### ISSUE TITLE
Define Log Level Use Cases

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#103]
We should collectively establish conventions for each log level and what sort of information we provide.

Also, ensure existing logged messages are of the appropriate level.

Please review the github package below for log level desc.

**Comment by dutterbutter** [comment]
https://github.com/inconshreveable/log15

**Comment by ansermino** [comment]
@amerameen the result of this should be added to our `CONTRIBUTING.md`

**Comment by ansermino** [comment]
I <3 complete sentences

**Comment by dutterbutter** [comment]
Please consider adding a stack trace for Log.Crit errors

**Comment by ansermino** [comment]
Use as few words as possible!

**Comment by amerameen** [comment]
Here is a first pass at it! Let me know your thoughts and we can refine them, especially if you think a level is unnecessary in our case or that we should add a level.

**Critical** - Very severe events that will cause the application to abort
**Error** - Severe events that may allow the application to keep running
**Warning** - Events that are potentially harmful or unintended
**Info** - Messages that provide information about the state of the application at a high-level
**Debug** - Fine-grained messages that are useful for debugging the application
**Trace** - Even more fine-grained messages than debug that may be useful for debugging the application
