### ISSUE TITLE
dot/state: batch db writes while syncing

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1033]
## Expected Behavior

- writing to the db should be batched where it can
- currently we write everything individually (slow!)
- we should batch all writes then flush it to disk every so often eg. flush when a block is finalized, when the node shuts down. 

places this could be implemented:
- `TrieState.WriteTrieToDB`

- when syncing from genesis, begin a new batch tx, since you can assume you'd sync many blocks 
- add functionality to know when you are syncing in the `StorageState` and batch the new state writes (`StoreTrie`) once syncing is done (or the node shuts down), this way the new state write doesn't block (sync service could set `StorageState.Syncing()` or such)
- in `blockState`, can also batch writes in `AddBlock` when syncing

NOTE: please approximately benchmark sync time before and after this is done to confirm sync time improves

**Comment by arijitAD** [comment]
Already implemented. Closing the PR.
