### ISSUE TITLE
Request justification in block request message

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#1062]
## Expected Behavior

in `syncer.createBlockRequest` we should request the block justification.

note: currently, there is no way to verify the received justification without some sort of block number -> set ID mapping (will open another issue for that)

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
closing due to inaccuracy - a finalization message already contains the justification, updating #1051 to specify verification details
