### ISSUE TITLE
failed to generate keypair use command line

### ISSUE THREAD

**Issue by cscjoke** [ChainSafe/gossamer#1064]
## Expected Behavior

- generate keypair

## Current Behavior

- when use `./gossamer account --generate` and enter the password to generate keypair it returns 

```sh
INFO[08-10|09:12:03] [cmd] loading default configuration...   id=gssmr
INFO[08-10|09:12:03] [cmd] generating keypair...
Enter password to encrypt keystore file:
>
EROR[08-10|09:12:06] [cmd] failed to generate keypair         error="failed to get keystore directory: failed to create data directory: mkdir /home/ubuntu/.gossamer/gssmr/keystore: no such file or directory"
failed to get keystore directory: failed to create data directory: mkdir /home/ubuntu/.gossamer/gssmr/keystore: no such file or directory
```

## Steps to Reproduce

1. Get the source code and build gossamer: `make gossamer`
2. cd bin directory and execute `./gossamer account --generate`
3. enter the password

## Specification

- go version: `go1.14.1
- gossamer version: 0.0.1
- gossamer commit tag:  v0.1.0
- gossamer commit hash: 531be2bb8d53b949fa0554182ae47533da563384
- operating system: Ubuntu 18.04
- additional links: NA

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
This should work if you do `gossamer init` beforehand, however, it should work without initialization, we will work on updating that. Thanks for bringing this to our attention!

**Comment by cscjoke** [comment]
use `mkdir -p /home/ubuntu/.gossamer/gssmr` create the directory and execute `./gossamer account --generate` it run well
