### ISSUE TITLE
re-run lottery when babe.SetThreshold is called

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#1065]
## Expected Behavior

- BABE lottery should be re-run after epoch threshold has been set/changed.

## Current Behavior

- `babe.SetEpochThreshold` does not re-run BABE lottery when epoch threshold is set.

## Possible Solution

- Update `babe.SetEpochThreshold` to re-run lottery when it's called.

## Steps to Reproduce

1.
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
no longer relevant, see https://github.com/ChainSafe/gossamer/issues/1206
