### ISSUE TITLE
[ENTRYPOINT] command

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#109]
Within a cmd/ directory create the entry point to begin running the node
- start libp2p host: (`p2p.NewService()`, `Service.Start()`)
- create rpc server (`rpc.NewServer()`, NOTE: Server currently does nothing, so it should probably be stubbed with a `_` to avoid compilation issues)
- initialize DB (see https://github.com/ChainSafe/gossamer/blob/4fdb956ca22c24893545eed9f98c9c5f9872e1c3/polkadb/database_test.go#L35)

Consideration should be made for the CLI params to be passed in (#90)

**Comment by dutterbutter** [comment]
I'd also suggest the following:
- parsing config.toml for easy config
- registering RPC services (modules)

**Comment by dutterbutter** [comment]
Initital entry point `dustin/test-entrypoint`
