### ISSUE TITLE
Update Runtime API for v0.8

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#1104]

**Comment by FlorianFranzen** [comment]
I have been looking at the way wasm imports are currently being handled in Gossamer and this is my observation.

First of all, I think you should invest some time in removing the requirement that imports have be be expected in a fixed order. Substrate does not have that requirement and the average dev will expect them to be matched by name.

It will also make switching between different versions of the runtime much easier.

[Here](https://github.com/paritytech/substrate/blob/master/client/executor/wasmtime/src/imports.rs#L37) is for example how substrate matches the imports with wasmtime under rust. It resolves each import by type and name and then generates the list of externs that way.

Secondly your current list of exports seems to be quite different from the latest runtimes, like Kusama v2025 or Polkadot v25. So for the host-api test, I am not so sure which ordering to use in the long run. Personally I would prefer to keep the none legacy version as close to upstream as possible.
