### ISSUE TITLE
Inconsistencies with spec

### ISSUE THREAD

**Issue by Warchant** [ChainSafe/gossamer#113]
I am implementing [Trie](https://github.com/ChainSafe/gossamer/tree/development/trie) for C++ looking at [spec](https://github.com/w3f/polkadot-re-spec) and your trie implementation.

I've found some inconsistencies and I want to get some feedback on them.

Lets start with this one:
https://sourcegraph.com/github.com/ChainSafe/gossamer/-/blob/trie/node.go#L151

According to spec, depending on a node type, two **most significant** bits must be set according to the rule below.
![image](https://user-images.githubusercontent.com/1867551/57071234-743bde00-6ce2-11e9-954b-f59323de63ca.png)

In your current code, you set two **least significant bits**. Why?

```go
func (l *leaf) header() []byte {
	var header byte = 1
        ...

func (b *branch) header() []byte {
	var header byte
	if b.value == nil {
		header = 2
	} else {
		header = 3
	}
         ...
```

Is this an implementation mistake?

**Comment by Warchant** [comment]
@noot bump

**Comment by noot** [comment]
@Warchant sorry for the late response, been off the grid for a week.  it looks like you are correct and this was an implementation mistake - I'll fix it up now. thanks so much for pointing this out!

**Comment by Warchant** [comment]
I propose to collaborate and create a test set for codec and trie, since both our tries should be compatible.
Can we start a chat on Riot or maybe on slack? Telegram?

**Comment by noot** [comment]
yes, that is definitely a good idea. there is currently this repo being working on by w3f: https://github.com/w3f/polkadot-re-tests 
however, there are only tests for SCALE in there currently. maybe we can open a discussion with them about creating trie test vectors, since it should also be compatible with Substrate. we can message on Riot :)
