### ISSUE TITLE
Error trying to restart node: failed to retrieve :code from trie: trie with given root does not exist:

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#1152]
## Expected Behavior

- Should be able to restart node that was previously stopped without error.

## Current Behavior

- Sometimes node will give error when trying to start a node that was stopped. 
```
INFO[10-28|15:52:48] initializing node services...            pkg=dot name=gssmr id=gssmr basepath=/home/emack/.gossamer/alice_test caller=node.go:222
INFO[10-28|15:52:48] creating state service...                pkg=dot caller=services.go:47
EROR[10-28|15:52:48] failed to create node services           pkg=cmd error="failed to retrieve :code from trie: trie with given root does not exist: 0x304c0ae83b66ac958ca62255ebbcc79f92d41abd0cabe96784785c9399c83f04" caller=main.go:205
failed to retrieve :code from trie: trie with given root does not exist: 0x304c0ae83b66ac958ca62255ebbcc79f92d41abd0cabe96784785c9399c83f04

```

## Possible Solution

- 

## Steps to Reproduce

1. Init node (Using genesis_oneauth.json config) and start
2. Stop node
3. Try starting again, you may get this error.  I have not found a pattern to re-create the error every time.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by dutterbutter** [comment]
Closing for now.
