### ISSUE TITLE
wasmtime: match imports by name

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1165]
## Expected Behavior

- wasmtime should match imports by name

## Current Behavior

- currently, it matches them based on position. this is not ideal since it requires new imports functions for runtimes that may have the same imports, but in a different order

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by FlorianFranzen** [comment]
[Here](https://github.com/paritytech/substrate/blob/master/client/executor/wasmtime/src/imports.rs#L37) is how substrate does it for their wasmtime backend.

**Comment by noot** [comment]
see https://github.com/bytecodealliance/wasmtime-go/issues/37#issuecomment-700890816
