### ISSUE TITLE
make lint pathing issue on Manjaro/Arch 

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/gossamer#1188]
## Expected Behavior

- `make lint` functions without failure on Arch (Manjaro)

## Current Behavior

- `make lint` crashes when looking for env variables
```
make ✖ ERR  not found: make-$(GOLANGCI)
```

## Possible Solution

- [Go sub module pathing issues](https://bbs.archlinux.org/viewtopic.php?id=235103)

## Steps to Reproduce

1. `make gossamer` 
2. `make lint`

## Specification

- go version: go version go1.15.2 linux/amd64
- gossamer version: latest
- gossamer commit tag: optional.Boolean type implemented
- gossamer commit hash: 22013125c1a46bf9370ec1de8ca5acdb8a55739b
- operating system: Manjaro
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I am planning to submit a pull request to fix this issue myself

**Comment by dutterbutter** [comment]
@RyRy79261 is this still relevant?

**Comment by RyRy79261** [comment]
@dutterbutter Seems its functioning as expected
