### ISSUE TITLE
Documentation - Block Production Flow Diagrams

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#1212]
Based on the Gossamer onboarding presentations, create diagrams and associated descriptions of Block Production in Gossamer

**Comment by arijitAD** [comment]
Added diagram  https://www.notion.so/chainsafe/Gossamer-Onboarding-bdb6b1d7b1d4410eaf33187494e4f7d0#ad14a03693694de29c1a8d4a926634fe
