### ISSUE TITLE
implement 128 bit unsigned integer

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#1235]
## Expected Behavior

- The node should work with runtime that uses u128 values.  [https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1432-u32--u64--u128](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1432-u32--u64--u128) specifies that unsigned integers should include a u128.
- Account balance in a u128.

## Current Behavior

- Does not currently handle uint128.

## Possible Solution

- Implement uint128.

## Steps to Reproduce

1.
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [ ] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [ ] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by arijitAD** [comment]
We can probably use a package from `CockroachDB` https://github.com/cockroachdb/cockroach/blob/master/pkg/util/uint128/uint128.go

**Comment by noot** [comment]
we might need to make our own since it looks like the above package uses big endian, but in gossamer we use little endian
