### ISSUE TITLE
Code coverage is failing for unit tests.

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1255]
## Expected Behavior

- cc-reporter should work.

## Current Behavior

Error:
```
/home/runner/work/gossamer/gossamer/cc-reporter: 2: /home/runner/work/gossamer/gossamer/cc-reporter: Syntax error: "(" unexpected (expecting ")")
```
![Screenshot 2020-12-21 at 12 54 42 PM](https://user-images.githubusercontent.com/5843604/102750418-c20bcb00-438b-11eb-9666-39f76e249d1a.png)

## Possible Solution

- Investigate the issue with cc-reporter.

## Steps to Reproduce

https://github.com/ChainSafe/gossamer/pull/1242/checks?check_run_id=1587449812

1. Raise a PR.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by dutterbutter** [comment]
Investigating the issue. I have opened an issue with [paambaati/codeclimate-action](https://github.com/paambaati/codeclimate-action/issues/275) as I cannot see why it would be erroring on the `before-build` check and was previously working on prior builds. Might be related to [codeclimate/test-reporter/issues/449](https://github.com/codeclimate/test-reporter/issues/449).

I will open a PR removing it as a required check if necessary.
