### ISSUE TITLE
encode Light protocol messages with protobuf

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1265]
## Expected Behavior

- Light protocol messages should be encoded with protobuf as described in section 4.2 of the spec
- See spec [section 4.2 for more details here](https://github.com/w3f/polkadot-spec/blob/master/host-spec/c04-networking.tm#L264)

## Current Behavior

- currently encoded with SCALE

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by P1sar** [comment]
Stale
