### ISSUE TITLE
ext_crypto_sr25519_verify_version_1 / version_2 : determine changes made in schnorrkel

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1285]
## Task summary

- there are currently two versions of `ext_crypto_sr25519_verify`
- version 1 uses older (pre-audit?) version of schnorrkel (used at start of kusama)
- version 2 uses current version of schnorrkel (current kusama and all of polkadot)
- seems like the signing algorithm has been updated between the two, need to determine exactly what was changed and make that update in go-schnorrkel
- then update `ext_crypto_sr25519_verify_version_2` accordingly

## Specification reference

- `E.3.8. ext_crypto_sr25519_verify`

## Other information and links

-

**Comment by FlorianFranzen** [comment]
Version 2 was introduced in paritytech/substrate#5336. As you can see in the diff the verifiy of `...version_2` is provided by schnorrkel while `..._version_1` uses a [special deprecated verify](https://github.com/paritytech/substrate/blob/master/primitives/core/src/sr25519.rs#L592).

**Comment by noot** [comment]
@FlorianFranzen great, thank you for the info!
