### ISSUE TITLE
Improvements on table driven tests

### ISSUE THREAD

**Issue by decanus** [ChainSafe/gossamer#130]
When running multiple tests in a single test function, [t.Run](https://golang.org/pkg/testing/#T.Run) should be used. This allows to clearly state which iteration of the test has failed. Which would be useful for tests like [these](https://github.com/ChainSafe/gossamer/blob/development/polkadb/database_test.go#L76).

Example usage is 
```golang
for _, v := range tests {
    t.Run(v, func(t) {
         // @todo run test
    })
}

```

For a longer guide check out [this](https://blog.golang.org/subtests).

**Comment by noot** [comment]
cool, thanks for pointing this out. we will be updating our tests :)

**Comment by nivida** [comment]
@GregTheGreek told me to drop a comment here because of the on-going sprint planning. I'm currently working on it as an introduction to Go and tests. I'm going to open a PR soon.

**Comment by ryanchristo** [comment]
@nivida sweet, let us know if you have any questions

**Comment by ryanchristo** [comment]
cc @nivida are you still working on this?

We have been doing a lot of refactoring lately and implementing test cases in some packages so we just wanted to check in and see what you have been or what you are/were planning to work on.
