### ISSUE TITLE
Connection to polkadot.js.org/apps fails

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#1314]
## Describe the bug

- When trying to connect https://polkadot.js.org/apps/ to gossamer node it fails with error message in browser console `disconnected from ws://127.0.0.1:8546/ : 1006 : Abnormal Closure` 

## Expected Behavior

- The website should connect to configured node and start displaying blocks built in explorer.

## Current Behavior

- The web site continually tries to connect, displaying message `Waiting to make a connection to the remote endpoint and finishing API initialization.` 
- Tried with gossamer node running rpc flag external, and ws-external, still no connection.
- NOTE: polkadot.js apps does work when running and connecting from a local server:
     -  Following instructions in README it http://github.com/polkadot-js/apps:
     - Install Node.js
     - clone polkadot-js/apps repo
     - build `yarn`
     - start `yarn run start`
     - point to http://localhost:3000/ and configure to use local node (ws://127.0.0.1:8546) for polkadot-js/apps will connect to local running gossamer node.

## Possible Solution

-

## To Reproduce

1. go to https://polkadot-js.org/apps/
2. Configure to use custom node ws://127.0.0.1:8546
3. Start gossamer and try web site will try to connect.
4. Review browser console logs to see error.
 

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
</br>

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by RyRy79261** [comment]
So the default Toml file doesn't enable the websocket server by default, enabling allows the Polkadot app to connect, no block info is rendering but yeah

**Comment by edwardmack** [comment]
Update: further testing has determined that seem to only be an issue with the Brave browser (Version 1.18.77).  
- When testing with Google Chrome (Version 87.0.4280.141) works.
- Testing with Firefox (Version 85.0) works.
