### ISSUE TITLE
update BABE slot time calculation on start-up

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1317]
## Task summary

- substrate doesn't use relative time currently (ie. `babe.Service.getCurrentSlot` can be unused)
- when the node starts up, it should set the current slot as the slot based on non-relative time (unix time / slot duration)

**Comment by FlorianFranzen** [comment]
I would say it does not use relative time yet, as it is still planned to be implement. However at the moment there are still various open questions around joining the network using relative time (e.g. w3f/polkadot-spec#263).

Therefore I would recommend disabling it instead of throwing it all away.

**Comment by noot** [comment]
good to know, I'll update the issue description
