### ISSUE TITLE
fix BABE VRF proof verification

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1320]
## Task summary

- currently, verifying the BABE VRF output and proof fails with kusama
- it seems like the transcript used by substrate is different from gossamer, causing this issue: https://github.com/paritytech/substrate/blob/master/primitives/consensus/babe/src/lib.rs#L94
- there may be some differences in rust-schnorrkel and go-schorrkel also

## Other information and links

- related to #1134

**Comment by FlorianFranzen** [comment]
So it turns out the issue I was thinking about was only present in the runtime (see paritytech/substrate#5785), so it probably not related. So lets see what an update to the transcript does.

**Comment by noot** [comment]
@FlorianFranzen I recently updated the transcript to fix the threshold verification, and it didn't seem to fix the VRF proof verification :/ the slot, epoch, output and proof match what is on polkascan so going have to look into it more
