### ISSUE TITLE
error sending websocket message after client disconnect

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#1325]
## Describe the bug

- Clients can connect to gossamer nodes via websocket connection, when the client disconnects, gossamer continues to try sending messages to them.  Fix this so that when the client disconnects, gossamer will close the connection instead of continuing to try sending messages.

## Expected Behavior

- After a connected websocket client disconnects gossamer node should close the connection.

## Current Behavior

- After a websocket client disconnects from gossamer, gossamer continues to try sending messages, resulting in error `EROR[01-21|10:46:10] error sending websocket message          pkg=rpc error="websocket: close sent" caller=websocket.go:340`

## Possible Solution

- Watch for disconnections, and close connection when disconnected.

## To Reproduce

1. 
2. 
3. 

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
</br>

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by noot** [comment]
closing for now since it no longer seems to be an issue
