### ISSUE TITLE
prune trie nodes from database

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1361]
## Task summary

- currently, we never prune trie nodes from the database
- there are 2 cases we want to remove nodes from the database: 1. when a chain is finalized, we want to delete any nodes that are in non-finalized forks but are not in the canonical chain; 2. if we are not an "archive node" we want to delete any nodes from blocks earlier than some block in the chain, that are not being used by any blocks higher than that.
- this issue is to determine when a trie node and its child nodes are no longer used, and to then delete them from the database
- reference counting is a possible solution, but needs more research

**Comment by dutterbutter** [comment]
Initial research for this issue -> https://hackmd.io/NYtcmdM_QVanSVfTyKbssg

We will start with implementing offline bloom filters.
