### ISSUE TITLE
Use `Sync.Pool` for trie node allocation and deallocation.

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1377]
## Issue summary

- There are two types of a trie node: leaf and branch.
- We can use `Sync.Pool` to reuse trie nodes which may be deallocated when delete is called or when generation is updated.
- If a large number of nodes are created and deleted then `Sync.Pool` has better performance than creating and deleting memory from the heap.

## Other information and links

- https://golang.org/pkg/sync/#Pool

**Comment by noot** [comment]
@arijitAD  can we get more info on this?

**Comment by timwu20** [comment]
This will be noted for further trie package refactors.
