### ISSUE TITLE
fix ext_crypto_sr25519_verify_version_1

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1393]
## Describe the bug

- `ext_crypto_sr25519_verify_version_1` fails to verify transactions in kusama block `3876` and onwards, causing `execute_block` to fail
- determine the issue and resolve it

**Comment by danforbes** [comment]
@noot mentioned that this may not actually be a problem. It looks like version 1 of this API (referenced in this Issue) has been deprecated (ref: https://w3f.github.io/polkadot-spec/develop/sect-crypto-api.html#sect-ext-crypto-sr25519-verify). I wonder if we just need to be using version 2 (declared in Gossamer here https://github.com/ChainSafe/gossamer/blob/v0.6.0/lib/runtime/wasmer/imports.go#L33)?

**Comment by noot** [comment]
closing this for now as this isn't an issue but actually the intended behaviour
