### ISSUE TITLE
Add Prometheus and Grafana for metric tracking/monitoring

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/gossamer#1398]
## Task summary

- Add [prometheus](https://prometheus.io/) and [grafana](https://grafana.com/) to provide insights and metrics
- Some initial node metrics to consider tracking
         -  CPU usage
         -  client memory usage
         -  Disk usage
         -  Network traffic
         -  Participation rate 
         -  Peer count
         -  Error rate

## Other information and links

-

**Comment by noot** [comment]
also would be good to add peer scores
