### ISSUE TITLE
research and implement scoring for network sync module

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1399]
## Task summary

- scoring should be used when determining who to try to sync from first
- basic premise is score goes up when you successfully receive a response from a peer, score goes down otherwise
- research how to ideally implement this so that peers we are more likely to get a response from are prioritized without completely ignoring other/new peers

**Comment by arijitAD** [comment]
WIP: Peer scoring https://hackmd.io/@FyilpQ7sQ265a9xyqSxyLg/B1EIbIIfY
