### ISSUE TITLE
[RPC/Grandpa] ProveFinality - Update for AuthorityID handling 

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/gossamer#1404]
## Issue summary

The ProveFinality rpc call needs to be updated to enact the AuthorityID logic defined in [the spec](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#17-grandpa)

## Other information and links

- https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#17-grandpa

**Comment by EclesioMeloJunior** [comment]
Question: do we need the `round id` with the `authority set id` to recovery a specific block hash justification? @noot

**Comment by timwu20** [comment]
> Question: do we need the `round id` with the `authority set id` to recovery a specific block hash justification? @noot

@noot said you need both

**Comment by jimjbrettj** [comment]
stale issue
