### ISSUE TITLE
update ext_crypto_start_batch_verify and ext_crypto_finish_batch_verify to use go-schnorrkel BatchVerify

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1405]
## Task summary

-  see https://github.com/ChainSafe/go-schnorrkel/blob/master/batch.go#L69
- now, when starting batch, we can create a new `schnorrkel.BatchVerifier`
- use `Add` to add a new signature, and `Verify` to finish verification

**Comment by noot** [comment]
can use this library for ed25519 batch verification: https://github.com/hdevalence/ed25519consensus/blob/main/batch.go

**Comment by danforbes** [comment]
@noot I have removed this from the cross-client devnet Epic for now #1356 - does that seem correct? I think you mentioned that these methods may be deprecated, although they still seem to appear in the spec (ref https://w3f.github.io/polkadot-spec/develop/sect-crypto-api.html#sect-ext-crypto-start-batch-verify). I think this may still be worth doing but I don't see how it directly relates to #1356

**Comment by timwu20** [comment]
This isn't required anymore. They've deprecated these host api functions.
