### ISSUE TITLE
add import/export of state snapshot

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/gossamer#1412]
## Task summary

- Investigate if we are able to export and import a snapshot of the state
- If changes need to be done, we would be able to make those changes, import a snapshot and begin syncing at the block height we left off from

## Specification reference

- 

## Other information and links

-

**Comment by noot** [comment]
closing since state export (from gossamer) and then import into gossamer does work, see https://hackmd.io/@nZ-twauPRISEa6G9zg3XRw/SJ8BgXOXO
