### ISSUE TITLE
Integrate fuzz testing in Gossamer

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1452]
## Issue summary

- Fuzz adds random data to `struct` for testing.
- We can generate random value to test things like scale encode/decode, Trie APIs, etc...

## Other information and links

- https://medium.com/a-journey-with-go/go-fuzz-testing-in-go-deb36abc971f
- https://github.com/dvyukov/go-fuzz

**Comment by noot** [comment]
duplicate of #2119 and #2089
