### ISSUE TITLE
Assess and refactor time intensive unit-tests

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/gossamer#1472]
## Issue summary

- Improve the speed of certain tests by assessing if resources can be shared, move to parallel table driven tests, or the use of `gomock`
- Below is a table of the longest taking unit test packages

|  Package 	|  Time taken  	|   
|---	|---	|
|   `github.com/ChainSafe/gossamer/dot`	| ~350.508s	|  
|   `github.com/ChainSafe/gossamer/dot/core`	| ~311.674s 	|  
|   `github.com/ChainSafe/gossamer/lib/babe`	| ~571.752s  	|  
|   `github.com/ChainSafe/gossamer/dot/sync`	| ~297.813s 	|  
|   `github.com/ChainSafe/gossamer/lib/runtime/wasmer`	| ~225.374s |  
|   `github.com/ChainSafe/gossamer/dot/rpc/modules`	| ~614.548s	|  

## Other information and links

-

**Comment by danforbes** [comment]
As of 2022-01-07 our unit tests are taking about 30  min to complete (ref: [CI for #2142)](https://github.com/ChainSafe/gossamer/runs/4731601331?check_suite_focus=true)

|Package|Time taken|
|-----------|---------------|
`github.com/ChainSafe/gossamer/dot`|~363.234s (increased)
`github.com/ChainSafe/gossamer/dot/core`|~356.770s (increased)
`github.com/ChainSafe/gossamer/lib/babe`|~466.412s (decreased :tada:)
`github.com/ChainSafe/gossamer/dot/sync`|~151.814s (decreased :tada:)
`github.com/ChainSafe/gossamer/lib/runtime/wasmer`|~196.737s (decreased :tada:)
`github.com/ChainSafe/gossamer/dot/rpc/modules`|~0.417s (decreased BIGLY 🎉 🎉 :tada:)

**Comment by noot** [comment]
@danforbes what's the status on this?

**Comment by danforbes** [comment]
My understanding is that @edwardmack is actively working on Issues that should fall under this Epic. @timwu20 do you have any thoughts on a "definition of done" for this Epic?

**Comment by timwu20** [comment]
I believe we've made good progress on this.  We should create a new epic to track this effort for any remaining packages.
