### ISSUE TITLE
Use buffered channels for websocket listener.

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1478]
## Issue summary

- Since, an unbuffered channel is blocking, it is 4x slower than a buffered channel.
- Channels should always be buffered unless we need blocking behaviour.
```
BenchmarkBufferedChannelEmptyStruct-8         23657084            49.9 ns/op
BenchmarkBufferedChannelOneByte-8             21230530            54.6 ns/op      18.31 MB/s

BenchmarkUnbufferedChannelEmptyStruct-8        6075384            177 ns/op
BenchmarkUnbufferedChannelOneByte-8            6341457            184 ns/op       5.44 MB/s
```

## Other information and links

- https://tpaschalis.github.io/channels-limitations-speed/

**Comment by edwardmack** [comment]
Closed, this issue was addressed in PR #1668.
