### ISSUE TITLE
create gossamer devnet and document issues

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1479]
## Task summary

- create a gossamer devnet with multiple authority nodes
- let devnet run for a couple days and document any issues

**Comment by noot** [comment]
first issue: the node doesn't seem to produce the BABE NextEpochData digest needed for the next epoch in the first block of an epoch, I thought this was produced by the runtime but it doesn't look like it is. this is the same for the substrate default node runtime and the polkadot/kusama runtimes. asked for clarification as to whether this is produced by the runtime or the host

**Comment by danforbes** [comment]
Closing as duplicate as #592. I have moved any remaining Issues from this Epic under that one. @noot - do we still need to track this?

> first issue: the node doesn't seem to produce the BABE NextEpochData digest needed for the next epoch in the first block of an epoch, I thought this was produced by the runtime but it doesn't look like it is. this is the same for the substrate default node runtime and the polkadot/kusama runtimes. asked for clarification as to whether this is produced by the runtime or the host
