### ISSUE TITLE
implement `--telemetry-url` Parameter

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#1502]
## Issue summary

Implement a command line parameter for Gossamer's default execution action that can be used to specify the endpoint to which Gossamer should send telemetry metrics. The default value is https://telemetry.polkadot.io/, however, it may be desirable to use an alternate UI or a local instance of [the telemetry service that is provided by Parity](https://github.com/paritytech/substrate-telemetry). The Rust implementation of the Polkadot node accepts two arguments to this parameter: one that specifies the URL and one that specifies the verbosity level. See below for [a comment regarding the verbosity level](https://github.com/ChainSafe/gossamer/issues/1502#issuecomment-934680300). It is unclear at this time whether or not it's necessary or even important for Gossamer to support configuration of telemetry verbosity at this point; if necessary, we can create a separate Issue to track that as a future task.

**Comment by danforbes** [comment]
Here are some thoughts from one of the contributors to Substrate Telemetry around this issue in terms of what that code base is expecting for verbosity levels

> Good question; I'm not actually certain, to be honest, but from testing it appeared that verbosity level 0 was enough to still have a node advertise useful telemetry information! Seeing which messages are sent with which verbosity requires digging into the substrate code, which isn't quite as simple to do!

> Aside from peering into substrate code, you could also point a node at your own WebSocket server and just record the messages that come in at different verbosity levels to get an idea!
