### ISSUE TITLE
Trie root hash does not match the result from rust implementation 

### ISSUE THREAD

**Issue by drskalman** [ChainSafe/gossamer#151]
```
$ ./run_tests.sh
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/polkadot-re-tests/build
[100%] running cargo
    Finished dev [unoptimized + debuginfo] target(s) in 0.77s
[100%] Built target rust_tester_target
[100%] Built target go_tester
[100%] Built target go_tester_all
[100%] running cargo
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
[100%] Built target rust_tester_target
[100%] Built target go_tester
[100%] Built target go_tester_all
Install the project...
-- Install configuration: ""
-- Up-to-date: bin/usr/local/bin/rust_tester
-- Installing: bin/usr/local/bin/go_tester
Test Summary:     | Pass  Total
Scale Codec Tests |    6      6
  2.552807 seconds (4.40 M allocations: 226.640 MiB, 4.80% gc time)
WARNING: replacing module CommonFixtures.
WARNING: replacing module ScaleCodecFixtures.
WARNING: replacing module StateTrieFixtures.
state trie root: 0xa10270d88debdb7005451775b908c2d575a37bfed94daaa0b6fa14045372e45c

state root hash: 0x4213043100000000000000000000000000000000000000000000000000000000
State Trie Tests: Test Failed at /home/user/polkadot-re-tests/test/state_trie_tests.jl:18
  Expression: test_result_array[end] == test_result_array[CommonFixtures.reference_implementation]
   Evaluated: "state root hash: 0x4213043100000000000000000000000000000000000000000000000000000000" == "state trie root: 0xa10270d88debdb7005451775b908c2d575a37bfed94daaa0b6fa14045372e45c\n"
Stacktrace:
 [1] top-level scope at /home/user/polkadot-re-tests/test/state_trie_tests.jl:18
 [2] top-level scope at /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /home/user/polkadot-re-tests/test/state_trie_tests.jl:5
state trie root: 0x7cdd17212f13b5943c04cc48c59a4e2307f4b4f6370a4f10db2195b5ae90589c

state root hash: 0xb804236613fdec5bec79e990892cb84c7941af6cdd9879917221ca0655970f15
State Trie Tests: Test Failed at /home/user/polkadot-re-tests/test/state_trie_tests.jl:18
  Expression: test_result_array[end] == test_result_array[CommonFixtures.reference_implementation]
   Evaluated: "state root hash: 0xb804236613fdec5bec79e990892cb84c7941af6cdd9879917221ca0655970f15" == "state trie root: 0x7cdd17212f13b5943c04cc48c59a4e2307f4b4f6370a4f10db2195b5ae90589c\n"
Stacktrace:
 [1] top-level scope at /home/user/polkadot-re-tests/test/state_trie_tests.jl:18
 [2] top-level scope at /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /home/user/polkadot-re-tests/test/state_trie_tests.jl:5
Test Summary:      | Fail  Total
State Trie Tests   |    2      2
  State Trie Tests |    2      2
ERROR: LoadError: Some tests did not pass: 0 passed, 2 failed, 0 errored, 0 broken.
in expression starting at /home/user/polkadot-re-tests/test/runtests.jl:3

```

**Comment by noot** [comment]
I'm getting an error trying to run the tests:
```
elizabeth@elizabeth:~/polkadot-re-tests$ ./run_tests.sh 
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Cargo Home: /home/elizabeth/.cargo
-- Rust Compiler Version: 1.35.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/elizabeth/polkadot-re-tests/build
Scanning dependencies of target rust_tester_target
[100%] running cargo
    Updating crates.io index
error: failed to load source for a dependency on `parity-scale-codec`

Caused by:
  Unable to update /home/elizabeth/polkadot-re-tests/implementations/rust/parity-codec

Caused by:
  failed to read `/home/elizabeth/polkadot-re-tests/implementations/rust/parity-codec/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
test/testers/rust-tester/CMakeFiles/rust_tester_target.dir/build.make:64: recipe for target 'test/testers/rust-tester/x86_64-unknown-linux-gnu/debug/librust_tester.a' failed
make[2]: *** [test/testers/rust-tester/x86_64-unknown-linux-gnu/debug/librust_tester.a] Error 101
CMakeFiles/Makefile2:106: recipe for target 'test/testers/rust-tester/CMakeFiles/rust_tester_target.dir/all' failed
make[1]: *** [test/testers/rust-tester/CMakeFiles/rust_tester_target.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
[100%] running cargo
    Updating crates.io index
error: failed to load source for a dependency on `parity-scale-codec`

Caused by:
  Unable to update /home/elizabeth/polkadot-re-tests/implementations/rust/parity-codec

Caused by:
  failed to read `/home/elizabeth/polkadot-re-tests/implementations/rust/parity-codec/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
test/testers/rust-tester/CMakeFiles/rust_tester_target.dir/build.make:64: recipe for target 'test/testers/rust-tester/x86_64-unknown-linux-gnu/debug/librust_tester.a' failed
make[2]: *** [test/testers/rust-tester/x86_64-unknown-linux-gnu/debug/librust_tester.a] Error 101
CMakeFiles/Makefile2:106: recipe for target 'test/testers/rust-tester/CMakeFiles/rust_tester_target.dir/all' failed
make[1]: *** [test/testers/rust-tester/CMakeFiles/rust_tester_target.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Scale Codec Tests: Error During Test at /home/elizabeth/polkadot-re-tests/test/runtests.jl:4
  Got exception outside of a @test
  LoadError: ArgumentError: Package Debugger not found in current path:
  - Run `import Pkg; Pkg.add("Debugger")` to install the Debugger package.
  
  Stacktrace:
   [1] require(::Module, ::Symbol) at ./loading.jl:823
   [2] include at ./boot.jl:326 [inlined]
   [3] include_relative(::Module, ::String) at ./loading.jl:1038
   [4] include(::Module, ::String) at ./sysimg.jl:29
   [5] include(::String) at ./client.jl:403
   [6] top-level scope at /home/elizabeth/polkadot-re-tests/test/runtests.jl:4
   [7] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
   [8] top-level scope at /home/elizabeth/polkadot-re-tests/test/runtests.jl:4
   [9] top-level scope at util.jl:156
   [10] top-level scope at /home/elizabeth/polkadot-re-tests/test/runtests.jl:4
   [11] top-level scope at util.jl:156
   [12] include at ./boot.jl:326 [inlined]
   [13] include_relative(::Module, ::String) at ./loading.jl:1038
   [14] include(::Module, ::String) at ./sysimg.jl:29
   [15] exec_options(::Base.JLOptions) at ./client.jl:250
   [16] _start() at ./client.jl:436
  in expression starting at /home/elizabeth/polkadot-re-tests/test/scale_codec_tests.jl:3
Test Summary:     | Error  Total
Scale Codec Tests |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/elizabeth/polkadot-re-tests/test/runtests.jl:3
```

**Comment by noot** [comment]
I've modified the tests to print the encoded root nodes and this is the result:
```
[rust] encoded root: [3, 31, 4, 31]
[rust] len: 4

[go] encoded root: [42, 13, 4, 31]
[go] len 4

State Trie Tests: Test Failed at /home/elizabeth/polkadot-re-tests/test/state_trie_tests.jl:18
  Expression: test_result_array[end] == test_result_array[CommonFixtures.reference_implementation]
   Evaluated: "[go] encoded root: [42, 13, 4, 31]\n[go] len 4\n" == "[rust] encoded root: [3, 31, 4, 31]\n[rust] len: 4\n"
Stacktrace:
 [1] top-level scope at /home/elizabeth/polkadot-re-tests/test/state_trie_tests.jl:18
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /home/elizabeth/polkadot-re-tests/test/state_trie_tests.jl:5
[rust] encoded root: [fe, f0, 0, 80, 80, 5, 9c, 78, 6c, b9, bc, cd, d9, 1b, a, a6, a4, e1, 32, cb, 9c, 2f, bd, bd, 2d, b6, 5a, 37, b8, 6d, 5b, 59, 9c, 7, 84, 80, 73, 80, 8f, 8b, 67, 33, a6, bf, b2, ec, 10, 8c, e3, 15, ef, 27, 1d, 4f, 99, 33, 1d, e, 61, e3, dd, f1, b4, c6, 45, e, e7, c9, c5, 7b, 80, 3a, 97, f4, f6, 5, e6, 79, 8d, f2, d4, b5, 42, df, 8c, 9c, 43, e, 41, 74, 3d, 74, a1, a1, 14, 8f, 39, bb, c6, 66, d7, 2e, 92, 80, 59, 73, be, cf, 57, af, 51, 44, c6, 19, 74, a0, 7, d2, 71, ad, 40, a, 72, 3, 96, 4f, 9, e, 45, 2f, 51, dc, 4a, 81, c8, 4]
[rust] len: 136

[go] encoded root: [80, f0, 0, d5, 5f, 40, dd, 60, 0, ae, a4, 93, fb, dc, 60, 34, b7, 92, c2, e7, a5, 90, 6e, 75, 31, ce, 10, 17, a3, 88, d4, ce, b, cc, 64, 91, 34, 65, da, 18, ec, d4, 4f, 3, 64, f1, a6, 75, f3, bd, b8, 3, e6, 1, c1, 82, cb, 7, 6b, 9c, de, de, a7, 32, 1, 36, 42, b, 6a, e4, 47, 3d, 5, ab, cc, 8e, 87, 65, 88, 5b, 96, f6, 3d, 3e, 15, c8, b4, a7, 81, d6, 4b, 9e, cc, 2a, dc, f3, 55, cb, 66, fa, 7b, 42, c6, b9, d3, a2, 88, 63, b6, 63, 3b, f4, e9, ec, e0, ab, 55, 57, 2d, 6d, 32, cf, e2, e, 14, 29, 15, 60, 18, 6c, 5d]
[go] len 131

State Trie Tests: Test Failed at /home/elizabeth/polkadot-re-tests/test/state_trie_tests.jl:18
  Expression: test_result_array[end] == test_result_array[CommonFixtures.reference_implementation]
   Evaluated: "[go] encoded root: [80, f0, 0, d5, 5f, 40, dd, 60, 0, ae, a4, 93, fb, dc, 60, 34, b7, 92, c2, e7, a5, 90, 6e, 75, 31, ce, 10, 17, a3, 88, d4, ce, b, cc, 64, 91, 34, 65, da, 18, ec, d4, 4f, 3, 64, f1, a6, 75, f3, bd, b8, 3, e6, 1, c1, 82, cb, 7, 6b, 9c, de, de, a7, 32, 1, 36, 42, b, 6a, e4, 47, 3d, 5, ab, cc, 8e, 87, 65, 88, 5b, 96, f6, 3d, 3e, 15, c8, b4, a7, 81, d6, 4b, 9e, cc, 2a, dc, f3, 55, cb, 66, fa, 7b, 42, c6, b9, d3, a2, 88, 63, b6, 63, 3b, f4, e9, ec, e0, ab, 55, 57, 2d, 6d, 32, cf, e2, e, 14, 29, 15, 60, 18, 6c, 5d]\n[go] len 131\n" == "[rust] encoded root: [fe, f0, 0, 80, 80, 5, 9c, 78, 6c, b9, bc, cd, d9, 1b, a, a6, a4, e1, 32, cb, 9c, 2f, bd, bd, 2d, b6, 5a, 37, b8, 6d, 5b, 59, 9c, 7, 84, 80, 73, 80, 8f, 8b, 67, 33, a6, bf, b2, ec, 10, 8c, e3, 15, ef, 27, 1d, 4f, 99, 33, 1d, e, 61, e3, dd, f1, b4, c6, 45, e, e7, c9, c5, 7b, 80, 3a, 97, f4, f6, 5, e6, 79, 8d, f2, d4, b5, 42, df, 8c, 9c, 43, e, 41, 74, 3d, 74, a1, a1, 14, 8f, 39, bb, c6, 66, d7, 2e, 92, 80, 59, 73, be, cf, 57, af, 51, 44, c6, 19, 74, a0, 7, d2, 71, ad, 40, a, 72, 3, 96, 4f, 9, e, 45, 2f, 51, dc, 4a, 81, c8, 4]\n[rust] len: 136\n"
Stacktrace:
 [1] top-level scope at /home/elizabeth/polkadot-re-tests/test/state_trie_tests.jl:18
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /home/elizabeth/polkadot-re-tests/test/state_trie_tests.jl:5
Test Summary:      | Fail  Total
State Trie Tests   |    2      2
  State Trie Tests |    2      2
```

The results lead me to believe the rust implementation does not match the spec.

Regarding the first test: The first byte should be node type (most significant 2 bits) and partial key length (least significant 6 bits).  Firstly, the node type bits are placed in the least significant bits instead of most.  Secondly the node type for rust is branch w/ value (11) but should be leaf, since the trie has only one node and a branch is required to have children.  Thirdly it seems that the ordering of the nibbles in the partial key encoding is flipped.

Regarding the second test: First byte has same issue as above, except it also says that the root node has a partial key length > 63.  Based on the test data, the root node should have children only at indices (4, 5, 6, 7) and no partial key, so the partial key encoding is incorrect for rust. The length of the rust encoding seems to be wrong (5 bits too long) likely due to an incorrect partial key. The correct length should be 1 (header) + 2 (children bitmap) + 32*4 (4 child nodes each w/ 32 byte hash) = 131

**Comment by cheme** [comment]
Looking at encoded values, it seems like things can be explain by the spec child difference and the fact that a different codec was use in the rust test, except for the nibble encoding in the first test (2nd byte).
So I also think the nibble ordering is switch.
In rust we got 31 (0x31 which is hex value of 1 in utf8), which is BE encoding, while in go we have 0x13 which I infer is a LE encoding. I remember that the spec was LE at first but then switched back to BE.

**Comment by noot** [comment]
@cheme thanks for clarifying. I'll change our nibble ordering to BE. So is the node header correct for the rust? What encoding was being used for the rust test?

**Comment by cheme** [comment]
A few days backward I did test for [1, 7] with a debug println on the encoded root (before hashing) and I had  [42, 01, 04, 07] (1 and 7 are byte value not hex) so node header did match in this case.
If you want to test with the correct encoding in rust project their is at some place a `TrieStream` that need to be replaced with `TrieStreamNoExt` (I know the naming is not really explicit :).
The encoding for the rust test is the one currently in use for substrate (+ branch with partial nibble):
- Header encoding is totally different (uses range of value instead of bitmask so is a bit more compact but not really intuitive to use), 
- then the bitmask,
- then the partial (different encoding again: it uses an additional byte in the case of pair number of nibble (a header byte allow to check if the nibble number is pair or not which is not usefull when the size is already into the header), 
- then scale encoded childs (same as the modified spec),
- then scale encoded value (if node type is branch with value).
 it looks alike your test execution result (but please forget about it since it should be replaced soon with the polkadot-re one).

**Comment by noot** [comment]
@cheme I changed the `ReferenceTrieStream` in the tests to `ReferenceTrieStreamNoExt` and now the header matches :) I've also updated our code to encoding the key in BE and the test for [1,1] is the same now. There's still some discrepancy with the second test but I'll try to figure it out.  The lengths are the same now so it is probably some small issue somewhere. 

 Just to confirm, does this look like I'm using the correct trie with no ext? https://github.com/noot/polkadot-re-tests/blob/test-trie/test/testers/rust-tester/src/trie_tester.rs

**Comment by cheme** [comment]
yes seems correct :+1:

**Comment by noot** [comment]
cool thank you! is the partial key length encoding the same as the spec?

**Comment by noot** [comment]
it seems that for the branch encoding in rust, the `scale(value)` is being appended before the `scale(hash(child_0)) | ... | scale(hash(child_16))`, is that correct? 
I've changed that and I've added a few test cases and the rust + go match for my new cases, but the random_trie tests still have a hashing mismatch.

**Comment by cheme** [comment]
Oh yes, I just said to @drskalman the opposite information, I am very sorry.

Indeed the value is encoded before the children in the current rust implementation.

I can change it or we can change the spec, that is really not an issue. cc/ @drskalman .

I cannot really say where is the best place, maybe if we consider a stream decoding on an iteration algorithm we would display the branch value first so it will may make sense to put it before the childs (but we can probably have the opposite reasoning for other use case).

**Comment by noot** [comment]
no worries, I've just changed my implementation. so not an issue, but we should change the spec.

**Comment by noot** [comment]
@cheme is there a way I can print out the trie + its node encodings recursively? trying to debug this has been tough :p

**Comment by cheme** [comment]
you can try disp function at https://gist.github.com/cheme/2b44515dfef2e4f23ddff192e3fa84f5 (it uses a different hasher but the trie layout printed should be correct).
It will also requires changing the parent Cargo.toml to contain
```rust
#trie 
reference-trie = { path = "../../../implementations/rust/trie/test-support/reference-trie" }
keccak-hasher = { path = "../../../implementations/rust/trie/test-support/keccak-hasher" }
memory-db = { path = "../../../implementations/rust/trie/memory-db" }
hash-db = { path = "../../../implementations/rust/trie/hash-db" }
trie-db = { path = "../../../implementations/rust/trie/trie-db" }
trie-root = {path = "../../../implementations/rust/trie/trie-root"}
```
Not sure if it will really help (the display for big trie can be hard to read and there is not the encoded values), I could probably update my branch to test on blake and have a nice display trace, start of next week.
Otherwhise you can try to reduce the sample size by dichotomy, but I am not sure it can be done.

**Comment by noot** [comment]
Thanks so much! I'll try it out and see if it helps, it would be good to check that the trie structure matches so I can be sure it's the encoding.  A display trace for the blake and encoding would be really helpful too.

**Comment by cheme** [comment]
I created a iter_build callback which display encoded nodes (not totally the same algo as trie_root but should do the same).
Can be find in https://github.com/cheme/polkadot-re-tests/tree/test-trie  (git submodule need update not sure if the script do it).

**Comment by noot** [comment]
@cheme amazing, thank you so much. I'll take a look today and continue debugging :)

**Comment by noot** [comment]
I think our trie structure matches but there is some issue with encoding leaves: there is a branch
`[Node::NibbledBranch { index: 6, slice: 2, nodes: [Node::Leaf { index: 3, slice: 1'3'2'3'3, value: [53] }, Node::Leaf { index: 6, slice: 3'6'4, value: [50] }]` 
The two leaves get encoded like this in rust: `[48, 62, 31, 32, 33, 4, 35]` and `[47, 1, 62, 63, 64, 4, 32]`
In go they are encoded like this: `[45, 1, 32, 33, 4, 35]` and `[43, 3, 64, 4, 32]` 

It looks like the discrepancy is that in the rust code, the branch key and prefix that are directly above the leaf also get added to the encoded partial key. But this doesn't happen in go. Have I encoded the partial key incorrectly or is there some other issue?

**Comment by cheme** [comment]
go seems correct, I will check that.

**Comment by cheme** [comment]
The algo use to print the trace needs sorted data as input, I change a bit the code in my branch to run things sorted.
The original code uses a btreemap but it did the store utf8 string which sorted differently than their counterpart byte representation (as use in the trie).
The trace should look better.

**Comment by noot** [comment]
@cheme okay cool, let me know what you find out.

**Comment by cheme** [comment]
I reduce your test to 
```
keys:
  - 12345
  - azyx
  - Ye
  - Qui
  - Vo1
values:
  - 1
  - 1234567890asdfghjklmnbvcxzqertyuiop
  - 8
  - Yei1Iesh
  - Vo1Xavah
```
giving a trie like 
```
b -> 3 leaf(1)
|-> 5 b -> 1 leaf(semilong)
|       |-> 6 leaf(other semilong)
|       |-> 8 leaf(8)
|
|-> 6 leaf (long val one)
```
the difference is in the hash written for the last value in the root branch:
in rust I got
``` 
Encoded node: [47, 1, 7a, 79, 78, 8c, 31, 32, 33, 34, 35, 36, 37, 38, 39, 30, 61, 73, 64, 66, 67, 68, 6a, 6b, 6c, 6d, 6e, 62, 76, 63, 78, 7a, 71, 65, 72, 74, 79, 75, 69, 6f, 70]
	with prefix: ([], (1, 60))
	hashed to [2d, 82, 61, 4f, e8, 50, 1b, ce, 27, 26, aa, b9, 8d, 97, 41, 1b, 53, e9, c0, 88, ff, 8f, 41, 20, 65, 4b, d9, ce, 3b, cf, c3, bf]
```
corresponding to the end of the rust encoded root.
In go I got the same trace value : 
```
leaf encoding [47, 1, 7a, 79, 78, 8c, 31, 32, 33, 34, 35, 36, 37, 38, 39, 30, 61, 73, 64, 66, 67, 68, 6a, 6b, 6c, 6d, 6e, 62, 76, 63, 78, 7a, 71, 65, 72, 74, 79, 75, 69, 6f, 70]
[go] encoded root: [80, 68, 0, 20, 49, 1, 32, 33, 34, 35, 4, 31, 80, 8e, 3f, b5, 31, bd, 6c, 45, ed, 10, 5f, 30, 8e, 22, 56, d9, 31, 52, 84, 4, 1f, 1c, ec, d5, d6, 7d, fc, 91, b3, 1d, 69, fa, 5b, 
80, f0, a7, de, 2b, 45, 3c, d0, 43, 1e, a8, c5, a3, 4f, b9, ab, 4d, 7e, 4d, 33, e1, 1b, fe, 8d, 90, 3f, 97, 4, 8c, 26, 15, a4, a5]
```
But the root does not include the same hash value (portion after last 80)
in rust encoded root is:
```
[rust] encoded root: [80, 68, 0, 20, 49, 1, 32, 33, 34, 35, 4, 31, 80, 8e, 3f, b5, 31, bd, 6c, 45, ed, 10, 5f, 30, 8e, 22, 56, d9, 31, 52, 84, 4, 1f, 1c, ec, d5, d6, 7d, fc, 91, b3, 1d, 69, fa, 5b, 
80, 2d, 82, 61, 4f, e8, 50, 1b, ce, 27, 26, aa, b9, 8d, 97, 41, 1b, 53, e9, c0, 88, ff, 8f, 41, 20, 65, 4b, d9, ce, 3b, cf, c3, bf]
```
So I find my hash back in rust, I am a bit clueless about what is going wrong (other hashing did happen without difference).

**Comment by noot** [comment]
@cheme figured out the issue, in the branch child encoding, the hashing buffer wasn't being flushed every time. so it was hashing the wrong thing in children after the first.  I just fixed it and looks like the hashes match now!

**Comment by noot** [comment]
@drskalman please see my updated tests and confirm that the roots match https://github.com/noot/polkadot-re-tests/tree/test-trie 
my updated code is in this branch https://github.com/ChainSafe/gossamer/tree/elizabeth/trie-fix/trie
