### ISSUE TITLE
Implement external runtime crypto functions

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#152]
* ext_keccak_256 [done]
* ext_blake2_256 [done[
* ext_sr25519_verify [in progress] [(ChainSafe/gossamer#171)](https://zube.io/chainsafe-2/gossamer/c/207) 
* ext_ed25519_verify [done]
* ext_twox_128 [needs cgo] [(ChainSafe/gossamer#182)](https://zube.io/chainsafe-2/gossamer/c/225)

**Comment by noot** [comment]
relevant rust code: https://github.com/paritytech/substrate/blob/d713fbc358106ec7d400dea0a1d644a8448942ad/core/executor/src/wasm_executor.rs#L116

**Comment by ansermino** [comment]
Closed in favour of subtasks.
