### ISSUE TITLE
persist node name across restarts

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1522]
## Describe the bug

- node currently generates a new random name every time it starts, but it should create a random name when it starts for the first time and use that name every time it starts up afterwards (can write it to the db)

**Comment by EclesioMeloJunior** [comment]
is it a good idea to put the node name into de config.toml? And then load the name from the file whenever the node initializes or reinitializes?

**Comment by noot** [comment]
@EclesioMeloJunior the name can already be specified using the config file, this issue is so that a random name isn't generated every time the node restarts (if none is specified), the node should use the same name unless it becomes re-initialized

**Comment by EclesioMeloJunior** [comment]
@noot I thought of the following logic:

- If there's no flag name then try to retrieve the node name from the database.
- If the database result returns data then use it as node global name
- If the database result does not succeeded so generate a random name and store this one in the database

So, when the node initializes we will generate a random name and store it, and when the node reinitializes we will retrieve the persisted name.

But I have noticed that the method `dot.InitNode` calls the method `state.Service.Initialize` and this method executes
```
db.ClearAll()
```
So, if we store the node name at the database on initialization then when the node reinitialize the stored name will be lost?

**Comment by arijitAD** [comment]
> @noot I thought of the following logic:
> 
> * If there's no flag name then try to retrieve the node name from the database.
> * If the database result returns data then use it as node global name
> * If the database result does not succeeded so generate a random name and store this one in the database
> 
> So, when the node initializes we will generate a random name and store it, and when the node reinitializes we will retrieve the persisted name.
> 
> But I have noticed that the method `dot.InitNode` calls the method `state.Service.Initialize` and this method executes
> 
> ```
> db.ClearAll()
> ```
> 
> So, if we store the node name in the database on initialization then when the node reinitialize the stored name will be lost?

We initialize the node once but we can run it multiple times. Initialization is only needed if you want to start fresh.
