### ISSUE TITLE
Implement Go Standard Package folder structure

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#1527]
## Issue summary

- Many go projects with external packages utilize the `pkg` and `internal` root level folders.  Issue #1072 is looking to move SCALE into it's own package for external use.  Migrating `scale` to the `pkg` folder is a nice compromise and we can always move it out into it's own repo afterwards.
- Rename `lib` to `internal`.  The go compiler enforces that external applications that import packages will not be able to import packages that stored in an `internal` folder.  
- Create the `pkg` folder with the intention of putting the finished package from #1072 into the `pkg` folder.
- Audit the existing packages in `lib` and see which other packages we'd like to put in `pkg`.

## Other information and links

- https://github.com/golang-standards/project-layout

**Comment by qdm12** [comment]
- `lib/trie/proof`'s [trie proof verification](https://github.com/ChainSafe/gossamer/blob/a1e127bc4f8504a5e5db6146944b3a51320a8fbe/lib/trie/proof/verify.go#L28)
- `lib/trie`'s `NewEmptyTrie()` function and trie `Put`, `Hash`, `Delete`, methods are used [here](https://github.com/w3f/polkadot-tests/blob/9f9b437b716e6b9bb0a564563c7400b2c040234d/adapters/gossamer/state_trie.go)
- `pkg/scale`  is used by https://github.com/w3f/polkadot-tests/blob/9f9b437b716e6b9bb0a564563c7400b2c040234d/adapters/gossamer/scale_codec.go#L25
- `lib/common`'s `Hash` is used by https://github.com/w3f/polkadot-tests/blob/9f9b437b716e6b9bb0a564563c7400b2c040234d/adapters/gossamer/state_trie.go#L90
- `lib/runtime` is used by https://github.com/w3f/polkadot-tests/tree/main/adapters/gossamer/host_api
