### ISSUE TITLE
Implement External Trie Runtime Functions

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#153]
- ext_clear_storage
- ext_set_storage
- ext_exists

See spec, Appendix A.

**Comment by noot** [comment]
relevant rust code: https://github.com/paritytech/substrate/blob/d713fbc358106ec7d400dea0a1d644a8448942ad/core/executor/src/wasm_executor.rs#L116

**Comment by noot** [comment]
this is done, will pr once wasmer issues are fixed
