### ISSUE TITLE
Non authority node fails to handle block announce message.

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1538]
## Issue summary

- Non-authority node fails to read block announce message.

## Other information and links

- Continuation of #1482

**Comment by noot** [comment]
@arijitAD is the problem that it doesn't get the full block after receiving the block announce, or that it can't process the full block?

**Comment by arijitAD** [comment]
> @arijitAD is the problem that it doesn't get the full block after receiving the block announce, or that it can't process the full block?

The issue has two parts:
1. Non-authority node reads data from stream incorrectly. (Fixed)
2. Even after fixing the read, the block announce message is not handled properly. (Currently Investigating)
