### ISSUE TITLE
determine how to add new authority node to existing network

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1549]
## Task summary

- while the devnet is running, we will want to add new authority nodes to make sure that functionality works
- will likely be done through runtime staking module, need to determine how exactly this is done

**Comment by danforbes** [comment]
@arijitAD - is this currently being worked on, or should we move it to inactive?

**Comment by arijitAD** [comment]
We need to retest this once syncing algorithm is done.

**Comment by noot** [comment]
closing at this has been determined. in the future we should write our own runtime to allow a sudo key to add/remove validators for easy testing
