### ISSUE TITLE
Cannot run make build

### ISSUE THREAD

**Issue by kanishkatn** [ChainSafe/gossamer#1556]
## Describe the bug
Getting `invalid version` error on `github.com/ChainSafe/go-schnorrkel@v0.0.0-20210127175223-0f934d64ecac` during `make gossamer`

## Expected Behavior

Should build

## Current Behavior

Throws the following error

`go: github.com/ChainSafe/go-schnorrkel@v0.0.0-20210127175223-0f934d64ecac: invalid version: unknown revision 0f934d64ecac`

## Possible Solution

Use the correct version

## To Reproduce

1. Clone the repo 
2. run `make gossamer`

## Log output

$ make gossamer
```
rm -fr ./bin
cd cmd/gossamer && go build -o ../../bin/gossamer && cd ../..
go: github.com/ChainSafe/go-schnorrkel@v0.0.0-20210127175223-0f934d64ecac: invalid version: unknown revision 0f934d64ecac
```

## Specification

- go version: 1.15.2
- gossamer version: development

**Comment by EclesioMeloJunior** [comment]
I got the same error here after running `go clean --modcache` 

```
> go clean --modcache
> make gossamer
rm -fr ./bin
cd cmd/gossamer && go build -o ../../bin/gossamer && cd ../..
go: github.com/ChainSafe/go-schnorrkel@v0.0.0-20210127175223-0f934d64ecac: invalid version: unknown revision 0f934d64ecac
make: *** [Makefile:125: gossamer] Error 1
```
