### ISSUE TITLE
Benchmark and compare other Go based key value store

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1563]
## Issue summary

- Currently, we use [`chaindb`](https://github.com/ChainSafe/chaindb) which uses [`badger`](https://github.com/dgraph-io/badger) internally.
- [`chaindb`](https://github.com/ChainSafe/chaindb) should implement multiple databases internally.
- [`pebble`](https://github.com/cockroachdb/pebble) is another Go-based key-value store, which is tested for production systems and has better read and write speed than [`badger`](https://github.com/dgraph-io/badger)
- We should benchmark `pebble`

## Other information and links

- https://github.com/cockroachdb/pebble
- https://github.com/ChainSafe/chaindb
- https://github.com/dgraph-io/badger

**Comment by dutterbutter** [comment]
May also be worth looking into: 👇
https://github.com/tendermint/tm-db
