### ISSUE TITLE
`dumpconfig` Doesn't Respect CLI Flags

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#157]
## Expected Behavior

CLI flags should be included when running `dumpconfig`.

## Current Behavior

Only the options from the toml file are used.

## Possible Solution
Here `gossamer.setConfig()` (renamed `getConfig()` in #155 ) returns the config from a file or the default config:
https://github.com/ChainSafe/gossamer/blob/952ef791855ec4bf422251e95017217374e5a737/cmd/gossamer/configcmd.go#L165

To resolve this, the config instance configured within `gossamer.makeNode()` should be reused somehow. Additionally, `setConfig()`(`getConfig()`) should be further renamed

## Steps to Reproduce (for bugs)

0. Checkout `development`
1. `make gossamer`
2. `gossamer --datadir "someDir" dumpconfig`

Output:
```
[ServiceConfig]
BootstrapNodes = ["/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ", "/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM"]
Port = 7001
RandSeed = 33

[DbConfig]
Datadir = "chaindata"

```

## Your Environment
* Version used: development
* Commit hash:  952ef79
* Go Version: 1.12
* Operating System and version (include distro if Linux): Ubuntu 18.04
* Link to your project or reproducible gist:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by dutterbutter** [comment]
This will be addressed in upcoming PR with CLI update
