### ISSUE TITLE
polkadot.js UI (api 4.9.x): cannot show block details for blocks with extrinsics 

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1578]
## Describe the bug

- 

## Expected Behavior

-

## Current Behavior

- on the UI w/ api version 4.9.x, we are unable to see the block details for blocks with extrinsics due to some decoding error (other blocks w/o extrinsics are fine, earlier api versions are fine) 
- https://files.slack.com/files-pri/T4Q9KCBC4-F021L8TFUN7/screenshot_2021-05-11_14-00-20.png
- probably some SCALE encoding issue with the extrinsics in the block

[](url)

**Comment by timwu20** [comment]
Let's make sure we cover this in #2027
