### ISSUE TITLE
Create a seperate folder for db.

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1588]
## Issue summary

- Currently, DB is stored in the base path. It will be nice if we store it in a separate folder.
<img width="1163" alt="Screenshot 2021-05-14 at 6 48 39 PM" src="https://user-images.githubusercontent.com/5843604/118276441-47cc1680-b4e5-11eb-894d-1389d1adab24.png">

## Other information and links

-

**Comment by EclesioMeloJunior** [comment]
@arijitAD you mean in a separate folder inside or outside the basepath?

**Comment by arijitAD** [comment]
Inside the base path.
