### ISSUE TITLE
Implement sr25519 signature algorithm and ext_sr25519_verify

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#171]
Info: https://wiki.polkadot.network/en/latest/polkadot/learn/cryptography/
https://en.wikipedia.org/wiki/Schnorr_signature

Polkadot uses sr25519 as its default signing scheme, which is custom to substrate and has only been implemented in rust.  The scheme is Schnorr signatures over curve25519.

**Comment by noot** [comment]
@noot might need to fork https://godoc.org/golang.org/x/crypto/curve25519 doesn't export add and sub funcs we need

**Comment by noot** [comment]
we are gonna use cgo to import this https://github.com/Warchant/sr25519-crust
these are c bindings for the original rust implementation https://github.com/w3f/schnorrkel

**Comment by zmanian** [comment]
We have implementations of 

Merlin and Ristretto255 in native golang

https://github.com/gtank/merlin

https://github.com/gtank/ristretto255

This make implementing sr25519 fairly trivial
