### ISSUE TITLE
Seperate out CI test in different workflows.

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1727]
## Issue summary

- We need to separate out the CI test in different workflows so we can individually retrigger them incase of failures.
- As @EclesioMeloJunior mentioned we can re-run a specific workflow, I dug around and found this [document](https://docs.github.com/en/actions/managing-workflow-runs/re-running-a-workflow) which explains it.
- We can rerun a workflow using GUI or CLI.

## Run workflow using `gh` CLI:
<img width="1214" alt="Screenshot 2021-08-13 at 11 07 57 AM" src="https://user-images.githubusercontent.com/5843604/129311682-6aa369f8-e084-4003-a41a-533e35081437.png">
1. Get the run id of the workflow.  
<img width="1232" alt="Screenshot 2021-08-13 at 11 08 53 AM" src="https://user-images.githubusercontent.com/5843604/129311699-26fcfd9d-c1e4-4018-a73c-3b08d5beac79.png">
2. Re run the job from CLI  
```
gh run rerun 1125244951
```

3. Just the specific workflow runs 
<img width="1341" alt="Screenshot 2021-08-13 at 11 10 18 AM" src="https://user-images.githubusercontent.com/5843604/129311786-66987ed5-f359-4d4b-b6b6-17b49758d422.png">

## Other information and links

- https://docs.github.com/en/actions/managing-workflow-runs/re-running-a-workflow

**Comment by dutterbutter** [comment]
@arijitAD are you suggesting we separate the docker tests from the unit tests or all test cases separated individually?

**Comment by arijitAD** [comment]
> @arijitAD are you suggesting we separate the docker tests from the unit tests or all test cases separated individually?

@dutterbutter Yes, All the tests which are currently inside the workflow file `test.yml` need to be separated out individually so we can retrigger them independently.
