### ISSUE TITLE
Implement `state_call` RPC call

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#1765]
## Task summary

- Implement `state_call` RPC call

## Specification reference

- [Spec reference](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1113-state_call)

## Other information and links

- N/A

**Comment by ramiroJCB** [comment]
Hello @EclesioMeloJunior , hey I wanted to do this issue but traversing throught the issues I found [this](https://github.com/ChainSafe/gossamer/pull/3228)  addressing this issue already. Could  we update this one to close and update this  [issue](https://github.com/ChainSafe/gossamer/issues/3735) that is related.

**Comment by EclesioMeloJunior** [comment]
@ramiroJCB thanks!
