### ISSUE TITLE
Kusama Node not syncing shortly after launch

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#1770]
## Issue summary

- When syncing to the Kusama network block syncing is paused based on the metrics and logs.  The following log message occurs before ultimately failing.  I've tried it a number of times and it's not block specific.
```
EROR[08-25|15:34:51] failed to handle block                   pkg=sync number=8939114 error="failed to find root key=0xb292a2a28d5a740f01852adc01227c6b91ca276446abec6a01c933b9b049717a: Key not found" caller=syncer.go:265
WARN[08-25|15:34:51] failed to handle block data              pkg=network failed on block=4353 error="failed to find root key=0xb292a2a28d5a740f01852adc01227c6b91ca276446abec6a01c933b9b049717a: Key not found" caller=sync.go:815
```
- Noticed this on the staging nodes for both Kusama and Polkadot.  The block sync number just stalls and the node continues to run, but never updates block sync progress.

- Run `gossamer --chain=kusama init` then `gossamer --chain=kusama --publish-metrics` and observe logs and `service_blocks_sync` metric.

## Other information and links

-

**Comment by noot** [comment]
I think the syncing refactor should address this (#1659) if not, we can revisit this after
