### ISSUE TITLE
make `SendBlockReqestByHash` synchronous when check justification

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#1771]
## Task summary

- The function `handleNeighbourMessage` at `lib/grandpa/message_handler.go` checks the justification and if there is some error and the error is a `blocktree.ErrStartNodeNotFound` error we must exec the `h.grandpa.network.SendBlockReqestByHash(msg.Vote.Hash)` call synchronously 

## Specification reference

- N/A

## Other information and links

- N/A

**Comment by noot** [comment]
going to close this for now and this won't be needed after the sync refactor, after it's done all instances of sending block requests should only be done by the sync package
