### ISSUE TITLE
`ext_storage_clear_prefix_version_2`, need to update `trie.ClearPrefix` to use `limit` param

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#1792]

**Comment by edwardmack** [comment]
ext_storage_clear_prefix_version_2 not found in host specification at [https://research.web3.foundation/en/latest/polkadot/specifications/host.html](https://research.web3.foundation/en/latest/polkadot/specifications/host.html)

**Comment by noot** [comment]
depends on #1717
