### ISSUE TITLE
feature: Add SCALE custom type functionality for Result, VaryingDataType, and VaryingDataTypeSlice 

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#1819]
## Task summary

- SCALE requires the destination data structure to be known before decoding.  This isn't a problem when we deal with initialised `Result`, `VaryingDataType` and `VaryingDataTypeSlice` instances.  
- The issue is when `Result`, `VaryingDataType` and `VaryingDataTypeSlice` are used as attributes in structs.  The zero case for the `Result`, `VaryingDataType` and `VaryingDataTypeSlice` have not been intialized with their associated value types, which causes a decode error.
- The proposed solution is to allow for shadowing (custom types) of `Result`, `VaryingDataType` and `VaryingDataTypeSlice`, and to utilise the constructor pattern (ex. `func NewMyResult() *NewResult`) which will be called by the scale decoding process to initialise these special types.  In the event that there is no constructor defined in the package we could throw a friendly error to notify the developer.

## Specification reference

- 

## Other information and links

- https://github.com/ChainSafe/gossamer/pull/1548

**Comment by danforbes** [comment]
Is this a place where we could be able to make use of generics?
