### ISSUE TITLE
ext_twox_128 runtime function

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#182]
only existing library is in c, we will need cgo for this

https://github.com/Cyan4973/xxHash

**Comment by edwardmack** [comment]
- created branch ed/ext_twox_128_runtime
- started implementing ext_twox_128 using https://github.com/OneOfOne/xxhash
  - They say it's faster than cGo for all inputs
  - Apache2, is it ok for us to use this? 
- Spec says it should output a 16-byte byte array, but when I concatenate the results I get a byte array with 36 elements.  I think I'm missing something basic in my understanding.  Let's review.

**Comment by edwardmack** [comment]
I figured out why I was getting the wrong results, started calling the correct method and I'm getting expected results!  

The code may be a little ugly (please comment), but it's working so I'm doing a PR so you can review/discuss/comment.
