### ISSUE TITLE
Implement `aura.pre_sealed_block` Telemetry Interface

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#1843]
I don't think it's actually possible for us to implement this since we have not implemented Aura block production.

**Comment by kishansagathiya** [comment]
There are no references of this message in substrate codebase or issues. This message is not being sent by substrate, chances are that this was being sent, but is removed now.

**Comment by timwu20** [comment]
What need to implement Aura (PoA consensus) for us to send this telemetry message.
