### ISSUE TITLE
dot/network: update `BlockRequestMessage.FromBlock(Number)` to be of type uint32

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1854]
## Task summary

- the `BlockRequestMessage.FromBlock/StartingBlock` field is a variadic type, either a uint representing a block number or a hash representing a block hash
- the uint is currently uint64, but should be updated to uint32, as this is the type used to represent block numbers in substrate

**Comment by qdm12** [comment]
This will be done in #1785 as a side effect.
