### ISSUE TITLE
dot/state: fix `Rewind` by adding lookup for finalized block -> (round, setID) where block was finalized

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1859]
## Task summary

- `Rewind` is currently broken as it fails to set what the current grandpa round and setID are after rewinding
- requires some lookup for finalized block -> (round, setID) where block was finalized
- implement and fix this

**Comment by timwu20** [comment]
@kishansagathiya are you working on this?

**Comment by kishansagathiya** [comment]
@timwu20 no, un-assigning

**Comment by jimjbrettj** [comment]
stale issue
