### ISSUE TITLE
dot/sync: update `getTarget` to use bell curve average of peer heads

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1861]
## Task summary

- currently the `getTarget` function (which returns the "target" block number we wish to sync to) takes the average of our peer's reported highest blocks
- however it should return the bell ciurved average (discard any outliers from the set over some standard deviation), as this target may be skewed by some malicious peer that reports some very high

**Comment by zjhuber** [comment]
Hi, where can I find expected values for the peer's reported highest blocks? Or what is realistically the range we want a threshold where it is very high like you mentioned?

**Comment by noot** [comment]
@zjhuber hey, the peer's reported highest blocks are stored in the `cs.peerState`, you can iterate through it and access the `peerState.number` field which is their reported highest block. you can look at the current `getTarget` function for inspiration :)
