### ISSUE TITLE
lib/genesis: determine type/encoding of `phragmenElection.Members`

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1866]
## Task summary

- currently the `phragmenElection.Members` is of type `[][]interface{}`
- need to determine the correct type for this

@arijitAD can I get more info on this?

**Comment by axaysagathiya** [comment]
Closing this issue as the phragmenElection is not present in the [westend-local-spec.json](https://github.com/ChainSafe/gossamer/blob/development/chain/westend-local/westend-local-spec.json).
