### ISSUE TITLE
Define API for WASM interpreters

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#187]
It would be nice to be able to switch out WASM interpreters if we like, eg. from `Life` to `wasmer`. However,  the interfaces for the VMs are quite different.

One of the main challenges is going to be creating a standard interface for each imported/exported functions. Perhaps this could be done be writing generic calls (eg. `func ext_blake2_256([]byte) []byte`) which can then be inserted into the logic required for the specific interpreter implementation. 

Memory might also be abstracted with an interface such as:
` Get(uint32 location, uint32 length) => []byte`

**Comment by noot** [comment]
shall we close this for now?
