### ISSUE TITLE
dot/state, dot/digest: move `NextGrandpaAuthorityChange` functionality to `state.GrandpaState`

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1871]
## Task summary

- currently the next grandpa authority (set) change is stored in memory in the `digest.Handler`
- however this should be moved to the `state.GrandpaState` and stored in the database, as it needs to be known if the node shuts down unexpectedly before the change is enacted

**Comment by EclesioMeloJunior** [comment]
Addressed in PR: #2519
