### ISSUE TITLE
Check areas to add peer reputation

### ISSUE THREAD

**Issue by arijitAD** [ChainSafe/gossamer#1887]
## Issue summary

-  Check areas to add peer reputation

## Other information and links

- https://github.com/ChainSafe/gossamer/pull/1791#discussion_r725987714

**Comment by timwu20** [comment]
@arijitAD can you provide a little more context?

**Comment by arijitAD** [comment]
I added peer scoring in major places similar to Substrate. But I didn't explore the entire substrate code to look for all possible areas where peer scoring was used. The task is to compare our peer scoring with substrate and see if we missed out somewhere.

**Comment by timwu20** [comment]
Protobuf file is missing `StateRequest`, `StateResponse` and `StateEntry` message types.  This was added into substrate via this [PR](https://github.com/paritytech/substrate/pull/8884/files) Implementation of "fast sync" and the handling these message types is not implemented.  `BAD_MESSAGE` is reported if `StateResponse` fails to decode ([line](https://github.com/paritytech/substrate/blob/master/client/network/src/protocol.rs#L1476)).  

Added `GenesisMismatch` type to match substrate `GENESIS_MISMATCH` where change is min int32 (essentially banning) that node.  Added report peer to gossamer code, PR otw.

substrate `rep::REFUSED` is not implemented in gossamer.  Need to investigate how to detect if a peer is refusing our connections.

substrate `rep::ANY_TRANSACTION` and `rep::ANY_TRANSACTION_REFUND` is not implemented.
