### ISSUE TITLE
create CLI flags for package log levels

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1893]
## Task summary

- currently the package log levels can only be set via the config file
- there should also be CLI flags for each package's log level
- `--log-<package-name>=level` look at substrate and match

**Comment by qdm12** [comment]
Waiting on https://github.com/paritytech/substrate/issues/8025#issuecomment-956293219 to know what the possible target names are. For now I set them to:

```
log-core
log-sync
log-network
log-rpc
log-state
log-runtime
log-blockproducer
log-finalitygadget
```
