### ISSUE TITLE
ext_storage_changes_root [Runtime Imported Function]

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#190]
There is a stub for this imported function in runtime/wasm.go. 

It is yet to be specced, see section E.1.9 in the spec (https://github.com/w3f/polkadot-re-spec/blob/master/polkadot_re_spec.pdf)

**Comment by noot** [comment]
I don't think this exists in v0.4 or v0.5, so I'm going to close this for now

**Comment by noot** [comment]
duplicate of #905
