### ISSUE TITLE
Implement unit test for `ext_offchain_timestamp_version_1` and `ext_offchain_sleep_until_version_1`

### ISSUE THREAD

**Issue by omar391** [ChainSafe/gossamer#1902]
## Describe the bug

Relates to #1795 and #1508

- Currently 2 test cases  for `ext_offchain_timestamp_version_1` and `ext_offchain_sleep_until_version_1` are failing.

### Summary: 
we have defined these 2 methods on the GOlang side. From the unit test, we instantiate the WASM runtime file (compiled from the RUST code) and call the GO-ed version of the method using the exported glue/linking method in the WASM binary named: `rtm_ext_offchain_timestamp_version_1` and `rtm_ext_offchain_sleep_until_version_1`.

- Issue for: `ext_offchain_timestamp_version_1`
-- Current: Calling `inst.Exec("rtm_ext_offchain_timestamp_version_1", nil)` from the unit test return empty byte int64 value.
-- Expected: It should correctly get the int64 version of `time.Now().Unix()` passed from GO side.

- Issue for: `ext_offchain_sleep_until_version_1`
-- Current: It somehow can't find the glue `rtm_ext_offchain_sleep_until_version_1` in the WASM instance. I have checked the existing rust implementation which has the relevant definition of this method. So WASM should have this method.
-- Expected: WASM should be able to call the GO side of the function and sleep till the expected timestamp.
 
 

## Specification

- go version: 1.17
- gossamer version: `development`
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by arijitAD** [comment]
@omar391  Can you share more debug info why this is not possible? `ext_offchain_timestamp_version_1 `
Also, share the error for `rtm_ext_offchain_sleep_until_version_1 `

**Comment by omar391** [comment]
@arijitAD The issues were related to using `Vec<u8>` instead of `u64` and using pointer references instead of value on the rust side.

**Comment by arijitAD** [comment]
@omar391 You can look at other implemented functions. Doesn't look like a Rust/Golang issue to me.

**Comment by omar391** [comment]
PR https://github.com/ChainSafe/gossamer/pull/1806 is merged. So it's fixed and closed!
