### ISSUE TITLE
Remove uint128.go from lib/common Package

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#1939]

**Comment by kishansagathiya** [comment]
Can you provide more info here?
uint128.go is being used. I think we want to replace with something else. Is that the case? Is it decided, what it should be replaced with, or is it to be researched?

**Comment by timwu20** [comment]
I moved this to `pkg/scale`, we just need to update the imports and adjust the syntax.

**Comment by kishansagathiya** [comment]
Closed in https://github.com/ChainSafe/gossamer/pull/2074
