### ISSUE TITLE
chore(tests): migrate from `github.com/vektra/mockery` to `github.com/golang/mock`

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#1954]
## Issue summary

We are now migrating slowly to use gomock which is maintainted by some of the golang team.

Its features are more complete, it is more popular and it has a tighter integration with the Go language.
~This would also allow us to use to use Go 1.18 without being blocked by mockery not supporting it as well.~ mockery v2.10.0 supports go 1.18

Old issue description:

> Mockery is highly untyped and it's hard to detect problems at compile time / in IDE without running (potentially long running) tests. Overall, golang/mock is a better solution as far as I know, having used both extensively

This issue should:

- replace/remove all mockery code with gomock code
- Remove mockery from the documentation in the contributing document
- Remove mockery from the `mocks checks` CI workflow

**Comment by noot** [comment]
@qdm12  is this done?

**Comment by qdm12** [comment]
@noot No, although mockery v2.10.0 supports Go 1.18 so it's less of a pressing issue.
Don't get me wrong though, I would love to get this done, but there are other more pressing issues I think :wink:
