### ISSUE TITLE
Block Tree

### ISSUE THREAD

**Issue by steviezhang** [ChainSafe/gossamer#196]
Basic Block Tree structure and functionality

Longest-Path(BT)
- returns a path graph of BT which is the longest among all paths in BT

Deepest-Leaf(BT)
- returns the head of Longest-Path(BT) chain.

Leaves(BT)
- returns all hashes of blocks that are leaves on the current BT 

Children(H, BT)
- returns all children of block with Hash H on the current BT

1. Import-Block(B, BT). Helpers:
    - Hash-Exists(H, BT)
        - Checks to make sure a hash belongs to a block in current BT
    - Is-Descended-From(H, H2, BT)
        - Checks if hash is descendant of other block hash.

2. pre and post order traversal (BT)

3. when finalizing a block, "pruning" competing branches. Consider:
    - if finalized block is already finalized
    - if finalized block is ancestor of previously finalized block
    - if finalized block is earlier than previously finalized block and is not ancestor of that block
    - if finalized block descendant of previously finalized block
        - immediate descendant
        - non-immediate descendant with some nonfinalized ancestors
    - if finalized block does not exist in tree

**Comment by amerameen** [comment]
Still need to write tests & implement 'finalize block'
