### ISSUE TITLE
Setup https://github.com/profefe/profefe

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#1970]
In order to collect periodically pprof samples and be able to check changes over time (e.g. after a crash).

- [ ] Setup profefe in our cluster/ECS
- [ ] Use the agent library https://pkg.go.dev/github.com/profefe/profefe/agent to send pprof data periodically
- [ ] Document how to easily compare pprof stored in profefe

**Comment by timwu20** [comment]
Since infra is taking over our profiling, I'm going to close this.
