### ISSUE TITLE
Setup metrics monitoring for Gossamer devnet with Prometheus and Grafana

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#1971]
We already have exported Prometheus metrics (the same as substrate) in Gossamer.

Tasks to do:

- [ ] Setup Prometheus on our cluster/ECS
  - [ ] Configure it to scrap all Gossamer nodes
- [ ] Setup Grafana on our cluster/ECS
  - [ ] Configure it to fetch data from the Prometheus instance
- [ ] Either:
  - Find an existing Grafana dashboard JSON for substrate and import it
  - Setup our own dashboard, and commit it to your repository
- [ ] Document this in the repository somewhere

**Comment by noot** [comment]
@qdm12 I believe we decided not to use grafana, as we already have datadog set up

**Comment by qdm12** [comment]
Do we have Prometheus metrics being sent to datadog already? We may want to modify this issue :thinking:

**Comment by noot** [comment]
doing to close this for now as we have a datadog setup
