### ISSUE TITLE
Add ping or health check endpoint

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#1972]
This can be in the form of an HTTP server. It would be used to detect when/why a node becomes unresponsive. It could later be used by users for Kubernetes/Docker health checks for example.

- [ ] Add independent HTTP server with handler returning `200`
- [ ] Improve healthcheck to check things within the program (has anything stalled etc.)?
- [ ] Add healthcheck client mode to Gossamer (eventually, otherwise use `curl`).
- [ ] Add `HEALTHCHECK` instruction in Dockerfile

**Comment by timwu20** [comment]
Don't think we need this given that infra is taking this over.
