### ISSUE TITLE
Improve linting to detect potential memory problems

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#1974]
- [x] Check `// nolint` comments
  - Check it makes sense to ignore
  - Replace each with `//nolint:<linter>`
  - Add `nolintlint` linter so outdated `//nolint` comments are detected
- [x] Add linters `nilerr`, `nilnil` and `exportloopref`

**Comment by noot** [comment]
@qdm12 is this done?

**Comment by qdm12** [comment]
First part is done in #2047, I just did the second part in #2072

**Comment by qdm12** [comment]
Done in #2047 and #2072
