### ISSUE TITLE
[Research] Trie DB

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#2]
* see [pre spec](https://github.com/w3f/polkadot-re-spec/blob/master/polkadot_re_spec.pdf) section 5
* implement encoding of keys in tree
* implement base-16 modified Merkle Patricia tree (ie. Trie)
* what db are we going to use for storage?

**Comment by ansermino** [comment]
Some possible DBs to use:
BoltDB - https://github.com/boltdb/bolt
BadgerDB - https://github.com/dgraph-io/badger

Hard to say which would benefit use more. BoltDB is used by Prysmatic for their Eth 2.0 client, and Badger comes recommended by @priom (iirc)

**Comment by priom** [comment]
This looks to be pretty good; https://github.com/etcd-io/bbolt

We could start by doing some tests

**Comment by priom** [comment]
Test
