### ISSUE TITLE
Trie tests occasionally fail on CI

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#201]
## Expected Behavior
Trie tests should not fail

## Current Behavior
It seems that sometimes the tests fail and `TestFailingTests` gets run, which is supposed to run the same test case as the test that failed in `TestPutAndGet`.  However, it doesn't run the same test case.

## Possible Solution
There is a bug in TestFailingTests. Maybe it is not running the correct test cases.

## Steps to Reproduce (for bugs)
`go test ./trie/ -v`

It will need to be run multiple times until the fail happens.  Since the tests are random, we don't really know what case causes it to fail, or why it appears that the wrong test case gets run.

**Comment by ansermino** [comment]
https://travis-ci.com/ChainSafe/gossamer/builds/118839226

**Comment by dziabko** [comment]
https://travis-ci.com/ChainSafe/gossamer/builds/127910064

**Comment by ansermino** [comment]
https://travis-ci.com/ChainSafe/gossamer/jobs/241819149

**Comment by ansermino** [comment]
https://travis-ci.com/ChainSafe/gossamer/jobs/243543232

**Comment by ansermino** [comment]
https://travis-ci.com/ChainSafe/gossamer/jobs/250385405

**Comment by ansermino** [comment]
This continues to be an issue, seems there must be an issue here.

**Comment by ansermino** [comment]
Would be great to get the output file from the failing tests
