### ISSUE TITLE
Transaction Load-Testing for Gossamer Devnet

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2011]
## Task summary

- Research and document a strategy for load-testing Gossamer's ability to handle large volumes of transactions (spam)
- Implement the above strategy
- Document the findings

## Specification reference

- N/A

## Other information and links

- @ETeissonniere from [Nodle](https://github.com/NodleCode) was gracious enough to open-source [a load-testing utility](https://github.com/NodleCode/chain-loadtest) used by his team.

**Comment by arijitAD** [comment]
I created 1000 extrinsics using the tool but it seems to generate invalid extrinsics. 

![Invalid Extrinsics](https://user-images.githubusercontent.com/5843604/143030532-e7641186-6654-4046-a9f6-902fccc36795.png)

**Comment by danforbes** [comment]
You probably need to update the parameters used to instantiate the API https://github.com/NodleCode/chain-loadtest/blob/main/src/api.ts

**Comment by timwu20** [comment]
@arijitAD is there a PR for this?

**Comment by arijitAD** [comment]
There is no PR. The task was to observe if we are able to handle a high amount of txns. It seems to work.
I have added the load testing logs and the test script here
https://github.com/ChainSafe/gossamer/commit/782fb1731acf2b9169ad14fa5eef9bf4e154f19d#diff-5076a1f78c8a695913cc20ec45b8751f2fdfad72bc68acbbe7b22761a0d1f0e3
