### ISSUE TITLE
Investigate Interoperability with Polkadot-JS API v6.8.1

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2028]
Consider using the Polkadot-JS API [HTML test bundle](https://github.com/polkadot-js/api/blob/v6.8.1/test-bundle.html) or [API tests](https://github.com/polkadot-js/api/blob/v6.8.1/packages/api/test/api.spec.ts)

**Comment by edwardmack** [comment]
Testing with current API (v9.10.1) via polkadot.js.org/apps are working.
