### ISSUE TITLE
Implement Block & Extrinsics DB

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#203]
We need data stores for blocks and extrinsics, presumably separate instances of BadgerDb.

We will want to store Blocks (a type defined elsewhere): 
```
type Block struct {
    ...
    extrinsics []common.Hash
}
```

Then in the extrinsics DB we will store each extrinsic by their hash, with the extrinsic type (defined elsewhere) taking a form of:
```
type Extrinsic []byte
```

**Comment by amerameen** [comment]
@dutterbutter did #246 close this?

**Comment by dutterbutter** [comment]
From the previous PR yes.
