### ISSUE TITLE
dot/network: remove race conditions and parellelize tests

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#2044]
## Task summary

- there are currently race conditions in the network package as can be seen with `go test -race ./dot/network/...`
- fix these race conditions and update tests to run in parallel
- tests currently start up libp2p hosts, so there are conflicts between ports/basepaths between hosts. this will need to be resolved for tests to run in parallel

**Comment by timwu20** [comment]
closing this since we can't even run the tests in dot/network tests in race mode.  We are now able to run the tests in parallel.
