### ISSUE TITLE
Add support for NAT Traversal

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#2071]
## Task summary

Few days ago me and @noot were discussing about whether p2p circuit relay should be enabled in gossamer and what are the benefits and possible risks of it. Creating this issue to get clarity on a 

- At the moment, Peers that are behind NAT cannot connect to gossamer network.
- Is it important for us to take care of NAT traversal? Are most of our users (or users of polkadot) likely to be behind NAT?
- If you do some research on various NAT Traversal protocols offered by libp2p like AutoNAT, p2p circuit relay, STUN, UPnP, etc. See which of these would make sense for us to support.
- Check if substrate/polkadot is using any of these

## Specification reference

- 

## Other information and links

-

**Comment by danforbes** [comment]
Related Substrate Issue https://github.com/paritytech/substrate/issues/2772

**Comment by timwu20** [comment]
Given that substrate doesn't support this I don't think we need to.  Closing this.
