### ISSUE TITLE
Accept interfaces, return structs

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#2088]
## Task summary

- I have been returning `Message` interface instead of individual structs. I like the idea that all messages are just the same and not having to export a whole bunch of structs. But there is a lot of literature for returning structs. This is mostly a reminder to me to read those and change all instances where I have returned `Message`, if needed. 

## Specification reference

- https://github.com/ChainSafe/gossamer/pull/2043#discussion_r757563996

## Other information and links

-

**Comment by qdm12** [comment]
Maybe you can add linter `ireturn` and do it across the entire codebase :thinking:
