### ISSUE TITLE
Update Makefile and CircleCI Config

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#21]
## Expected Behavior

CI commands should be available inside Makefile. Similarly CI config should use Makefile.

## Current Behavior

Linters don't match.

## Possible Solution

Update Makefile to use CI commands, then update CI to use Makefile

## Steps to Reproduce (for bugs)

N/A

## Context

N/A

## Your Environment

N/A

**Comment by dutterbutter** [comment]
@GregTheGreek this relates to the CI changes we had discussed

**Comment by GregTheGreek** [comment]
I'll open a pr tomorrow to address this

**Comment by dutterbutter** [comment]
ChainSafeSystems/gossamer#78

**Comment by ansermino** [comment]
Just to clarify, this is still an open task. Travis config does not use makefile

**Comment by GregTheGreek** [comment]
Perhaps update the title

**Comment by GregTheGreek** [comment]
I can also fix the make file tomorrow
