### ISSUE TITLE
Implement VRF

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#210]
See [#247      (ChainSafe/gossamer#194)](https://zube.io/chainsafe-2/gossamer/c/247)  & [ChainSafe/gossamer#207 (ChainSafe/gossamer#171)](https://zube.io/chainsafe-2/gossamer/c/207)

**Comment by noot** [comment]
compile schnorrkel to a wasm blob then attempt to call sr25519 and vrf functions from that
