### ISSUE TITLE
Investigate and Fix Data Races

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2147]
## Issue summary

- Use [Go tooling for race detection](https://go.dev/doc/articles/race_detector) to detect data races in Gossamer code, create a plan to fix data races, and fix the data races according to the plan.

## Other information and links

- The following packages have been identified as having data races by running unit tests with race detection turned on (there might be more depending on `MODE` environment variable):
  - `dot/digest`
  - `dot/network`
  - `dot/peerset`
  - `dot/rpc/subscription`
  - `dot/sync`
  - `dot/telemetry`
  - `lib/grandpa`

**Comment by jimjbrettj** [comment]
stale issue
