### ISSUE TITLE
Investigate v0.9 extrinsic tests that generate own extrinsics and document plan of action

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#2156]
Currently, there are tests that use extrinsic generated by itself, so we need to ensure the generated extrinsic is compatible and works with the runtime at version 9. 

The tests are:
- TestAuthorModule_SubmitExtrinsic
- TestAuthorModule_SubmitExtrinsic_invalid
- TestAuthorModule_SubmitExtrinsic_InQueue
- TestBuildBlock_failing

**Comment by timwu20** [comment]
@EclesioMeloJunior can you add a description to this.

**Comment by EclesioMeloJunior** [comment]
@timwu20 I've investigated and created a simple plan of action to ensure that the extrinsic used in the tests functions works with runtime v0.9:

- The tests `TestAuthorModule_SubmitExtrinsic`, `TestAuthorModule_SubmitExtrinsic_invalid` and `TestAuthorModule_SubmitExtrinsic_InQueue` are on author RPC module integration test suite, so I can ensure the test execution using the version v9 in the PR https://github.com/ChainSafe/gossamer/pull/2091
- The test `TestBuildBlock_failing` is currently being skipped, so I will suggest opening an issue to remove the skip and ensure the execution using the v9

fyi @danforbes

**Comment by danforbes** [comment]
This work has been completed.
