### ISSUE TITLE
Investigate How to Test GRANDPA Catch-Up

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2157]

**Comment by noot** [comment]
for interop, the basic steps are:
1. run substrate polkadot node (and wait for it to sync)
2. run gossamer node, pretend that it's an authority (ie. set `Roles = 4` in `NeighbourMessage`)
3. send catch-up request from gossamer node to substrate node (on outbound grandpa stream)
4. check if we receive a catch-up response from the substrate node on an inbound grandpa stream

**Comment by timwu20** [comment]
#1531
