### ISSUE TITLE
Fix Flaky Tests in `TestBlockTree_GetHashByNumber`

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2158]
[Logs 1](https://github.com/ChainSafe/gossamer/runs/3977236105?check_suite_focus=true)
[Logs 2](https://github.com/ChainSafe/gossamer/runs/3979841722?check_suite_focus=true)
[Logs 3](https://github.com/ChainSafe/gossamer/runs/4002865116?check_suite_focus=true)

**Comment by noot** [comment]
I believe this was fixed by @EclesioMeloJunior

**Comment by danforbes** [comment]
@EclesioMeloJunior if so please close this Issue with a comment that references the relevant commit 🙏🏻

**Comment by EclesioMeloJunior** [comment]
Yes, this was addressed here -> https://github.com/ChainSafe/gossamer/commit/43d68e36e98f1f9d5cd83962ba5a4cbfee7270ab
