### ISSUE TITLE
transaction testing investigation

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#2230]
Determine plan of action for docker container running transaction testing within local and ECS gossamer devnets. 

### Requirements
- Integrate datadog metrics for health status
- Run transactions across multiple nodes (alice, bob, charlie, dave)
- Ensure that transactions are successful
- Ensure that blocks are finalised (tbd)
- Utilize polkadotJS or find go alternative to initiate RPC calls
- load testing? 
- Configurable
- Query state through HTTP endpoint?

**Comment by jimjbrettj** [comment]
possible reference resource https://github.com/NodleCode/chain-loadtest

**Comment by jimjbrettj** [comment]
Overview of what this task will look like/entail:
- building a dockerfile to run a script which interacts with devnet
- publish metrics to datadog via prometheus (can scrape endpoint)
- Send both valid and valid transactions
    - Run indefinitly, sending txns and verifying them and the state
    - configure txns/sec and maybe other things such as % of invalid txns
    
The phases will go as follows:
- build dockerfile and simple test script to interact with the devnet
- come up with scheme to have on infinitly running program which sends txns and verifies them and the state, and implement this into the script
- make the script configurable, publish metrics, and any other things we need to tie this all together

Of course, this is an estimate at how this will unfold and can be altered as needed. If anyone has any questions or comments please comment or reach out to me.
