### ISSUE TITLE
update `Service` interface to allow `Start()` to take or return an error channel

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#2235]
## Task summary

 - currently, if a service such as BABE or GRANDPA encounters an error and stops running its internal algorithm, the higher-level service orchestrator is unaware of this, and the goroutine will fail (basically) silently, stalling block production or finality
 - service should either take/return an error channel that the service handler can listen on, and either panic or restart the service if it fails

**Comment by jimjbrettj** [comment]
stale issue
