### ISSUE TITLE
dot/state: writing and reading a trie to disk gives a different trie

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2243]
## Issue summary

By adding root hash checks for tries read from database, we obtain a different trie where a leaf gets turned into a branch of two leaves. This was found in `TestGetStorageChildAndGetStorageFromChild` after adding root hash checks (using `trie.MustHash()`) when reading from the database.

**Comment by danforbes** [comment]
Can this be closed since #2360 was merged?

**Comment by noot** [comment]
@danforbes yes I believe so
