### ISSUE TITLE
cross-client devnet: substrate shouldn't drop us as a peer

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#2252]
## Task summary

- on the cross-client devnet, occassionally the substrate node will show 0 peers, but gossamer shows 1 peer still. this is concerning because it seems substrate dropped us, but gossamer thinks it's still connected
- firstly we shouldn't be getting dropped, secondly gossamer should correctly determine if it's been dropped.

**Comment by danforbes** [comment]
It seems to me as if this problem may have merged into the development branch between Jan 20-25, because this problem was not occurring on the 20th and I first noticed it around the 25th.

**Comment by noot** [comment]
#2151 might have helped this, it might have been dropping us due to authoring blocks in an off-by-one slot (#2217)

**Comment by kishansagathiya** [comment]
This seems like the most likely culprit

```
2022-02-10 19:36:46.028 TRACE tokio-runtime-worker peerset: Report 12D3KooWG1EcPoFmHGYDALsTFMqRz8y8KLPxbDrxiswJHQNy7u7z: -1024 to -536872651. Reason: Request refused    
```

```
2022-02-10 19:36:46.028 DEBUG tokio-runtime-worker sync: Request to peer PeerId("12D3KooWG1EcPoFmHGYDALsTFMqRz8y8KLPxbDrxiswJHQNy7u7z") failed: Refused.    
```

**Comment by kishansagathiya** [comment]
I have been trying with polkadot master + substrate master. I am running till my laptop get hot, don't see gossamer peer getting dropped anymore.

**Comment by kishansagathiya** [comment]
After talking to @noot, it seems like this is an intermittent error. Adding logs of both sides [gossamer logs](https://gist.github.com/kishansagathiya/71aa7596aec024f0f4b8e4e792bd0d7f) and [polkadot logs](https://gist.github.com/kishansagathiya/a8ecf32add0eb9840a951d29431d43cd)

**Comment by noot** [comment]
@kishansagathiya I'm seeing this quite soon after starting the 2 nodes, like within the first few blocks. also seeing this log from gossamer:
```
2022-03-03T15:53:46-05:00 CRIT highest rated peer is below bannedThresholdValue	peerset.go:L409	pkg=peerset
``` 

I suspect it's actually gossamer banning substrate. can you continue to look into this?

**Comment by kishansagathiya** [comment]
Just tried to replicate this using polkadot `v0.9.10` a few times. We got disconnected for refusing some request. Not because of 
```
2022-03-03T15:53:46-05:00 CRIT highest rated peer is below bannedThresholdValue	peerset.go:L409	pkg=peerset
```

I did see the above message once when I was using an inappropriate genesis file (like bob-gossamer not being in authorities).
