### ISSUE TITLE
P2P Test fail on CI

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#226]
## Expected Behavior

Tests pass.

## Current Behavior

It seems the p2p test fail on the first CI run.

## Possible Solution

TBD

## Steps to Reproduce (for bugs)

N/A

## Context
https://travis-ci.com/ChainSafe/gossamer/builds/123723287
https://travis-ci.com/ChainSafe/gossamer/builds/123644076

**Comment by noot** [comment]
is this ok now?
