### ISSUE TITLE
Investigate Substrate Fast-Sync and Possible Gossamer Implementation

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2264]
## Issue summary

- Substrate implements a "fast sync" mode, however, it's not clear if this will be superseded by a "warp sync" mode. This Epic is for investigating Substrate **fast sync** in order to determine how important it is for it to be implemented in Gossamer. If implementing fast sync is deemed a priority, this Epic will track its implementation in Gossamer.

## Other information and links

- [Substrate fast sync PR](https://github.com/paritytech/substrate/pull/8884)

**Comment by FlorianFranzen** [comment]
https://spec.polkadot.network/#sect-network-sync

**Comment by P1sar** [comment]
duplicated by WARP sync epic
