### ISSUE TITLE
No BlockResponse received from Alexander testnet upon sending BlockRequest

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#227]
Currently, we are able to connect to Alexander and get status messages. To download blocks, we should be able to send another node a BlockRequest message and receive a BlockResponse. However, we are not receiving any BlockResponses after sending a BlockRequest.

Possible reasons:

-  BlockRequest message is encoded incorrectly
-  BlockResponse is not being delivered for some reason?

Possible routes to debug:

- use rust polkadot or polkadot JS to create a test to encode a BlockRequest message and see if that encoding matches what's in the spec/what we've implemented
- Run an Alexander node locally, try to connect to it through Gossamer and send it a BlockRequest message and see what happens. can run polkadot with `--log sub-libp2p=debug,sync=debug` to see extra logs

other notes:
this is the alexander commit: https://github.com/paritytech/substrate/tree/9de71d51b1d7f8ab3feff69f8d38b07b995b8def
here is the messages at that commit: https://github.com/paritytech/substrate/blob/9de71d51b1d7f8ab3feff69f8d38b07b995b8def/core/network/src/message.rs

see current work on branch elizabeth/p2p-block

**Comment by amerameen** [comment]
@noot is this still an issue?

**Comment by noot** [comment]
@amerameen  yes

**Comment by ryanchristo** [comment]
Closing in favor of #467
