### ISSUE TITLE
load p2p protocolPrefix, bootNodes from genesis

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#228]
it's just a const right now, it should be passed into p2p through a config since different networks will have different prefixes.

solution: add protocolPrefix to config in p2p section, parse that and set it as the service.ProtocolPrefix when starting the new p2p service.

in the future: maybe we will need multiple prefixes. add functionality to allow for an array of supported prefixes

**Comment by ansermino** [comment]
This should probably be part of genesis config
