### ISSUE TITLE
dot/state: move tries older than the last finalized trie to disk

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2321]
## Task summary

Right now we store each block state trie for each finalized block in memory.
We should just have the last finalized trie in memory since it will reference all nodes (even from previous tries) and we don't need the previous tries as far as I know. The older tries should be stored on disk.

To confirm with Elizabeth.

**Comment by noot** [comment]
I think this was closed by @timwu20 ? please reopen if not
