### ISSUE TITLE
trie: store value of nodes on disk

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2323]
## Task summary

If #2321 and #2322 do not solve the memory usage issue, this should be worked on.

For now we keep the value of each node of the trie in memory.
We should instead write the nodes values to disk and fetch it from disk when needed.
This will cause a potential speed performance degradation (to verify), but can be a major cause for extreme memory usage.

- Modify code to store node hash <-> value when creating/modifying a node
- Modify code to delete node hash <-> value when modifying/removing a node
- Modify code to fetch node value using the node hash (kept in memory) when needed
- Memory usage improvement measured and documented
- Speed performance degradation measured and documented

**Comment by qdm12** [comment]
#2340 should remove the need for this, let's hold for now.

**Comment by noot** [comment]
@qdm12 is this still needed? seems like the memory issue is fine now

**Comment by qdm12** [comment]
Ehhh, I still need to finish #2310 to know how many nodes we have in memory. In the long run, the node goes out of memory after a few weeks, so this may be needed. Let's keep this opened until we're sure the trie isn't a cause for memory increasing in the long run.

**Comment by qdm12** [comment]
This is no longer needed, having the whole state trie (and deltas from forks before finalization) does not use much memory (~100MB at the tip). See #1973 for an update on memory usage.
