### ISSUE TITLE
Logger Instance for P2P

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#234]
Create an instance of the logger for the P2P package. This instance should add the context (module info) to all log messages in that package automatically.

**Comment by ansermino** [comment]
`log15` doesn't quite work the way we want it to. I think this will be a bit more involved than anticipated, might even call for using a new logger implementation

**Comment by amerameen** [comment]
Alright, let's discuss

**Comment by amerameen** [comment]
Closing this as we will be taking a new approach to logs in the future,
