### ISSUE TITLE
investigate stalled syncing of polkadot network

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#2344]
## Issue summary

- the current staging setup for the polkadot network is stopping at block ~800k
- does not seem to be fetching required block for future blocks to reference as parent
- investigate and fix in bootstrap syncing

## Other information and links

- #1787

**Comment by noot** [comment]
@timwu20 was this fixed? you said it was because the machine ran out of disk space?

**Comment by timwu20** [comment]
Looks to be due to disk storage, the disk was full on the instance, but the node still continued in a blocked state trying to fetch blocks, but the parent block wasn't found on disk.  I've created an issue (#2442) for halting the node when this happens.
