### ISSUE TITLE
lib/trie: split into subpackages and move to `internal/trie`

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2350]
## Task summary

Current situation: there is a lot of files and code in `lib/trie`, especially in `database.go` and `trie.go` which are 1000+ lines files.

Proposed refactoring: All the code in `lib/trie` should be moved in the `internal/trie` directory so they are not exposed as a Go API to other Go projects for the time being (since it is unstable and the Go API isn't really thought out that much yet).

Proposed steps:

1. Move `child_storage*.go` code in package `internal/trie/child`, by using a 2-commits-rebase-and-merge PR to track file movements
2. ~Move content of `lookup.go` and `proof.go` to `internal/trie/proof`, by using a 2-commits-rebase-and-merge PR to track file movements~ Done in #2604 
3. Split content of `database.go` (and test) in multiple files to `internal/trie/database` by using a usual squash and merge PR
4. Split content of `trie.go`  (and test, as well as remaining files) in multiple files to `internal/trie` by using a usual squash and merge PR

Related to #1527

**Comment by qdm12** [comment]
Following our meeting with Bo from Polymer Labs, they are using the following

- `NewEmptyTrie`
- `.LoadFromProof`
- `.Get`
- `.VerifyProof`
- `Pair`

in github.com/cosmos/ibc-go/v3 so we should keep those exported.

**Comment by dimartiro** [comment]
We are addressing this in #3757 so I'm gonna close this issue in favor of that.
