### ISSUE TITLE
Check for root in EncodeAndHash

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#2357]
## Issue summary

- Looking at the comments and code, trie.Hash() and trie.root.EncodeAndHash() should produce the same hash, but they don't. condition of `len(key) < 32` is not checked in `trie.Hash` ~and it hashes everything~, because in case of root nodes we are supposed to return hash of encoding as hash regardless of length of encoding. This creates mismatching hashes from both functions.

- Right now the logic used in `node.EncodeAndHash() ` is repeating in `trie.Hash`. 
- ~`trie.Hash` should get hash from `trie.RootNode.EncodeAndHash() ` and return it~
- In `node.EncodeAndHash` we should check if this node is root or not. If the node is root we should return blake2b hash of its encoding regardless of length of its encoding.
- And then, trie.Hash should get hash from trie.RootNode.EncodeAndHash() and return it.

**Comment by noot** [comment]
the root node should always be hashed, so I think the functionality of `trie.Hash` is correct

**Comment by kishansagathiya** [comment]
> the root node should always be hashed when getting the trie hash, so I think the functionality of trie.Hash is correct. EncodeAndHash is for nodes that are not necessarily the root so it's not subject to the same rule

Ah, right. My bad!

I feel like we should check for root in `EncodeAndHash` and hash it. That should fix many problems. If we don't do this, we will have to do this separately every time we using EncodeAndHash.

**Comment by kishansagathiya** [comment]
closed in https://github.com/ChainSafe/gossamer/pull/2359
