### ISSUE TITLE
trie: missing trie node types

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2374]
## Task summary

https://github.com/paritytech/substrate/blob/ded44948e2d5a398abcb4e342b0513cb690961bb/primitives/trie/src/node_header.rs#L85-L107

we only implement leaf, branch without value and branch with value types, so it appears some types are missing.

[Source comment](https://github.com/ChainSafe/gossamer/pull/2369/files/eece8455e7d4eff4667b03180039f73e9f1ab6dc#r824822837)

**Comment by noot** [comment]
which types are missing? `HashedValueLeaf` and `HashedValueBranch`?

**Comment by seunlanlege** [comment]
> the gossamer trie doesn't need to be the exact same as the substrate one

any reason for this?

**Comment by danforbes** [comment]
@noot - are you able to provide an answer to Seun's question above?

**Comment by noot** [comment]
@seunlanlege @danforbes  what I meant was that the implementation doesn't need to match in terms of exact types, as long as both implementations match the specification and result in the same merkle value for the same input

**Comment by danforbes** [comment]
That makes sense. I agree that we don't need to use the same naming conventions and internal structures as Substrate; I'm unclear as to whether or not Gossamer's trie implementation is missing certain types of nodes, etc that inform part of the trie's actual specification.

**Comment by noot** [comment]
closing in favour of #2418
