### ISSUE TITLE
GRANDPA Does Not Verify Equivocatory Votes (GSR-03)

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2396]
If a GRANDPA voter has been recorded as an equivocatory voter then their vote will not be verified. [The specifications](https://w3f.github.io/polkadot-spec/develop/sect-finality.html) state that if any of the conditions are not met then a vote is invalid.

• The block hash does not correspond to a valid block.
• The block is not an (eventual) descendant of a previously finalized block.
• The signature is invalid.
• The AuthorityID is not in the authority list for the set.

Refer to the sample function below that can be used to verify these votes and use it to ensure each equivocatory vote is valid for the functions `verifyCommitMessageJustification()`, `verifyPreCommitJustification()` and `VerifyBlockJustification()` otherwise disregard the vote.

```go
func (h *MessageHandler) verifyPreCommitJustification(msg *CatchUpResponse) error {
	auths := make([]AuthData, len(msg.PreCommitJustification))
	for i, pcj := range msg.PreCommitJustification {
		auths[i] = AuthData{AuthorityID: pcj.AuthorityID}
	}
	eqvVoters := getEquivocatoryVoters(auths)
	// verify pre-commit justification
	var count uint64
	for idx := range msg.PreCommitJustification {
		just := &msg.PreCommitJustification[idx]
		if _, ok := eqvVoters[just.AuthorityID]; ok {
			continue
		}
		err := h.verifyJustification(just, msg.Round, msg.SetID, precommit)
		if err != nil {
			continue
		}
		if just.Vote.Hash == msg.Hash && just.Vote.Number == msg.Number {
			count++
		}
	}
	if count+uint64(len(eqvVoters)) < h.grandpa.state.threshold() {
		return ErrMinVotesNotMet
	}
	return nil
}
```

**Comment by kishansagathiya** [comment]
Any vote cast by an equivocatory voter is called equivocatory vote. And equivocatory votes are invalid (https://spec.polkadot.network/develop/sect-finality.html#defn-equivocation). 

So, wouldn't it be appropriate to not check any verifications on equivocatory votes?

**Comment by noot** [comment]
@kishansagathiya no, you need to check the signatures. equivocatory votes are still used as part of the calculation for number of votes for a block (total # of equivocations is used)
