### ISSUE TITLE
Gossamer `build-spec` Action Not Compatible with Polkadot 0.9.17 Genesis Files

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2417]
Gossamer's `build-spec` command will fail when it's used to build a human-readable genesis spec that was generated by a Polkadot v0.9.17 node. Gossamer should be updated to be compatible with Polkadot in this regard.

**Comment by noot** [comment]
also initializing a node with a dev genesis generated by polkadot v0.9.17 will fail (uses build-spec functions internally)

**Comment by timwu20** [comment]
Not necessary anymore.  We removed this command.
