### ISSUE TITLE
Implement storage trie version 1

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#2418]
## Task summary

Current storage trie is version 0, we need to upgrade to version 1 which has an [updated header format](https://spec.polkadot.network/#defn-node-header) which especially adds inlined hashes nodes.

Trie encoding/hashing functions might need to accept a v1 parameter or some other method for versioning the trie encoding

Discussions:

- https://github.com/paritytech/substrate/discussions/11607

Related Gossamer issues:

- #2374
- #2329 (good information in there!)

Related Gossamer PRs:

- #2369  (good information in there too!)
- #2477 (merge in feature branch later)

Related Rust code:

- [**Codec**](https://github.com/paritytech/substrate/blob/345e3b1fcbbb0c479a031c45859d7154e7c4b5f7/primitives/trie/src/trie_codec.rs)
- [**Node header**](https://github.com/paritytech/substrate/blob/345e3b1fcbbb0c479a031c45859d7154e7c4b5f7/primitives/trie/src/node_header.rs#L85)
- Commit for inner hash in trie crate: https://github.com/paritytech/trie/commit/cbc0283ceb014ef29c5a6c6dbe22a66e8a712c48
- Substrate PR for trie upgrade: https://github.com/paritytech/substrate/pull/9732
- [Smoldot PR](https://github.com/smol-dot/smoldot/pull/230/files)

Related documentation:

- [State storage trie structure spec](https://spec.polkadot.network/#sect-state-storage-trie-structure)
- [v1 trie diff](https://github.com/w3f/polkadot-spec/pull/478/files)

Other issues:

- https://github.com/ComposableFi/ibc-go/issues/6

WASM functions to implement:

- [`ext_storage_root_version_2`](https://spec.polkadot.network/#sect-ext-storage-root-version-2)
- [`ext_default_child_storage_root_version_2`](https://spec.polkadot.network/#_version_2_prototype_4)
- [`ext_trie_blake2_256_root_version_2`](https://spec.polkadot.network/#_version_2_prototype_9)
- [`ext_trie_blake2_256_ordered_root_version_2`](https://spec.polkadot.network/#_version_2_prototype_10)
- [`ext_trie_keccak_256_root_version_2`](https://spec.polkadot.network/#_version_2_prototype_11)
- [`ext_trie_keccak_256_ordered_root_version_2`](https://spec.polkadot.network/#_version_2_prototype_12)
- [`ext_trie_blake2_256_verify_proof_version_2`](https://spec.polkadot.network/#_version_2_prototype_13)
- [`ext_trie_keccak_256_verify_proof_version_2`](https://spec.polkadot.network/#_version_2_prototype_14)

Post-v1 things to do:

- https://github.com/ChainSafe/gossamer/pull/2747#discussion_r946246955
- https://github.com/ChainSafe/gossamer/pull/2736/files#r941466934

**Comment by blasrodri** [comment]
Hi! What's the status of this? Is there anything I can do to help out?

**Comment by qdm12** [comment]
Hello there, sorry I didn't notice the comment earlier.
Status is still in progress (actively being worked on since May 2022 pretty much), it's taking a long time since this change impacts the entire codebase and there is a lot of code we had/have that cannot work with the v1 state trie (due to the higher dependency on disk). For example we need to implement #2838 first (which is also work in progress).

You can help out by letting us know what is the problem you are encountering. We checked 2 weeks ago and all runtimes still use `v0` as their state trie (not v1), so my guess is you are using i.e. the proof verification function `ext_trie_blake2_256_verify_proof_version_2` with the version argument set to `1` right? Or is it something else?

Thanks!

**Comment by qdm12** [comment]
I hope this comment will help continue work on this:

https://github.com/ChainSafe/gossamer/pull/2918#issuecomment-1545740847

Also the following PRs are relevant directly to support the v1 trie:

https://github.com/ChainSafe/gossamer/pull/2641
https://github.com/ChainSafe/gossamer/pull/2665

More changes would also be required to support the v1 trie outside the trie package (for the host), notably:

https://github.com/ChainSafe/gossamer/pull/2774
https://github.com/ChainSafe/gossamer/pull/2664
