### ISSUE TITLE
Update Gossamer Testing Runtimes

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#2419]
## Task summary

- currently we are using a modified substrate node runtime from an older version (polkadot v0.9.10) for the dev/gssmr runtimes
- note: only difference between dev and gssmr runtimes is dev has BABE threshold values set to (1,1) instead of (1,4)
- additionally the runtime was modified so there are the same authorities every epoch
- we should create a new testing runtime that is easier to maintain that uses the v0.9.17 host API (ie newest FRAME version)
- for testing, we should have a sudo key (Alice) that can add/remove authorities (ie we do not need staking)
- note that the code will not live in this repo but in some other gossamer-runtime repo as it will be written in rust and compiled to wasm
- make sure to include rust versions used and compilation scripts/steps

**Comment by danforbes** [comment]
@timwu20 Here is the PR you requested https://github.com/ChainSafe/substrate-node-template/pull/1
