### ISSUE TITLE
Incorrect Use of Synchronisation Primitives (GSR-21)

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2423]
The `encodingMu` [reader/writer lock](https://pkg.go.dev/sync#RWMutex) appears intended to synchronise concurrent access to each `leaf` struct’s `encoding` field. This is used incorrectly, potentially allowing for problematic race conditions.

Current functionality appears to not rely on the `encodingMu` for synchronisation. As such, this issue is deemed of _low_ severity.

In `(*leaf).encodeAndHash()`, `l.encoding` is accessed outside of the bounds the lock at line.

Similarly in `hash.go` within `encodeNode()`, the value written to `n.encoding` may no longer be accurate, because it relies on a value prior obtaining the current lock.

Evaluate whether the `encodingMu` lock is required for correct functionality, as well as the `RWMutex` directly contained in the `leaf` and `branch` structs.

If these locking primitives are required, ensure the lock is held whenever `l.encoding` is accessed. Do not expect the value to remain unchanged when a lock is released and quickly re-acquired (e.g. when releasing a read lock to obtain the associated write lock).

When reasonable, perform regular unit and integration testing of concurrent components with the `-race` flag enabled.

**Comment by edwardmack** [comment]
This was addressed in PR #2301
