### ISSUE TITLE
Investigate growing goroutine count and heap usage 

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#2453]
## Issue summary

- Memory usage continues to climb over time.  When syncing polkadot, memory usage reached 12GB at a block height of ~3M.  Based on collected metrics, heap usage and goroutine count grows at the same rate.
- Investigate codebase for blocked goroutines

## Other information and links

-

**Comment by qdm12** [comment]
Goroutine count does not seem to increase (hovers between 500 and 600) anymore, and that number seems reasonable.
I think we can close this in favor of #1973 ?

**Comment by timwu20** [comment]
I think we have fixed our memory leaks at this point in time.
