### ISSUE TITLE
Fix libp2p Dependabot PR

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2489]
Dependabot opened #2488 to upgrade libp2p from v0.9.0 to v0.15.0, but it's broken our builds. The build should be fixed so that we upgrade our libp2p version. If the upgrade doesn't directly relate to patching some vulnerability, or allowing us to participate in a Polkadot network, then this probably isn't very high priority.

**Comment by qdm12** [comment]
Also github.com/libp2p/go-libp2p-discovery needs to be upgraded
