### ISSUE TITLE
Add notifications for failed development branch build on travis

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#250]
Currently, if our weekly development branch builds runs once a week in addition to PRs. If it fails no one will notice. This is not ideal.

Let's configure TravisCI to send 2+ team members and email if the build fails.

**Comment by dutterbutter** [comment]
@amerameen I believe we do get an email notification if the build fails, but we can make it more transparent and obvious if we integrate Travis with a dedicated slack channel. When a build fails, everyone invited in the slack channel will see the notification. It's pretty easy to setup from what I remember.

@noot @ansermino thoughts?
