### ISSUE TITLE
polkadot.js/api function api.rpc.system.networkState returns no data

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#2532]
## Describe the bug

- When making the following call using polkadot/api version 8.3.1 and gossamer node with runtime gossamer version 0.0.19:
```
const networkState = await api.rpc.system.networkState();
console.log('\x1b[32m%s\x1b[0m %s', 'networkState:',  networkState);
```
the node returns:
```
networkState: {"peerId":"","listenedAddresses":[],"externalAddresses":[],"connectedPeers":{},"notConnectedPeers":{},"averageDownloadPerSec":0,"averageUploadPerSec":0,"peerset":{"messageQueue":0,"nodes":{}}}

```
NOTE: [PSP-6](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1511-system_networkstate) states: "NOTE: This API is future-reserved, specification will be adjusted." 

NOTE: testing this paritytech polkadot node 0.9.19 returned: `TypeError: api.rpc.system.networkState is not a function` so it seems that paritytech has not implemented this yet.

## Expected Behavior

- The expected return value should contain data in the returned fields.

## Current Behavior

- Currently returns JSON object with field, but all values are empty.

## Possible Solution

-

## To Reproduce
Steps to reproduce the behaviour:

1. 
2. 
3. 

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
</br>

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by danforbes** [comment]
Not implemented by Substrate either
