### ISSUE TITLE
polkadot.js/api function api.rpc.system.accountNextIndex returns error

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#2533]
## Describe the bug

- When calling polkadot.js function, for example:
```
   const ADDR_Alice = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY';
    const aliceNonce = await api.rpc.system.accountNextIndex(ADDR_Alice);
    console.log(`aliceNonce: ${aliceNonce}`);
```

## Expected Behavior

- The node should return nonce for the given account.

## Current Behavior

- Returns error: `RPC-CORE: accountNextIndex(accountId: AccountId): Index:: -32000: unsupported metadata version 14: null`

## Possible Solution

-

## To Reproduce
Steps to reproduce the behaviour:

1. 
2. 
3. 

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
</br>

## Specification

- go version:
- gossamer version: runtime v0.9.19
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:
- polkadot/api version: 8.3.1

**Comment by danforbes** [comment]
Duplicate of #2462
