### ISSUE TITLE
polkadot.js/api error calling api.rpc.payment.queryInfo

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#2538]
## Describe the bug

- When calling polkadot.js api function api.rpc.payment.queryInfo, for example:
```
   const paymentQueryInfo = await api.rpc.payment.queryInfo(testExt);
    console.log('\x1b[32m%s\x1b[0m %s', "paymentQueryInfo:", paymentQueryInfo);
  
```

## Expected Behavior

- Should return u128 representing the fee of the extrinsic

## Current Behavior

- returns error: `RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: -32000: Failed to call the TransactionPaymentApi_query_info exported function.: null`

## Specification

- gossamer version: runtime v0.9.19
- polkadot/api version: 8.3.1

**Comment by danforbes** [comment]
Not a problem
