### ISSUE TITLE
Research how to optimize block tree functions

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#254]
Please take a look at the existing block tree implementation in https://github.com/ChainSafe/gossamer/tree/development/core/blocktree. This is a naive implementation, so it needs to be optimized. 

The goal is to be able to efficiently prune the block tree using these functions.

Please research and provide pseudo code for optimizations.

**Comment by amerameen** [comment]
I am taking a look at this, but it would be best to collaborate with others on it. 

@steviezhang @ansermino

**Comment by noot** [comment]
related to #871

**Comment by amerameen** [comment]
Closing for now. Will reopen if necessary.
