### ISSUE TITLE
Blocks do not finalise in cross-client devnet

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#2613]
## Describe the bug

- If you run a cross-client devnet (2 gossamer nodes, 1 substrate node), blocks never get finalised.
```
2022-06-16T19:47:13+05:30 DBUG failed to validate vote message &{1 0 stage=precommit hash=0x0000000000000000000000000000000000000000000000000000000000000000 number=0 authorityID=0xd17c2d7823ebf260fd138f2d7e27d114c0145d968b5ff5006125f2414fadae69}: block does not exist	vote_message.go:L64	pkg=grandpa
```
My feeling is that above error message is the culprit. Most likely we are creating a block header without populating block hash into it.

**Comment by kishansagathiya** [comment]
- The problem is happening in `getPreVotedBlock`. There is `getPossibleSelectedBlocks` which gives us blocks with more than threshold votes, 
getPossibleSelectedBlocks gives 0 blocks. so we go to `getGrandpaGHOST` which returns a vote without setting any hash.

I am not yet sure, which one is the abnormal part here getGrandpaGHOST or getPossibleSelectedBlocks

**Comment by kishansagathiya** [comment]
it does look like we are receiving proper pre vote messages. All prevote messages that we get are good. we are receiving pre votes from substrate

Problem is that we don't send proper pre-commit message.

**Comment by EclesioMeloJunior** [comment]
I believe you found an investigation path! I think we could transform this issue into an epic as `Blocks do not finalize in cross-client devnet` can group a couple of related issues, what do you think? @danforbes @timwu20

**Comment by danforbes** [comment]
@EclesioMeloJunior let's talk more about that idea in standup on Monday 👍🏻

**Comment by kishansagathiya** [comment]
Seems like blocks are getting finalised. So, after finalising a block we are supposed to write it in the db and chain sync will pick it up and share with rest of the network. For whatever reason chain sync always thinks that blocks are not finalised. So, either we don't write things proper or don't read them or something in between.

After finalising a block we send a commit message to peers. I see another gossamer node getting the commit messages, but not substrate (may be I don't know what log to look for). The gossamer node that gets commit message also doesn't seem to use that info.

**Comment by kishansagathiya** [comment]
seeing this error sometimes with 2 substrate 1 gossamer
```
2022-07-19T16:24:20+05:30 EROR block data processing for block with hash 0xf71994272a0ccc2ee46e0e3d90645ed95448c33bd602f29da3431c1bb8cda695 failed: block producer equivocated	chain_processor.go:L86	pkg=sync
```

**Comment by kishansagathiya** [comment]
@EclesioMeloJunior we have been tracking them all in this issue

**Comment by kishansagathiya** [comment]
@danforbes I don't think this issue is relevant anymore. We don't have any finalisation or block building issue as far as I know.

**Comment by danforbes** [comment]
Closing per the above.
