### ISSUE TITLE
tests(dot/sync): Add tests against latest `gssmr` runtime

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#2703]
## Issue summary

- The following tests have been updated in PR #2671 to point to the old `gssmr` runtime:
  - `TestChainProcessor_HandleBlockResponse_ValidChain`
  - `TestChainProcessor_HandleBlockResponse_MissingBlocks`
  - `TestChainProcessor_HandleBlockResponse_BlockData`
  - `TestChainProcessor_ExecuteBlock`
- Investigate and add new tests against latest `gssmr` runtime  

## Other information and links

- #2671

**Comment by EclesioMeloJunior** [comment]
@timwu20 I think we can close this issue in favor of these other issues:
- https://github.com/ChainSafe/gossamer/issues/2895
- https://github.com/chainsafe/gossamer/issues/3016
