### ISSUE TITLE
tests(lib/babe): Add tests against latest `dev` runtime

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#2704]
## Issue summary

- The following tests have been updated in PR #2671 to point to the old `dev` runtime:
  - `TestBuildBlock_ok`
  - `TestApplyExtrinsic`
  - `TestBuildAndApplyExtrinsic`
  - `TestBuildBlockTimeMonitor`
  - `TestVerificationManager_OnDisabled_InvalidIndex`
  - `TestVerificationManager_OnDisabled_NewDigest`
  - `TestVerificationManager_OnDisabled_DuplicateDigest`
  - `TestVerificationManager_VerifyBlock_Ok`
  - `TestVerificationManager_VerifyBlock_Secondary`
  - `TestVerificationManager_VerifyBlock_InvalidBlockOverThreshold`
  - `TestVerificationManager_VerifyBlock_InvalidBlockAuthority`
  - `TestVerifyAuthorshipRight`
  - `TestVerifyAuthorshipRight_Equivocation`
- Investigate and add new tests against latest `dev` runtime  

## Other information and links

- #2671

**Comment by EclesioMeloJunior** [comment]
@jimjbrettj the PR #3037 resolves this issue?
