### ISSUE TITLE
Change GetBlockByNumber to GetBlocksByNumber and return multiple blocks

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#2748]
## Issue summary
- There could be multiple blocks with the same block number, so `GetBlockByNumber` is not very useful. Currently, it returns best block. I believe, it would make more sense if we start returning all blocks with same block number. 
- We could also have `GetBestBlockByNumber` is that seems important or useful.

## Other information and links

- code links 
https://github.com/ChainSafe/gossamer/blob/a0a1804b8572e1eeba8faceccc3254409786ab46/lib/babe/state.go#L29
https://github.com/ChainSafe/gossamer/blob/491af9516dad3cef582d04162558d83acc225e77/dot/state/block.go#L264

**Comment by kishansagathiya** [comment]
@timwu20 @danforbes what do you think?

**Comment by danforbes** [comment]
@kishansagathiya can you clarify where this `GetBlockByNumber` function is defined?

**Comment by kishansagathiya** [comment]
> can you clarify where this GetBlockByNumber functi

edited the description

**Comment by timwu20** [comment]
When would we need this function?

**Comment by kishansagathiya** [comment]
> When would we need this function?

Think we in general need this. Considering there could be multiple blocks with the same number, it would be false always return just one block per number.
