### ISSUE TITLE
`Unmarshal` Method for Genesis Runtime Field

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2766]
## Task summary

- See https://github.com/ChainSafe/gossamer/pull/2808#pullrequestreview-1099154903
- Create a struct with an `Unmarshal` function for the `Runtime` field of the `Genesis` struct. From https://github.com/ChainSafe/gossamer/pull/2543#discussion_r937827980

**Comment by qdm12** [comment]
@danforbes @timwu20 I don't think we want a custom `MarshalJSON` right, just `UnmarshalJSON` to take care of the `System`/`system` field right?

**Comment by danforbes** [comment]
Yes my fault @qdm12 I have updated the Issue 🙏🏻
