### ISSUE TITLE
Investigate `TransactionPaymentCallApi` Runtime APIs and RPC Endpoints

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2800]
## Task summary

- This task encapsulates the investigation associated with implementing the `TransactionPaymentCallApi`, which should involve understanding how to calculate the correct values that the two RPC endpoints need to return, as well as determining the correct paths for the new RPC endpoints.

**Comment by edwardmack** [comment]
fixed in PR #2889
