### ISSUE TITLE
dot/state/pruner: refactor code to be more understandable and modular

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2835]
The pruner code is (unit, integration and even usage-wise) untested, and hard to understand.

Since the trie lazy loading of nodes will interact a lot more with the database, and that the pruner already does some work with pruning database keys (node hashes), it feels required to understand the online pruner code and make it more modular.

**Comment by timwu20** [comment]
For context, we have disabled the online pruner in gossamer.  Maybe something to work on after implementing the lazy loaded trie @dimartiro.

**Comment by timwu20** [comment]
I would characterize this issue as an optimization not required to achieve any of the current milestones.

**Comment by timwu20** [comment]
Already being handled in the StateDB Optimizations epic.
