### ISSUE TITLE
trie: implement lazy loading of trie nodes from disk

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2838]
Our memory usage is high since we keep all trie nodes in memory. 

Instead we should (like Substrate) store all `node hash -> node encoding` on disk, and lazy load them as we need to access the trie (both read and write). Only the root hash should be kept in memory, and every node should be retrieved from disk as we go deeper in the trie (to insert or retrieve).

We should also implement pruning for nodes inserted/modified in uncle blocks (and make sure the finalized block doesn't contain them).

We can also implement a cache to keep the most frequently used nodes in memory and prevent decoding them again

Related with #2835 and #2836

**Comment by dimartiro** [comment]
I found that Ethereum is also using a lazy loading strategy with the `node keys -> encoded nodes` 

https://github.com/ethereum/go-ethereum/blob/d76efbb9be403689bc8d677a16af453728a7a513/trie/triedb/hashdb/database.go#L186-L224

**Comment by dimartiro** [comment]
In substrate, they are using this [trie crate ](https://github.com/paritytech/trie) for all trie operations, and they created a [TrieDB structure backed by a DB](https://github.com/paritytech/trie/blob/6eb4b88e0781da2db7dda0021249a8fa4244bc5d/trie-db/src/triedb.rs#L120-L128) with a cache, and they are implementing the [lazy loading there](https://github.com/paritytech/trie/blob/6eb4b88e0781da2db7dda0021249a8fa4244bc5d/trie-db/src/lookup.rs#L489-L570)

**Comment by dimartiro** [comment]
This change will help us to improve our memory usage and our node startup time when we are using an snapshot, also improving our debugging time when we are trying to sync to the tip of the chain and we need to use snapshots for that.

**Comment by dimartiro** [comment]
This issue will be Done when #3805 is completed

**Comment by P1sar** [comment]
Design Design considered complete
