### ISSUE TITLE
ZombieNet Support and CI Integration

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2842]
## Task summary

- [ZombieNet](https://github.com/paritytech/zombienet) is a tool to easily spawn ephemeral Polkadot/Substrate networks and perform tests against them. This Epic will track the investigation into the capabilities that must be exposed by Gossamer in order to integrate with ZombieNet, including its [CLI](https://paritytech.github.io/zombienet/cli/index.html) and [DSL/domain-specific language](https://paritytech.github.io/zombienet/cli/test-dsl-definition-spec.html). Once Gossamer can integrate with ZombieNet, ZombieNet should be used to drive enhanced CI/CD testing piplelines for Gossamer in order to make it easier to ensure that Gossamer nodes behave as expected in a number of different network topologies.

**Comment by qdm12** [comment]
Discussing this on https://github.com/paritytech/zombienet/discussions/623 (sorry I wasn't aware/didn't search for this issue)
