### ISSUE TITLE
Move integration tests for network and grandpa packages out of unit tests

### ISSUE THREAD

**Issue by jimjbrettj** [ChainSafe/gossamer#2850]
## Issue summary

- Currently integration tests being run as unit tests are greatly increasing the time it takes to run unit tests in CI. Specifically this is an issue for the network and grandpa packages. This issue involves moving the current integration tests to be run as actual integration tests as opposed to unit tests.

**Comment by danforbes** [comment]
@jimjbrettj do we want to turn this into an Epic and create separate Issues for the different packages/tests?

**Comment by jimjbrettj** [comment]
Perhaps there is minor improvements that can be had, but this effort has been undertaken and resolved
