### ISSUE TITLE
Submit and handle equivocation report

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#2853]
## Issue summary

- In case of an equivocation, substrate reports it (https://github.com/paritytech/substrate/blob/c24431eb6a95197550b30715a4c124be1aea79de/client/consensus/babe/src/lib.rs#L1228)
- by reporting, I mean, it submits an unsigned extrinsic containing equivocation proof and key ownership proof.
- On submitting this, an offence gets reported. (look for `report_offence`). I wonder if this method of reporting offence is peer scoring equivalent of substrate. More investigation is needed here. 
- Interesting functions to look for in substrate are `submit_report_equivocation_unsigned_extrinsic`, `submit_unsigned_equivocation_report`, `report_equivocation_unsigned`, `do_report_equivocation`

At the moment we don't report equivocation. The task list here is

- [ ] We  report the equivocation the way substrate does. 
- [ ] Investigate what should we do on finding these reports and offence 

## Other information and links

- Inspired from https://github.com/ChainSafe/gossamer/pull/2827#issuecomment-1251227120

**Comment by timwu20** [comment]
Pretty sure this is closed by #2827
