### ISSUE TITLE
`getPreVotedBlock` is not returning GRANDPA-GHOST

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#2888]
## Describe the bug

- `getPreVotedBlock` should return the pre-voted block B, also known as GRANDPA-GHOST, but this function is returning the block with the greatest amount of votes but not the supermajority

**Comment by jimjbrettj** [comment]
I looked here and it seems that if no block has > 2/3 prevotes then it does indeed return the best candidate @EclesioMeloJunior 

https://spec.polkadot.network/#algo-grandpa-ghost
