### ISSUE TITLE
Remove Unneeded Chain Specifications

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2895]
## Issue summary

- Since the following chain specifications are no longer necessary for the development of Gossamer, they should be removed from the Gossamer repository (this will require significant restructuring of the Gossamer tests, which is why this is an Epic):
  - `dev-staking`
  - `dev-v3substrate`
  - `dev`
  - `gssmr-staking`
  - `gssmr-v3substrate`
  - `gssmr`

## Other information and links

- All relevant specification and configuration files are within this directory https://github.com/ChainSafe/gossamer/tree/development/chain

**Comment by EclesioMeloJunior** [comment]
I face a problem with one of those chain specifications in the test `TestAuthorSubmitExtrinsic` related to the new `Account Info` field, more specifically the `dev-v3substrate`. Basically, the `dev-v3substrate` does not have the correct storage key for the account info, the account info should contain 80 bytes and this chain spec was providing a 76 bytes long account info storage key.

I fixed the problem by changing from `dev-v3substrate` to `westend-dev`.

refs: 
- https://github.com/centrifuge/go-substrate-rpc-client/pull/309
- https://github.com/centrifuge/go-substrate-rpc-client/commit/8b830c55b96d605bef01f9e84f462ad3701670a6

@danforbes fyi
