### ISSUE TITLE
BlockDB Operations

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/gossamer#292]
The purpose of this is to discuss the implementation on block operations, specifically what data needs to be written to the database instance, and what read operations should exist.

**Main Questions:**
1) What BLOCK data needs to be written to the underlying database?
2) Do these values need to be encoded prior to being written (using SCALE)? 

### BlockDB Data Writes:

Reviewing the [polkadot-js](https://github.com/polkadot-js/client) implementation it seems that multiple layers of block data are being written, although this is not clearly discussed within the specification.

The data that seems to be written include the following in key-value pair format (will be written to the DB as `[]byte`):

```
Key: ‘bestHash’, Value: ‘0x….’,
Key: ‘bestNumber’, Value: ‘10’,
Key: Hash, Value: ‘blockData’,
Key: Hash, Value: ‘blockHeader’, // I think parent_hash?
Key: blockNumber, Value: ‘Hash’, 
``` 

As shown here:
https://github.com/polkadot-js/client/blob/master/packages/client-db/src/block/index.ts

Keys Definition:
https://github.com/polkadot-js/client/blob/master/packages/client-db/src/block/keys.ts

How its used (Genesis Creation): LN: ~155
https://github.com/polkadot-js/client/blob/master/packages/client-chains/src/index.ts

Yet in the [substrate](https://github.com/paritytech/substrate) implementation, I don’t see the same data being written. I believe `blockData` is written but then it seems `<BlockHash, BlockNumber, ParentHash and ChangeSet>`. 

Substrate Implementation:

Insert blockData ~LN 98
https://github.com/paritytech/substrate/blob/master/core/network/src/protocol/sync/blocks.rs

ChangeSet  ~LN 203
https://github.com/paritytech/substrate/blob/master/core/state-db/src/lib.rs

### BlockDB Data Reads

Proposed Block GET ops:

`GetBlock`
`GetBestHash`
`GetBestNumber`
`GetBlockByHash`
`GetBlockByNumber`
`GetReceiptsByHash`
`GetBody`
`GetHeader`
`GetHeaderByHash`
`GetHeaderByNumber`
`GetCurrentHeader`

### Definitions From Spec

**BlockData (Definition E.2):**
```
Block header hash 
Header→  Block header 5-tuple (Denition 3.5)
Body Array of extrinsics→  Array of Byte arrays (Section 3.2)
Receipt→ Block Receipt Byte array 
Message Queue→  Block message queue Byte array
Justification→  Block Justification Byte array
```

**Header (Section 3.3.1.1):**
```
ParentHash→ header of parent
Number→ block number
StateRoot→ root of merkle trie
ExtrinsicsRoot→ reserved for runtime to validate extrinsics composing of the block body 
Digest→ auxiliary data
```

Any discussion on what block data needs to be written would be appreciated!

**Comment by dutterbutter** [comment]
@ansermino @noot

**Comment by amerameen** [comment]
Starting to take a look at this. In terms of your second question re:SCALE:

My thoughts are that this is unnecessary. The BlockDB will be accessed from within Gossamer for use within Gossamer, so don't see the need for encoding/decoding. If we retrieve a block from the DB to include it in a network message or something like that, we can encode it then.

That being said, the underlying data for the State Root or the Extrinsics Root will already be encoded.
--
Curious to hear your thoughts @ansermino @noot

**Comment by ansermino** [comment]
```
Key: Hash, Value: ‘blockData’,
Key: Hash, Value: ‘blockHeader’
```
Can you clarify what these are? How would the same hash key return different values?

**Comment by dutterbutter** [comment]
Using a prefix the same way polkadot-js and ethereum do @ansermino 

`hdr:hsh:`
`blk:hsh:`
