### ISSUE TITLE
Panic during syncing of Polkadot

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#2920]
## Describe the bug

- The node panics intermittently (not at the same block height) on staging syncing setups. 
- From the AWS logs of the polkadot gossamer node:
```
panic: failed to re-add transactions to chain upon re-org: failed to get runtime instance
```

## Expected Behavior

- Does not panic

## Current Behavior

- We introduced these panics in a previous PR to notify us if these things happen on long running nodes.

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  panic: failed to re-add transactions to chain upon re-org: failed to get runtime instance
  ```
</details> 
</br>

## Specification

- go version: `1.18`
- gossamer version: `development`
- gossamer commit tag: NA
- gossamer commit hash: NA
- operating system: Ubuntu 19.10
- additional links: NA

**Comment by jimjbrettj** [comment]
resolved with #2934
