### ISSUE TITLE
Implement `ext_crypto_ecdsa_generate` Host API

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/gossamer#2951]
## Task summary

- Implement the `ext_crypto_ecdsa_generate` [Host API](https://spec.polkadot.network/#chap-host-api).

## Specification reference

- https://spec.polkadot.network/#_ext_crypto_ecdsa_generate

**Comment by axaysagathiya** [comment]
merged @lakshya-sky's [PR](https://github.com/ChainSafe/polkadot-spec/pull/14) on chainsafe/polkadot-spec repo
