### ISSUE TITLE
SCALE encoding of Arrays is missing to encode the length

### ISSUE THREAD

**Issue by radkomih** [ChainSafe/gossamer#2975]
Hi there, 
shouldn't this method also encode the length?

https://github.com/ChainSafe/gossamer/blob/1ec0f63923bc9c43e73cc49d4c2a0f6d2dcdbae4/pkg/scale/encode.go#L216

```go
func (es *encodeState) encodeArray(in interface{}) (err error) {
	v := reflect.ValueOf(in)
	for i := 0; i < v.Len(); i++ {
		err = es.marshal(v.Index(i).Interface())
		if err != nil {
			return
		}
	}
	return
}

```

**Comment by timwu20** [comment]
Thanks for noticing @radkomih.  In this case the comment is incorrect.  Fixed size arrays don't require the prefixed length encoding.  We will update that comment.
