### ISSUE TITLE
Dependency inject databases and tables

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2981]
In many places we create the database or the table in constructors (or even worst in Start methods), whereas it should ideally be injected as dependency instead.

This blocks some modifications such as using a database in the trie code, or creates duplicate table objects which may or may not be thread safe. It also makes changing our database implementation harder.

**Comment by timwu20** [comment]
Completed in https://github.com/ChainSafe/gossamer/pull/3434
