### ISSUE TITLE
Create `internal/database/badger` package and drop chaindb

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2982]
A few key points why this is needed:

- :warning: With #2929 and recent commits, the in-memory tries are no longer leaking memory, and it can clearly be seen our current database implementation leaks memory pretty bad and also uses 50% of our CPU usage, which is also bad.
- having a separate repository for the database implementation (and interfaces) doesn't make sense now and probably won't in the future either.
- Interfaces, constructors are oddly designed in the chaindb repository
- chaindb uses a rather outdated and obscure fork of badgerdb

Prioritizing this issue right now, especially to see the result memory-usage-wise in order to take the right decision regarding state code changes (lazy loading, v1 state trie, other performance considerations).

The plan is to create an `internal/database/badger` package using `badger/v3` with cleaner constructors and interfaces in the rest of the code, and remove the chaindb dependency. A very simple `internal/database/memory` package might be created as well to ensure we have the right interfaces for multiple implementations. More database implementations can be added later on if needed for different memory or CPU usage trade offs.

This is blocked by #2981 since our code is rather tightly coupled unfortunately when it comes to replacing the database.

**Comment by dimartiro** [comment]
I think we can close this issue since we replaced chaindb to pebble some time ago. What do you think @timwu20 ?
