### ISSUE TITLE
Use MDNS implementation `github.com/libp2p/go-libp2p/p2p/discovery/mdns`

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2993]
Our current implementation (before PR #2794) is based on https://github.com/libp2p/go-libp2p/tree/644dadc30bcc712ea13ad730f50b5e8ec1b949f2/p2p/discovery/mdns_legacy

Unfortunately, `mdns_legacy` got removed in https://github.com/libp2p/go-libp2p/commit/707100a521dace4a7a87fd17c04042ea483380b5 so all releases since v0.21.0 do not have it anymore. The only alternative since is https://github.com/libp2p/go-libp2p/blob/4c74181d0dada0b4d600885285b96afee74e223d/p2p/discovery/mdns/mdns.go

Unfortunately again, this new mdns implementation will not work with our RPC test `TestStableNetworkRPC` with 3 nodes.

```sh
MODE=rpc go test -run ^TestStableNetworkRPC$ github.com/ChainSafe/gossamer/tests/rpc -v
```

This issue may be related to https://github.com/libp2p/go-libp2p/issues/1333 (or not).

After #2794 is merged, we should try upgrading to the new mdns package https://github.com/libp2p/go-libp2p/blob/4c74181d0dada0b4d600885285b96afee74e223d/p2p/discovery/mdns/mdns.go and remove the code in `internal/mdns` (based on mdns_legacy, in order to be able to upgrade libp2p dependencies).

**Comment by timwu20** [comment]
We should probably revisit this at some point since we're using a fork of the old `libp2p/go-libp2p/p2p/discovery/mdns_legacy`.
