### ISSUE TITLE
Add Block Origin to BlockData

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3004]
## Issue summary
We are not supposed to report equivocation if they happen during initial sync, because they could be stale.

To check if we are in initial sync, we need something like block origin. Block origin tells about where did we import this block. It could be things like we got it in the initial sync, was broadcasted in the network, genesis block, got it from a file, etc.
 The best place to add that would be in BlockData (https://github.com/ChainSafe/gossamer/blob/8320a2de02e1122ff3dd75c1d03cbea7d52f5c8c/dot/types/block_data.go#L15). Going through our codebase, we don't have logic to find. We need to add that logic and populate block data with block origin.

Once we have support for block origins, we can just add a condition such that if block origin is initial sync don't report equivocation.

## Other information and links

- More context here https://github.com/ChainSafe/gossamer/pull/2947#discussion_r1032579357
Block Origin in substrate
- https://github.com/paritytech/substrate/blob/86c6bb9614c437b63f3dbd2afddef52f32af7866/primitives/consensus/common/src/lib.rs#L62-L63

**Comment by timwu20** [comment]
@EclesioMeloJunior can you create an epic to house block importing improvements.

**Comment by EclesioMeloJunior** [comment]
Closing this issue in favor of https://github.com/ChainSafe/gossamer/issues/4208
