### ISSUE TITLE
Blocks don't get finalised

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3028]
## Describe the bug

- Ran a devnet full off 3 gossamer nodes. Ran it till some 450 block got created.
- Each peers can sync with nodes. Some of the pre-votes and pre-commits are being shared, but we don't reach a point where we finalise any blocks.

## Expected Behavior

-

## Current Behavior

-

## Possible Solution

-

## To Reproduce
Steps to reproduce the behaviour:

1. 
2. 
3. 

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
</br>

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by EclesioMeloJunior** [comment]
As @kishansagathiya pointed out in the description the nodes in the network are not finalizing blocks due to some problems in the message exchange, some nodes are not receiving the GRANDPA vote messages (pre-votes/pre-commits), so I think would be better if we change this issue name to `grandpa: nodes are not receiving vote messages`.

**Comment by EclesioMeloJunior** [comment]
After some investigations we found tha, in a setup of 3 gossamer nodes, when one start it already defines a pre-vote and send it but the other nodes didnt connect yet to receive the pre-vote message and this is causing the problem. Gossamer should send pre-votes only when it has connected peers, this improvement was described more in the issue: https://github.com/ChainSafe/gossamer/issues/2760. I think we can close this issue in favor of the issue https://github.com/ChainSafe/gossamer/issues/2760
