### ISSUE TITLE
target block number out of bounds

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3068]
## Describe the bug

Saw this log on importing blocks on westend network
```
2023-01-25T20:38:40+05:30 INFO     🚣 currently syncing, 2 peers connected, target block number 4294967295, 0.00 average blocks/second, 0.00 overall average, finalised block number 13824 with hash 0xc6084b775c37ab26f95b44cc81b26898d34d7fe64e3135fddfaf1a483ec1ba94	chain_sync.go:L384	pkg=sync
```

At the time of writing block number of best block is `14,363,546`, but gossamer logs says that target block is `4294967295`.

This doesn't seem to impact the functionality of gossamer as far as I have seen, but still not nice to see such a strange number.
## Expected Behavior

-

## Current Behavior

-

## Possible Solution

-

## To Reproduce
Steps to reproduce the behaviour:

1. 
2. 
3. 

## Log output
https://gist.github.com/kishansagathiya/7e8bfa0479f23e732ad4f60cd7b9b426

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

**Comment by EclesioMeloJunior** [comment]
Hey! I would like to mention (just to bring more context) that the value `4294967295` is the max value of uint32 type `uint(1<<32 - 1)` and this value is returned by the function `chainSync.getTarget()` when the `len(cs.peerState) == 0`, the `len(cs.peerState)` is 0 usually when the node don't receive block announcements from other peers

**Comment by kishansagathiya** [comment]
@EclesioMeloJunior sure
