### ISSUE TITLE
Implement Chain RPC Methods & Error Codes

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#309]
_If this needs to be split into smaller PRs or some of the RPC calls can't be implemented now, please create another task with a list of whatever remains_

**References:** 
- https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md#Chain
- https://polkadot.js.org/api/substrate/rpc.html 

**Where to Implement:** https://github.com/ChainSafe/gossamer/blob/development/dot/rpc/modules/chain.go

**To Do**
- [x] Chain RPC Error Codes
- [x] getHeader
- [x] getBlock
- [x] getBlockHash
- [ ] getFinalizedHead

**Comment by edwardmack** [comment]
This issue has been split to move chain_getFinalizedHead into it's own issue #779
