### ISSUE TITLE
Implement state RPC methods & error codes

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#310]
_If this needs to be split into smaller PRs or some of the RPC calls can't be implemented now, please create another task with a list of whatever remains_

**References:** 
- https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#111-state
- https://polkadot.js.org/api/substrate/rpc.html 

### State RPC calls
- [ ] [State RPC Error Codes](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#11121-state-errors)
- [ ] [`state_call`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1113-state_call)
- [x] [`getMetadata`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1119-state_getmetadata) 
- [x] [`queryStorage`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#11111-state_querystorage) 
- [x] [`subscribeRuntimeVersion`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#11113-state_subscriberuntimeversion-pubsub)
- [x] [`subscribeStorage`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#11115-state_subscribestorage-pubsub)
- [ ] [`getReadProof`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#11112-state_getreadproof)
- [x] [`getRuntimeVersion`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#11110-state_getruntimeversion)

**Comment by edwardmack** [comment]
- All methods need to implement handling block hash parameter (See issue #834)
- All Child calls, need understanding of Child Info and Child type, currently labeled "future-reserved", how should we deal with that?

**Comment by danforbes** [comment]
@EclesioMeloJunior - can we close this since we have individual issues now?

**Comment by EclesioMeloJunior** [comment]
@danforbes yes!
