### ISSUE TITLE
Implement author RPC methods & error codes

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#312]
Complete the following RPC calls and return error types as defined in the specification. Check mark each completed RPC call.

**References:** 
- https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#18-author
- https://polkadot.js.org/api/substrate/rpc.html 

### Author RPC calls
- [x]  [`hasSessionKeys`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#187-author_hassessionkeys) 
* [Substrate reference- `has_session_keys`](https://github.com/paritytech/substrate/blob/master/client/rpc/src/author/mod.rs#L124)

**Comment by edwardmack** [comment]
Questions:
- author_removeExtrinsic says remove given extrinsic from the pool and ban it to prevent reimporting.  Do we have functionality to ban these?
- author_rotateKeys - Generate new session keys and returns corresponding public key.  I need help understanding how session keys are currently handled, and where/how we can generate new ones.
- author_hasSessionKeys - Need help understanding session keys.
- Errors, todo, but I need better understanding of what some of these errors are.
