### ISSUE TITLE
Reconcile types.BlockHeader and common.BlockHeader

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#314]
right now we have two block headers, `types.BlockHeader` in core/types and `common.BlockHeader`. the one in `types` is used by the blocktree, the one in `common` is used by p2p/message.go.  The one in types has a hash field and the one in common doesn't.  It seems like we need both types, since a p2p BlockAnnounceMessage won't include a Hash field, and it makes sense for the block tree to know of the block hash for storage.

I suggest we make two types in `core/types`, `BlockHeader` and `BlockHeaderWithHash` so that we have both, and remove `common.BlockHeader`. Also `BlockHeader` should have a `Hash()` function.  Either that or we need to do custom encoding/decoding for BlockAnnounceMessage.

What are everyone's thoughts?

**Comment by ansermino** [comment]
It seems `BlockAnnounceMessage` is an alias for `common.BlockHeader` ([here](https://github.com/ChainSafe/gossamer/blob/a0569ff5d07259acb12e6b657139ec695ee79667/p2p/message.go#L259)). I would like to propose this be its own type, removing the need for two BlockHeader types. `BlockHeader`.

**Comment by noot** [comment]
I'm also okay with that, the only thing is that the core.Service takes a block header in ProcessBlock (which should be the one without the hash), so does it make sense for it to take a p2p.BlockAnnounceMessage?

**Comment by ansermino** [comment]
Shouldn't that take a complete block?

**Comment by noot** [comment]
yeah it does take a complete block, it's the one with the 5 fields as in the spec:
```
type BlockHeader struct {
	ParentHash     Hash
	Number         *big.Int
	StateRoot      Hash
	ExtrinsicsRoot Hash
	Digest         []byte 
}
```

since ProcessBlock is going to put it into `core_execute_block` it needs to be the usual PRE block format.

**Comment by amerameen** [comment]
What's the consensus here? Are we creating a BlockAnnouceMessage type that replaces the common.BlockHeader?

@noot @ansermino
