### ISSUE TITLE
babe/digest: Gossamer could not verify slot claim VRF proof at `#5608874`

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#3236]
## Describe the bug

Gossamer fails to verify the VRF proof while requesting the range from block `#5608705` to `#5610241`

```
2023-04-21T13:26:27Z ERROR    block data processing for block with hash 0x711cca084131819539f7c85d0f362214aee947a897d43d4576bf123dec288813 failed: processing block data with header and body: babe verifying block: failed to verify pre-runtime digest: could not verify slot claim VRF proof	chain_sync.go:L741	pkg=sync
```

But before requesting the range Gossamer successfully imported the block `#5608275` which contains the BABE Next Epoch Data and BABE Config Data digests

- BABE Next Epoch Data
```
2023-04-21T13:25:53Z DEBUG    stored BABENextEpochData data: {{[{[102 85 132 42 246 238 38 228 88 181 254 162 211 181 190 178 221 140 249 107 36 180 72 56 145 158 26 226 150 72 223 12] 1} {[92 167 131 48 94 202 168 131 131 232 44 215 20 97 44 22 227 205 24 232 243 118 34 15 45 159 187 181 132 214 138 105] 1} {[212 81 34 24 150 248 208 236 69 62 90 78 252 0 125 32 86 208 73 44 151 210 88 169 187 105 170 28 165 137 126 3] 1} {[236 198 169 213 112 57 219 36 157 140 107 231 182 155 98 72 224 156 194 252 107 138 97 201 177 9 13 248 167 93 218 91] 1}] [237 156 197 246 97 87 56 66 224 116 137 55 52 103 165 76 225 1 189 69 137 154 109 221 47 204 220 167 79 77 161 61]} map[1:{[] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 2:{0} 3:{0 0 0}]} for hash: 0x709238036170633c14ad9fc57e22d65601329a2d71e89f85c9204c094c0e76a8 to epoch: 9642	digest.go:L198	pkg=digest
```

- BABE Config Data
```
2023-04-21T13:25:53Z DEBUG    stored BABENextConfigData data: {{257 1024 0} map[1:{[] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 2:{0} 3:{0 0 0}]} for hash: 0x709238036170633c14ad9fc57e22d65601329a2d71e89f85c9204c094c0e76a8 to epoch: 9642	digest.go:L213	pkg=digest
```

We can notice that the babe config data digest contains a map with 3 fields and they only contain zeroes, which made me suspect about Gossamer failed to decode the babe config digest properly

**Comment by dimartiro** [comment]
I added a test to check if it's related with the decoding but seems to be working ok.
The 0's in the map are related with the cache in the structure we are using to decode the `nextConfigData`

```
// VaryingDataType is analogous to a rust enum.  Name is taken from polkadot spec.
type VaryingDataType struct {
	value VaryingDataTypeValue
	cache map[uint]VaryingDataTypeValue
}
```

![image](https://user-images.githubusercontent.com/659400/236076668-9d34c1d0-f03d-433a-bbcc-6fc72223e8e6.png)

I will continue investigating how to solve this.

**Comment by dimartiro** [comment]
I created one more test to try to verify the `PreDigestBlock` recreating the same scenario.

I'm creating a verifier using the `NextConfigData` and the `NextEpochData` from block [#5608275](https://westend.subscan.io/block/0x709238036170633c14ad9fc57e22d65601329a2d71e89f85c9204c094c0e76a8?tab=log) and trying to verify the `PreDigestBlock` from block [#5608874](https://westend.subscan.io/block/0x711cca084131819539f7c85d0f362214aee947a897d43d4576bf123dec288813?tab=log)

I was able to reproduce the same error:

```golang
func Test_VerifyPreDigestWithIssues(t *testing.T) {
	ctrl := gomock.NewController(t)
	mockBlockState := NewMockBlockState(ctrl)

	//Block #5608275 NextConfigData
	enc := common.MustHexToBytes("0x03010100000000000000040000000000000002")

	//Decode NextConfigData
	var dec = types.NewBabeConsensusDigest()
	err := scale.Unmarshal(enc, &dec)
	require.NoError(t, err)

	decValue, err := dec.Value()
	require.NoError(t, err)

	nextConfigData := decValue.(types.NextConfigData)

	//Block #5608275 NextEpochData
	enc = common.MustHexToBytes("0x01106655842af6ee26e458b5fea2d3b5beb2dd8cf96b24b44838919e1ae29648df0c01000000000000005ca783305ecaa88383e82cd714612c16e3cd18e8f376220f2d9fbbb584d68a690100000000000000d451221896f8d0ec453e5a4efc007d2056d0492c97d258a9bb69aa1ca5897e030100000000000000ecc6a9d57039db249d8c6be7b69b6248e09cc2fc6b8a61c9b1090df8a75dda5b0100000000000000ed9cc5f661573842e07489373467a54ce101bd45899a6ddd2fccdca74f4da13d")

	//Decode NextEpochData
	dec = types.NewBabeConsensusDigest()
	err = scale.Unmarshal(enc, &dec)
	require.NoError(t, err)

	decValue, err = dec.Value()
	require.NoError(t, err)

	nextEpochData := decValue.(types.NextEpochData)
	epochData, err := nextEpochData.ToEpochData()
	assert.NoError(t, err)

	//Block #5608874 PreRuntime
	enc = common.MustHexToBytes("0x0302000000e7631a10000000002664e2d4f9a6fb2ef0ba927b7bce0cf03f24bd58bf5b00ae001189a4f1de313bc1b688c11f30578d3f3b4ca1d9f97f453751d7a4d70c753989ae357380b50e076eb3756fee9f9ea4efa24ae7c58906466fd4e5062bb5d8e66cd411a9d2a11502")
	babePRD := types.NewBABEPreRuntimeDigest(enc)

	//Set threshold using NextConfigData and NextEpochData authorities
	threshold, err := CalculateThreshold(nextConfigData.C1, nextConfigData.C2, len(epochData.Authorities))
	assert.NoError(t, err)

	//Set verifierInfo config using NextConfigData and NextEpochData
	verifierInfo := &verifierInfo{
		authorities:    epochData.Authorities,
		randomness:     epochData.Randomness,
		threshold:      threshold,
		secondarySlots: nextConfigData.SecondarySlots > 0,
	}

	//Create verifier
	verifier := newVerifier(mockBlockState, 1, verifierInfo)

	//Try to verify PreRuntime from Block #5608874 
	_, err = verifier.verifyPreRuntimeDigest(babePRD)

	//Get the "could not verify slot claim VRF proof" error
	assert.EqualError(t, err, ErrBadSlotClaim.Error())
}
```

```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^Test_VerifyPreDigestWithIssues$ github.com/ChainSafe/gossamer/lib/babe

ok  	github.com/ChainSafe/gossamer/lib/babe	1.213s
```

Based on this I think that it's not an issue because we are trying to verify a `BabeSecondaryVRFPreDigest` with a configData that sets the `secondarySlots = 0`
So I think we have to import more blocks between the block [#5608275](https://westend.subscan.io/block/0x709238036170633c14ad9fc57e22d65601329a2d71e89f85c9204c094c0e76a8?tab=log) and [#5608874](https://westend.subscan.io/block/0x711cca084131819539f7c85d0f362214aee947a897d43d4576bf123dec288813?tab=log) to apply another `ConfigData` that will set the `secondarySlots > 0` and we will be able to validate the block [#5608874](https://westend.subscan.io/block/0x711cca084131819539f7c85d0f362214aee947a897d43d4576bf123dec288813?tab=log) after that.

**Comment by dimartiro** [comment]
> So I think we have to import more blocks between the block [#5608275](https://westend.subscan.io/block/0x709238036170633c14ad9fc57e22d65601329a2d71e89f85c9204c094c0e76a8?tab=log) and [#5608874](https://westend.subscan.io/block/0x711cca084131819539f7c85d0f362214aee947a897d43d4576bf123dec288813?tab=log) to apply another ConfigData that will set the secondarySlots > 0 and we will be able to validate the block [#5608874](https://westend.subscan.io/block/0x711cca084131819539f7c85d0f362214aee947a897d43d4576bf123dec288813?tab=log) after that.

I ran a script to find blocks with consensus logs between those 2 and I can't find any so I discard that hypothesis.
Next one is that we could have issues decoding the `ConfigData` and / or the `PreDigest` will be testing it and comparing with substrate.

**Comment by dimartiro** [comment]
At the end we figured out with @EclesioMeloJunior that this issue is related with the way we are decoding the `ConfigData` digest.
We were not considering the versioning as [substrate does](https://github.com/paritytech/substrate/blob/7d6084b5774ee13d0b33810c2830aa5a8506cbae/primitives/consensus/babe/src/digests.rs#L143C1-L152)

```rust
pub enum NextConfigDescriptor {
	/// Version 1.
	#[codec(index = 1)]
	V1 {
		/// Value of `c` in `BabeEpochConfiguration`.
		c: (u64, u64),
		/// Value of `allowed_slots` in `BabeEpochConfiguration`.
		allowed_slots: AllowedSlots,
	},
}
``` 

I opened a [PR](#3239 ) to support it
