### ISSUE TITLE
Add chain snapshots support

### ISSUE THREAD

**Issue by dimartiro** [ChainSafe/gossamer#3252]
### Chain Snapshots

The idea is to find a way to take chain snapshots so we can resume from the last finalized state.
This will help us to speed up the dev process without waiting to reach a specific block.

### First Version

Since we need to solve it first in staging, we can use a combination of shared disks (using AWS EFS) and executing daily backups to have recovery points that will act as chain snapshots.
Then we have to mount this disks in `/root/.gossamer/westend/db` path to store the chaindb there

### Second Version

We can improve the solution adding 2 CLI commands:

- **generate-snapshot:** Take and package snapshots to be shared later with the comunity
- **apply-snapshot:** To use an snapshot before running a new node

**Comment by P1sar** [comment]
@dimartiro please add link to what is blocking this issue

**Comment by P1sar** [comment]
Blocked by some infra problem.
