### ISSUE TITLE
move `ApplyForcedChanges` from `digest.BlockImportHandler` to `core/*Service.handleBlock` 

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#3330]
## Issue summary

- The method `*BlockImportHandler.Handle` does the `ApplyForcedChanges` but it is not its responsibility to perform this action, so a better place would be in the method  `handleBlock` which belongs to the core service at `dot/core` pkg

## Other information and links

- N/A

**Comment by ItIsOHM** [comment]
Hey i'm a beginner and want to contribute on this issue. I have forked and cloned the repo, but I can't find the "*BlockImportHandler.Handle" method as mentioned in the issue, can you please guide me on where I can find this?

**Comment by EclesioMeloJunior** [comment]
Hey @ItIsOHM, sure!

- The file `dot/digest/block_import.go` has a struct called `BlockImportHandler` and it contains the method `Handle(importedBlockHeader *types.Header)`, this method on line 33 https://github.com/ChainSafe/gossamer/blob/457fe39f7a12cb9eb04de5b6a315d38825247d68/dot/digest/block_import.go#L33 calls the `grandpaState.ApplyForcedChanges`
- Our intention is to move this method call to the method `handleBlock` located at `dot/core/service.go` line 191 https://github.com/ChainSafe/gossamer/blob/457fe39f7a12cb9eb04de5b6a315d38825247d68/dot/core/service.go#L191, right after calling the `onBlockImport.Handle` https://github.com/ChainSafe/gossamer/blob/457fe39f7a12cb9eb04de5b6a315d38825247d68/dot/core/service.go#L215

**Comment by ItIsOHM** [comment]
Ahh I see! Thanks for the help @EclesioMeloJunior!
So before I make an actual commit I wanted to confirm:

1- Remove the lines 33-36 from `block_import.go`
2- Add these lines after calling the `onBlockImport.Handle` in `service.go`

err = s.grandpaState.ApplyForcedChanges(&block.Header)
	if err != nil {
		return fmt.Errorf("applying forced changes: %w", err)
	}
	
I'm sorry if I am making any mistakes here, I'm just a beginner contributor :)

**Comment by EclesioMeloJunior** [comment]
Yep!! @ItIsOHM

**Comment by ItIsOHM** [comment]
Hello @EclesioMeloJunior, just opened a PR regarding this issue :D (https://github.com/ChainSafe/gossamer/pull/3361)
