### ISSUE TITLE
Save Peer ID Between Restarts

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#335]
We should maintain the peer ID of our node between restarts. I can potentially be written to the data directory alongside the DB.

**Comment by noot** [comment]
I think the best way to do this is to generate persist our p2p private key between restarts, since that'll always result in the same peer ID. instead of calling generateKey when starting p2p, we can read it from db if it exists.

**Comment by ansermino** [comment]
Planning on working on this. Would be useful for debugging for #325
