### ISSUE TITLE
Implement availability store

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3415]
## Issue summary

- this would be go translation of `polkadot/node/core/av-store` polkadot package
- See the implementers' guide: https://paritytech.github.io/polkadot-sdk/book/node/utility/availability-store.html

## Sub Issues
- [x] #3630 
- [x] #3629 
- [x] #3561 
- [x] #3628 
- [x] #3741

### Original issue notes:
- It should be able to perform following tasks in `AvailabilityStoreMessage` 
https://github.com/paritytech/polkadot/blob/153543b0c8c582e73f520e5c08cbe33bddfb5f69/node/subsystem-types/src/messages.rs#L418
- look here to see how those tasks are implemented in rust, https://github.com/paritytech/polkadot/blob/153543b0c8c582e73f520e5c08cbe33bddfb5f69/node/core/av-store/src/lib.rs#L1022

-  candidate backing subsystem generates available data, we have to be storing them using av-store (https://github.com/paritytech/polkadot/blob/153543b0c8c582e73f520e5c08cbe33bddfb5f69/node/core/backing/src/lib.rs#L559)

- this can be picked up immediately as this does not really have any dependencies.

**Comment by kishansagathiya** [comment]
I feel the best way to go about this PR would be to create a skeleton PR like https://github.com/ChainSafe/gossamer/pull/3497

Since, availability store is also a subsystem, there are a lot of ideas that we can borrow from that PR.

**Comment by edwardmack** [comment]
Closed since all containing issues are closed.
