### ISSUE TITLE
Construct a trie of chunks of erasure coded values

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3416]
## Issue summary

- To [make PoV available](https://github.com/paritytech/polkadot/blob/153543b0c8c582e73f520e5c08cbe33bddfb5f69/node/core/backing/src/lib.rs#L585), we need to validate erasure coded chunks against `expected_erasure_root`. We can do this by constructing a trie from erasure coded chunks. The root of that trie will be called `erasure_root`. We will check that the computed erasure root is the same as `expected_erasure_root`  from candidate descriptor.

- Currently in `lib/erasure`, we don't have ability to create a trie from erasure chunks.

## Other information and links

- [Use of this functionality in Polkadot's Candidate Backing](https://github.com/paritytech/polkadot/blob/153543b0c8c582e73f520e5c08cbe33bddfb5f69/node/core/backing/src/lib.rs#L601-L602)

- [Rust's implementation of this feature](https://github.com/paritytech/polkadot/blob/153543b0c8c582e73f520e5c08cbe33bddfb5f69/erasure-coding/src/lib.rs#L252-L274)

**Comment by EclesioMeloJunior** [comment]
@axaysagathiya can we close this issue? tip: you can type `Closes #...` in the PR description then when it is merged the linked issue will be closed automatically!
