### ISSUE TITLE
While syncing problematic block keeps in the state after `VerifyBlockJustification` fails

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#3468]
## Issue summary

- While syncing Gossamer retrieves and process blocks and the process steps are: `processBlockDataWithHeaderAndBody` and if the block contains a justification then it calls the `handleJustification`. So the first function, basically, inserts the block in the state (inserts it in the trie memory) and the second one verifies the justifications (signatures) to mark the block as finalized.

- If a block fails in the second step it keeps in the state, then the sync package logs the error and keeps working but this time the problematic block is the bestBlockHeader since it is the highest block in the state which leads to a problem in the sync package since then it will try to request the max blocks from the best block header so it will retrieve all blocks after the problematic one and this is not the intended behavior since it will lead to more problems such as failures to get epoch

- A possible approach is: whenever a failure happens in the bootstrap sync process we rollback until the latest finalized block
- NOTE: this doesn't actually happen when syncing to Paseo, but more so this is to ensure we do not corrupt our own state in the event we get an invalid block.

## Other information and links

- N/A

**Comment by EclesioMeloJunior** [comment]
This issue depends on GRANDPA integration, changing the `VerifyBlockJustification` to be called before the apply/import block process we need to refactor that function to don't rely on state, since currently it requires that the block to be in the state otherwise the block cannot be verified

**Comment by P1sar** [comment]
@timwu20 needs to move Verification function form feat/grandpa
