### ISSUE TITLE
Panic via RPC method “state_subscribeStorage” leads to denial of service (DoS)

### ISSUE THREAD

**Issue by pventuzelo** [ChainSafe/gossamer#3477]
# Panic via RPC method “state_subscribeStorage” leads to denial of service (DoS)

We ([@FuzzingLabs](https://github.com/FuzzingLabs)) found that the RPC method “state_subscribeStorage” can panic.

## Expected behavior

The function should not call a function that panics since it can be called using an RPC method.

## Environment

- Ubuntu 22.04.1
- go version go1.21.0 linux/amd64

## Steps to reproduce

This RPC call makes the node crash.

```bash
echo '{"id":1,"jsonrpc":"2.0","method":"state_subscribeStorage","params":["0x93528923842762059757263068645530213798460336021"]}' | websocat -n1 -B 99999999 ws://127.0.0.1:8546
```

## Root cause

The `notifyObserver` calls the `common.MustHexToBytes` which panics given a wrong input.

https://github.com/ChainSafe/gossamer/blob/d5c2c7fe3132b97fc6fa208bebcd254582ffb611/dot/state/storage_notify.go#L114

```
panic: cannot decode an odd length string
```

## Detailed behavior

```
panic: cannot decode an odd length string

goroutine 573 [running]:
github.com/ChainSafe/gossamer/lib/common.MustHexToBytes({0xc00609ca80, 0x31})
	github.com/ChainSafe/gossamer/lib/common/common.go:78 +0x158
github.com/ChainSafe/gossamer/dot/state.(*StorageState).notifyObserver(0xc005fbcbe0?, {0x5, 0xbc, 0x21, 0xd6, 0x7b, 0x37, 0x9, 0xbc, 0x7d, ...}, ...)
	github.com/ChainSafe/gossamer/dot/state/storage_notify.go:114 +0x2b4
github.com/ChainSafe/gossamer/dot/state.(*StorageState).RegisterStorageObserver.func1()
	github.com/ChainSafe/gossamer/dot/state/storage_notify.go:60 +0x3a
created by github.com/ChainSafe/gossamer/dot/state.(*StorageState).RegisterStorageObserver
	github.com/ChainSafe/gossamer/dot/state/storage_notify.go:59 +0x2a5
```

**Comment by pventuzelo** [comment]
Hi, do you have any update regarding the fix of this bug?

**Comment by kishansagathiya** [comment]
> Hi, do you have any update regarding the fix of this bug?

Have raised a PR with the solution. Thanks a lot for these issues and reminder.

**Comment by kishansagathiya** [comment]
@timwu20 @P1sar 
We have a whole lot of case where we use panic and these Must* functions. It would be a good exercise to go over them and handle them gracefully. I can create the issue, if you agree.

**Comment by timwu20** [comment]
I created issue #3735 to review all the RPC calls for Node MVP milestone.  I think we can address the usages of `Must` methods within the RPC calls in that issue.  I'm not sure if we need to address every usage of the `Must` functions in the rest of the codebase at this time.
