### ISSUE TITLE
feat(dot/parachain): add overseer signals

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3495]
## Issue summary
- From time to time parachain subsystems need information about relay chain. We use overseer to get these information and pass them on to different subsystems as overseer signals.

Now that we have overseer merged, we would be able to add these overseer signals, which are as follows
- ActiveLeaveUpdate
- BlockFinalized
- Conclude (Research and confirm if we can live without adding the Conclude signal)

I would suggest to add `ActiveLeaveUpdate` and `BlockFinalized` first.
Conclude is used to tell that work of all subsystems and overseer is done. So, I feel that it's probably not required, or there could be other ways to give that signal. But just see where it is used and confirmed if it is not necessary, keeping in mind difference in functionalities of rust and go.

- Since all Subsystems will have to process these message, we could also add an extra method in the SubSystem interface say `ProcessOverseerSignals`

 

## Other information and links
Link to OverseerSignal enum
- https://github.com/paritytech/polkadot-sdk/blob/7ca0d65f19497ac1c3c7ad6315f1a0acb2ca32f8/polkadot/node/subsystem-types/src/lib.rs#L151
- https://github.com/paritytech/polkadot-sdk/blob/7035034710ecb9c6a786284e5f771364c520598d/polkadot/node/overseer/src/lib.rs#L742

**Comment by kishansagathiya** [comment]
Doing this would lead to sub-issues for all subsystems as they will have to add logic to process these overseer signals.
i.e., collator protocol will have to process a `ActiveLeavesUpdate` message. Same goes for other subsystems and signals.

OverseerSignal is an enum in polkadot-sdk. We definitely do not need to create an enum for it.

**Comment by kanishkatn** [comment]
Thank you for creating the issue @kishansagathiya !

I'm not sure who's working on this; I'd suggest to generics for Signals, makes it easy to modularise the code. Here's a wip: https://github.com/ChainSafe/gossamer/blob/feat/k/disputes-coordinator-main/dot/parachain/dispute/initialized.go#L102

Question, Since we're going ahead with the direct-channel communication, it is going to use the same channel or are we looking to different channels for messages and signals?

**Comment by kishansagathiya** [comment]
> Question, Since we're going ahead with the direct-channel communication, is it going to use the same channel or are we looking to use different channels for messages and signals?

Same channel. I don't see a need for different channels tbh.
But would love to know your opinion if you think otherwise.

**Comment by kishansagathiya** [comment]
Closed with https://github.com/ChainSafe/gossamer/pull/3638
