### ISSUE TITLE
Implement MustEncode for Messages and Block Components

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#351]
I propose we implement `MustEncode` functionality for common types that should never fail. An implementation would look something like this:
```
func (st *SomeType) MustEncode() []byte {
    raw, err := codec.Encode(st)
    if err != nil {
        panic(err)
    }
    return raw
}
```

It seems the p2p message types, as well as block/header would be good places to implement this, there may be others.

Other uses of `Must***`:
https://godoc.org/github.com/cosmos/cosmos-sdk/codec#MarshalJSONIndent
https://github.com/ethereum/go-ethereum/blob/461291882edce0ac4a28f64c4e8725b7f57cbeae/common/math/integer.go#L73-L79

**Comment by monkrus** [comment]
@noot Is anyone currently working on this issue ?

**Comment by noot** [comment]
@monkrus nope, it is free to take! I don't think this issue is very relevant for network messages anymore, but would still be useful for Block and Header types.
