### ISSUE TITLE
some of the documentation are outdated or no longer exist

### ISSUE THREAD

**Issue by 1garo** [ChainSafe/gossamer#3577]
## Describe the bug

- `--base-path` command is outdated in the documentation.
- `gossamer account generate --ed25519` command don't exist anymore, it's all under `--scheme` now;

## Current Behavior

![image](https://github.com/ChainSafe/gossamer/assets/44412643/335aa05d-a47b-4dcd-a7fb-688778925989)

## Possible Solution

It's correct in the global flags, just need to adjust the documentation, if it's okay I could patch a PR for it.

## To Reproduce
Steps to reproduce the behaviour:

1. gossamer init --chain westend --key alice --basepath
2. gossamer account generate --ed25519

**Comment by 1garo** [comment]
There is a similar problem at: `gossamer account generate --ed25519`, I should open a separated PR for it?
![image](https://github.com/ChainSafe/gossamer/assets/44412643/6a550f9e-230c-4dec-be64-844a1dcc0c68)

**Comment by kanishkatn** [comment]
> There is a similar problem at: `gossamer account generate --ed25519`, I should open a separated PR for it? ![image](https://user-images.githubusercontent.com/44412643/282525381-6a550f9e-230c-4dec-be64-844a1dcc0c68.png)
> 
> I think that the command don't exist anymore, it is under `--scheme` now.

You're right! I think it's better to include it in the same PR. Maybe just update the issue to capture both?
