### ISSUE TITLE
`VerifyBlockJustification` fails to assert ancestry of blocks not in the `BlockTree`

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#3613]
## Describe the bug

- While syncing Gossamer faces the following problem:
```
2023-11-30T13:58:45Z ERROR block data processing for block with hash 0xb9b61c899c864d69a20a2f3abad55825f51ff09b493100dce632033c12a27014 failed: checking if descendant of highest block: getting header: pebble: not found pkg=sync
```
- This problem happened after we changed the flow of importing blocks through sync (https://github.com/ChainSafe/gossamer/pull/3576), basically, we only insert the block in the tree and execute it if its justification is valid otherwise we discard it.

- With this change, the function `VerifyBlockJustification` doesn't work properly because when it checks if a block belongs to the highest finalized chain. It requires that the block being verified is in the block tree, otherwise, it returns that cannot get the block header

- To fix this problem we should make sure that this function doesn't depend on blocks in the block tree and change it to verify blocks that were acquired through sync

**Comment by P1sar** [comment]
@EclesioMeloJunior please add issue that blocks this.

**Comment by P1sar** [comment]
@EclesioMeloJunior please remove duplicate https://github.com/ChainSafe/gossamer/issues/3468
