### ISSUE TITLE
Warp Sync

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#3625]
## Issue summary

- Implement WarpSync given that the full polkadot node defaults to providing a `WarpSyncProvider` when building a network using `sc_service::build_network`. [(code)](https://github.com/paritytech/polkadot/blob/de2d820e546159ab908ef0bc1eea1eb1e3edde67/node/service/src/lib.rs#L872)
- Potentially revisit syncing package so both full sync and warp sync can use common components

## Other information and links

- https://spec.polkadot.network/chap-sync#sect-sync-warp

**Comment by q9f** [comment]
As discussed, this is only relevant after we manage to sync all the chains fully.

**Comment by P1sar** [comment]
duplicate with  #3817
