### ISSUE TITLE
cli: update the init help

### ISSUE THREAD

**Issue by kanishkatn** [ChainSafe/gossamer#3673]
hey everyone, I was trying to run gossamer using a custom genesis raw file, I was executing
./bin/gossamer init --genesis custom.raw.json --base-path ~/.mypath
and then I got the error
2024-01-10T09:49:53-04:00 ERROR    failed to execute root command: unknown flag: --genesis
panic: unknown flag: --genesis

goroutine 1 [running]:
main.main()
	github.com/ChainSafe/gossamer/cmd/gossamer/main.go:33 +0x218
but then if you exec ./bin/gossamer init --help it shows the following example
The init command initialises the node databases and loads the genesis data from the genesis file to state.
Examples:
	gossamer init --genesis genesis.json
	gossamer init --chain westend

Usage:
  gossamer init [flags]

Flags:
      --force   force reinitialization of node
  -h, --help    help for init
But the flag genesis does not exist,  is the example is wrong or the flag genesis should be introduced?

**Comment by q9f** [comment]
Let's remove init. It's so pointless.

**Comment by kanishkatn** [comment]
> Let's remove init. It's so pointless.

I had kept init in for the BlockOps perspective. While running a node I find it easy to init the node, modify the config and then run the node. 

If we do wanna remove it, I believe it will be a big refactor since all the tests are using it.

Created a tracker for it here #3690
