### ISSUE TITLE
Include sync informations in the tip sync mode

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#3676]
## Issue summary

- Currently, Gossamer only shows sync informations like `target block`, `latest finalized block`, `connected peers` while in bootstrap mode and when it changes to tip mode those informations are not logged out

## Other information and links

- https://github.com/ChainSafe/gossamer/issues/3671

**Comment by q9f** [comment]
Not unrelated but maybe you want to also do it in the same pr: would be good to get the number of connected peers in the logs somewhere!
