### ISSUE TITLE
Failing `gossamer build-spec`

### ISSUE THREAD

**Issue by rllola** [ChainSafe/gossamer#3679]
## Describe the bug

I am trying to use `gossamer build-spec` to create a raw spec file as describe [here](https://chainsafe.github.io/gossamer/usage/import-runtime/#4-start-the-node) but the command fail with the followig error message

```
root@0107c1022466:/usr/src# gossamer build-spec --raw --chain westend-dev-spec.json
panic: runtime error: slice bounds out of range [:33] with capacity 0

goroutine 1 [running]:
github.com/ChainSafe/gossamer/lib/crypto.PublicAddressToByteArray(...)
	github.com/ChainSafe/gossamer/lib/crypto/keypair.go:76
github.com/ChainSafe/gossamer/lib/genesis.buildRawStructInterface({0x1717ec0?, 0xc0004b3a10?}, 0xc0004bb920)
	github.com/ChainSafe/gossamer/lib/genesis/helpers.go:288 +0x157d
github.com/ChainSafe/gossamer/lib/genesis.buildRawMapInterface({0x1596ca0?, 0xc00038b740?}, 0xc0004bb920)
	github.com/ChainSafe/gossamer/lib/genesis/helpers.go:265 +0x5ce
github.com/ChainSafe/gossamer/lib/genesis.buildRawMap({0xc0004e5c30, 0xc00038b740, 0xc0004ca198, 0xc0004ca030, 0xc0004e5cf0, 0xc0004ca180, 0xc0000a9980, 0xc0004ca000, 0xc0004ca1c8, 0xc0004ca1f8, ...})
	github.com/ChainSafe/gossamer/lib/genesis/helpers.go:190 +0x38e
github.com/ChainSafe/gossamer/lib/genesis.NewGenesisFromJSON({0x7ffea063d93e?, 0x18e5cca?}, 0x0)
	github.com/ChainSafe/gossamer/lib/genesis/helpers.go:90 +0x125
github.com/ChainSafe/gossamer/dot.BuildFromGenesis({0x7ffea063d93e?, 0x19083ad?}, 0x3?)
	github.com/ChainSafe/gossamer/dot/build_spec.go:59 +0x18
github.com/ChainSafe/gossamer/cmd/gossamer/commands.execBuildSpec(0x0?)
	github.com/ChainSafe/gossamer/cmd/gossamer/commands/build_spec.go:64 +0x274
github.com/ChainSafe/gossamer/cmd/gossamer/commands.glob..func2(0xc000219700?, {0x18d1211?, 0x4?, 0x18d11d9?})
	github.com/ChainSafe/gossamer/cmd/gossamer/commands/build_spec.go:30 +0x13
github.com/spf13/cobra.(*Command).execute(0x2965000, {0xc0000d7e60, 0x3, 0x3})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000359200)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	github.com/ChainSafe/gossamer/cmd/gossamer/main.go:31 +0x1df
```

## Expected Behavior

The command should create the raw spec for wested dev chai spec.

## Current Behavior

It is failing.

## To Reproduce
Steps to reproduce the behaviour:

1.  Try the command `gossamer build-spec --raw --chain westend-dev-spec.json` using the `westend-dev-spec.json` provided in the chain-spec folder.

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
panic: runtime error: slice bounds out of range [:33] with capacity 0

goroutine 1 [running]:
github.com/ChainSafe/gossamer/lib/crypto.PublicAddressToByteArray(...)
	github.com/ChainSafe/gossamer/lib/crypto/keypair.go:76
github.com/ChainSafe/gossamer/lib/genesis.buildRawStructInterface({0x1717ec0?, 0xc0004b3a10?}, 0xc0004bb920)
	github.com/ChainSafe/gossamer/lib/genesis/helpers.go:288 +0x157d
github.com/ChainSafe/gossamer/lib/genesis.buildRawMapInterface({0x1596ca0?, 0xc00038b740?}, 0xc0004bb920)
	github.com/ChainSafe/gossamer/lib/genesis/helpers.go:265 +0x5ce
github.com/ChainSafe/gossamer/lib/genesis.buildRawMap({0xc0004e5c30, 0xc00038b740, 0xc0004ca198, 0xc0004ca030, 0xc0004e5cf0, 0xc0004ca180, 0xc0000a9980, 0xc0004ca000, 0xc0004ca1c8, 0xc0004ca1f8, ...})
	github.com/ChainSafe/gossamer/lib/genesis/helpers.go:190 +0x38e
github.com/ChainSafe/gossamer/lib/genesis.NewGenesisFromJSON({0x7ffea063d93e?, 0x18e5cca?}, 0x0)
	github.com/ChainSafe/gossamer/lib/genesis/helpers.go:90 +0x125
github.com/ChainSafe/gossamer/dot.BuildFromGenesis({0x7ffea063d93e?, 0x19083ad?}, 0x3?)
	github.com/ChainSafe/gossamer/dot/build_spec.go:59 +0x18
github.com/ChainSafe/gossamer/cmd/gossamer/commands.execBuildSpec(0x0?)
	github.com/ChainSafe/gossamer/cmd/gossamer/commands/build_spec.go:64 +0x274
github.com/ChainSafe/gossamer/cmd/gossamer/commands.glob..func2(0xc000219700?, {0x18d1211?, 0x4?, 0x18d11d9?})
	github.com/ChainSafe/gossamer/cmd/gossamer/commands/build_spec.go:30 +0x13
github.com/spf13/cobra.(*Command).execute(0x2965000, {0xc0000d7e60, 0x3, 0x3})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000359200)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	github.com/ChainSafe/gossamer/cmd/gossamer/main.go:31 +0x1df
  ```
</details> 
</br>

## Specification

- go version: 1:21
- gossamer version: v0.8.0
- gossamer commit tag:  v0.8.0
- gossamer commit hash:
- operating system: `ubuntu:latest` (docker container)

**Comment by kanishkatn** [comment]
Do we need this command?

**Comment by rllola** [comment]
Yes.
It is part of your guide : https://chainsafe.github.io/gossamer/usage/import-runtime/#4-start-the-node

**Comment by q9f** [comment]
This is currently unmaintained. Which spec do you need @rllola?

**Comment by rllola** [comment]
I want to create my own spec file with my own custom runtime.

**Comment by kanishkatn** [comment]
It seems like you're using a raw spec as input. Could you share the spec you're using?

**Comment by rllola** [comment]
I was using the one provided in the repo - https://github.com/ChainSafe/gossamer/blob/development/chain/westend-dev/westend-dev-spec.json

There is no raw in the name. I am assuming it wasn't.

**Comment by kanishkatn** [comment]
Thank you for sharing @rllola . Sharing my initial findings here.

It is panicking while parsing `allowed_slots` in this block
```json
"babe": {
        "authorities": [],
        "epochConfig": {
          "c": [
            1,
            4
          ],
          "allowed_slots": "PrimaryAndSecondaryVRFSlots"
        }
      },
```

I believe we haven't updated the helpers to match the chain-spec. 

Please use the one from substrate for the time being. https://docs.substrate.io/reference/how-to-guides/basics/customize-a-chain-specification/

**Comment by kanishkatn** [comment]
> Do we need this command?

I am trying to get a better clarification on the usecase for this command.

Since the runtime development happens only with substrate at this time and substrate has the support to generate custom chain-spec, I fail to understand why we need to support this command. 

I'd appreciate any insights into this!

**Comment by rllola** [comment]
I haven't yet deep dive in the ecosystem of tools. I went with the first one I found which was gossamer (also because it had the useful `import-runtime` command).

If there is a better tool for this let me know and I will use it. In the meantime, if this is not maintained maybe it is better to deprecate it and link the tool in your doc to avoid people like me creating issues.

For the project I am working on, it is an integration tests tool to determine if node implementation follow the specs. It can test network behaviors or host API functions. It is for the last one I need a custom runtime.

**Comment by kanishkatn** [comment]
@rllola Thank you for creating the issue! I am happy to help for now.

Is it not possible to replace the runtime wasm blob in the `chain-spec-raw.json`?

**Comment by rllola** [comment]
Yes, that's what I ended up doing manually. But I was hoping to write a script to automatize the process.

**Comment by dimartiro** [comment]
@rllola if you are trying to create your own spec with your own runtime you have to use [`import-runtime`](https://chainsafe.github.io/gossamer/usage/import-runtime/#1-create-chain-spec-file-with-custom-runtime) command 

```
gossamer import-runtime --chain chain/westend/genesis.json --wasm-file yourownruntime.wasm > chain/westend-dev/westend-dev-spec.json
```

There is a known issue with this command, you can fix it adding the following lines [here](https://github.com/ChainSafe/gossamer/blob/b77e715d27745e88bd942284e8ef809d8d9818f0/cmd/gossamer/commands/import_runtime.go#L71) :
```golang
chainSpec.Genesis.Runtime = &genesis.Runtime{
   System: &genesis.System{},
}
```

> **Note:** I'll be opening a new PR to fix it 

And then rebuilding / re installing the client

```
make install
```

let me know if it works for you 😄

**Comment by dimartiro** [comment]
@rllola just to let you know that we already merged the fix so the only thing you have to execute now is:

```
gossamer import-runtime --chain chain/westend/genesis.json --wasm-file yourownruntime.wasm > chain/westend-dev/westend-dev-spec.json
```

**Comment by EclesioMeloJunior** [comment]
@dimartiro given that the fix was merged, can we close this issue?

**Comment by dimartiro** [comment]
Oh yeah! good catch, thks!
