### ISSUE TITLE
Create integration tests for availability store subsystem

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#3741]
## Task summary

Create tests to confirm that the availability store subsystem interacts as expected with the overseer.  This will involve creating a test harness that will generate messages and signals sent to the availability store subsystem, then verifying the state of data stored by the subsystem.  Based on the polkadot implementation, the following tests should be created:
- [x] testRuntimeApiErrorDoesNotStopTheSubsystem
- [x] testStoreChunkWorks
- [x] testStoreChunkDoesNothingIfNoEntryAlready
- [x] testQueryChunkChecksMeta
- [x] testStoreAvailableDataErasureMismatch
- [x] testStoreBlockWorks
- [x] testStorePovAndQueryChunkWorks
- [x] testQueryAllChunksWorks
- [x] testStoredButNotIncludedDataIsPruned
- [x] testStoredDataKeptUntilFinalized
- [x] testQueryChunkSizeWorks

And basic scenarios to test as described in the [Polkadot Parachain Host Implementers' Guide](https://paritytech.github.io/polkadot-sdk/book/node/utility/availability-store.html#basic-scenarios-to-test):
- [x] Stored data that is never included pruned in necessary timeout
- [x] Stored data is kept until we are certain it is finalized

## Specification reference

- [Polkadot Parachain Host Implementers' Guide](https://paritytech.github.io/polkadot-sdk/book/node/utility/availability-store.html#basic-scenarios-to-test)

## Other information and links

- [polkadot test code](https://github.com/paritytech/polkadot-sdk/blob/15a34838819f09f3bcfb3c05c08fb53934d8efc4/polkadot/node/core/av-store/src/tests.rs#L218)

**Comment by P1sar** [comment]
@edwardmack make Fork-awareness to separate issue

**Comment by edwardmack** [comment]
Closed with PR #3837
