### ISSUE TITLE
Give option to include public IP in node config

### ISSUE THREAD

**Issue by jimjbrettj** [ChainSafe/gossamer#3746]
## Issue summary

- Currently, to get our public IP we use HTTP requests to hit a few different endpoints to retrieve our public IP. This can be ok if your public IP is dynamic but we should optimize for using a static IP and thus this is not an ideal solution
- Instead, we should be able to include the public IP as part of the gossamer configuration

## Other information and links

- https://github.com/ChainSafe/gossamer/blob/fd779bfa239643cb144ae7d27a090cba3322ec88/dot/network/host.go#L127

**Comment by ramiroJCB** [comment]
Hello @jimjbrettj  I was looking for issues to do and this one got me interested.
But looking in the code I've found that `public-ip` is already being taken as a command flag and its documented in this [.md file ](https://github.com/ChainSafe/gossamer/blob/fd779bfa239643cb144ae7d27a090cba3322ec88/docs/docs/usage/command-line.md)

and this part of the [code ](https://github.com/ChainSafe/gossamer/blob/fd779bfa239643cb144ae7d27a090cba3322ec88/dot/network/host.go#L110-L119) is being use

**Comment by ramiroJCB** [comment]
Hello @jimjbrettj  :) hey I wanted to test this today and I've found that it's already tested on this  [file](https://github.com/ChainSafe/gossamer/blob/development/dot/network/host_integration_test.go#L52-L85) 
So probably we could close this issue after this discovery, what do you think ?

**Comment by jimjbrettj** [comment]
Hey @ramiroJCB, thank you so much for the investigation here! You are indeed correct, great catch :) 

We love getting contributions from outside the team, so feel free to take up any other issues you are interested in and don't hesitate to reach out with any questions.

I am closing this issue as resolved.

**Comment by ramiroJCB** [comment]
@jimjbrettj  will do ! thanks.
But hey I was trying to check your CONTRIBUTING.md and found you guys suggest to know [Polkadot Runtime Specification](https://research.web3.foundation/en/latest/polkadot/specifications/runtime.html) to be a part time contributor but the link is broken. you know of another link with similar content ?

**Comment by jimjbrettj** [comment]
yup here you go! https://spec.polkadot.network/id-polkadot-protocol
