### ISSUE TITLE
(dot/sync) tip sync request blocks in the queue

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#3747]
## Description

Every announce block is treated as a block to sync if Gossamer is in tip mode, and this is not optimal since the block sync happens in the same call it is announced.

### Changes

While in tip sync mode every block that is:
- `GREATER` than the latest finalized block and `GREATER` than our best block: just include in the queue an ascending request that should retrieve the max number of blocks until reaches the announced block
- `GREATER` than the latest finalized block and `LESS` than our best block: just include in the queue a descending request requesting the maximum number of blocks until a common ancestor block is found or it reaches the latest finalized block.

Those requests should be included in the `block request queue` and a goroutine should be able to handle them (remove the request from the queue) and update the queue inserting more tasks if needed (in cases where a single request does not fill the gap).

linked issue: https://github.com/ChainSafe/gossamer/issues/3705

**Comment by timwu20** [comment]
What is the problem that arises based on the current implementation?

**Comment by EclesioMeloJunior** [comment]
The problem is described here https://github.com/ChainSafe/gossamer/issues/3705. Sorry for not linking both issues

**Comment by timwu20** [comment]
@EclesioMeloJunior can you create an epic for this issue or put in an existing epic?

**Comment by EclesioMeloJunior** [comment]
Closing it given we plan to address the sync package using a different strategy, will create new issues an place them in the correct epic
