### ISSUE TITLE
Implement missing ext_crypto_ecdsa_generate_version_1 function

### ISSUE THREAD

**Issue by jimjbrettj** [ChainSafe/gossamer#3769]
## Issue summary

- Implement the ext_crypto_ecdsa_generate_version_1 host function

## Other information and links

- https://spec.polkadot.network/chap-host-api#id-ext_crypto_ecdsa_generate

**Comment by axaysagathiya** [comment]
Closing this as it's a duplicate of #2951. Which is already implemented by #3801 and https://github.com/ChainSafe/polkadot-spec/pull/14
