### ISSUE TITLE
fix(lib/epoch): use correctly very first slot number

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#3795]
## Describe the bug

- Currently, the `VerificationManager.VerifyBlock` method changes the epoch state if the header passed as argument is 1 
- It does not make sense for the verification to change the epoch state
- Makes more sense to set the first slot at finalization as said here https://github.com/ChainSafe/gossamer/pull/1640

**Comment by ramiroJCB** [comment]
Hello @EclesioMeloJunior  I wanted to pickup this ticket, But I  saw this [PR](https://github.com/ChainSafe/gossamer/pull/3841) and I wanted to asked you if that pr solve this current issue ?

**Comment by EclesioMeloJunior** [comment]
hey @ramiroJCB yes, this issue is being addressed by PR #3841, another related task that can be addressed on top of that PR is the issue https://github.com/ChainSafe/gossamer/issues/3866, it is a simple issue that can be tackled by you!
