### ISSUE TITLE
Implement ChainAPI Subsystem

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3840]
## Other information and links

- https://github.com/paritytech/polkadot-sdk/blob/aa68ea58f389c2aa4eefab4bf7bc7b787dd56580/polkadot/node/core/chain-api/src/lib.rs#L85

**Comment by kishansagathiya** [comment]
Requires skeleton and thus sub-issues, the issue could also use extra description. Estimating it at 8, until additional details and sub-issues arrives.

**Comment by P1sar** [comment]
duplicate
