### ISSUE TITLE
Improve Codec Coverage

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#391]
There seems to be some obvious cases missing from the codec test suite. Notably the following lines are never hit, some of which may be removable:

Encoding [32]byte:
https://github.com/ChainSafe/gossamer/blob/8fefce8600940155ca10e5359085d506804da672/codec/encode.go#L49-L50

Encoding common.Hash (this may be removable, custom type should be implicitly handled)
https://github.com/ChainSafe/gossamer/blob/8fefce8600940155ca10e5359085d506804da672/codec/encode.go#L59-L60

Encoding [][]byte:
https://github.com/ChainSafe/gossamer/blob/8fefce8600940155ca10e5359085d506804da672/codec/encode.go#L291-L298

Decoding [32]byte, common.Hash (common.Hash likely removable):
https://github.com/ChainSafe/gossamer/blob/8fefce8600940155ca10e5359085d506804da672/codec/decode.go#L65-L68

Decoding Interface whose value's kind is Slice or Array; kind is Struct:
https://github.com/ChainSafe/gossamer/blob/8fefce8600940155ca10e5359085d506804da672/codec/decode.go#L293-L294

https://github.com/ChainSafe/gossamer/blob/8fefce8600940155ca10e5359085d506804da672/codec/decode.go#L300-L301

Decoding Array Pointer:
https://github.com/ChainSafe/gossamer/blob/8fefce8600940155ca10e5359085d506804da672/codec/decode.go#L310-L311

Decoding Tuple (not pointer):
https://github.com/ChainSafe/gossamer/blob/8fefce8600940155ca10e5359085d506804da672/codec/decode.go#L375-L376

**Comment by noot** [comment]
we should probably not remove the `[32]byte` and `common.Hash` cases, I believe some common types depend on these cases. also, you would think those two cases are duplicates, since `common.Hash` is an alias for `[32]byte`, but unfortunately the type switch doesn't recognize that :/
