### ISSUE TITLE
Investigate PVF Host for candidate validation subsystem

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#3934]
## Issue summary

- The candidate validation subsystem uses the PVF (parachains' validation function) host to validate parachain block candidates.  This issue is to create the PVF host with the ability to validate the candidate's wasm blob.
- The PVF Host will handle validations for Precheck/Prepare and Validate/Execute
- The PVF Host will interface with a runtime instance to initilize and execute (or prepare) the parachain's validation function.
- Draft PR of overall architecture, and alignment session.

## Other information and links

- Polkadot's implementation of the pvf host can be found here: https://github.com/paritytech/polkadot-sdk/blob/aa68ea58f389c2aa4eefab4bf7bc7b787dd56580/polkadot/node/core/pvf/src/host.rs#L80
- https://paritytech.github.io/polkadot-sdk/book/node/utility/pvf-host-and-workers.html

**Comment by kishansagathiya** [comment]
@edwardmack Let's implement this as well. The following screenshot is a very strong reason to implement this
 
![Screenshot 2024-06-24 164718](https://github.com/ChainSafe/gossamer/assets/10185999/6dc8e152-df6c-4e2a-9e0c-51e0592b3919)

**Comment by kishansagathiya** [comment]
This is a going to be a decent chunk of work. Let's have a design doc for this one. 
Explanation of this in rust implementation is https://paritytech.github.io/polkadot-sdk/book/node/utility/pvf-host-and-workers.html
Let's come up with a design that could be inspired by this. something that makes sense to us and fits with golang
