### ISSUE TITLE
Implement Peer State

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#399]
The peer state is responsible for storing state information about peers. As peer events occur, the state should update itself.

The state will be queried by the RPC module, so we can use that to form some requirements. The required API is (see types [here](https://github.com/polkadot-js/api/blob/bed3f9f4c577fbe49ccfa67d5f86a82519e4cf3a/packages/types/src/interfaces/rpc/definitions.ts)):
```
networkState(): NetworkState {
    peerId // your peerId
}
peers(): []PeerInfo{
    PeerId,
    Roles,
    ProtocolVersion
    BestHash,
    BestNumber.
}
```

It seems that an event stream would work nicely for this. We can define a few events, such as `NewPeer`, `ExistingPeer`, `PeerDropped`, which contain the necessary information to update the state to reflect the actual network. The p2p layer (specifically the connection manager) can push these events into a channel which the pool polls.

**Comment by ryanchristo** [comment]
related to #444
