### ISSUE TITLE
fix(dot/state): fix could not find node panic

### ISSUE THREAD

**Issue by jimjbrettj** [ChainSafe/gossamer#3994]
## Issue summary

- When running in tip sync mode, we frequently run into a case where the runtime for a specific node cannot be found which causes the node to panic.
- The issue linked in the panic message is #3066 which means it could be related

This issue is considered resolved when the code has been updated to avoid causing us to hit this panic case. 

## Other information and links

![image](https://github.com/ChainSafe/gossamer/assets/40345116/dac3c248-4d06-46f8-a658-376dbfcf8a79)

**Comment by EclesioMeloJunior** [comment]
@jimjbrettj can I close this issues since they will be addressed/changed by the full sync refactor?
cc @P1sar

**Comment by jimjbrettj** [comment]
@EclesioMeloJunior yup, I am marking this as closed
