### ISSUE TITLE
commands to generate, import keys

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#404]
need to add a command that allows for keys to be generated/imported and saved in the <s>db</s> keystore directory as encrypted keystore files

something like this to generate a new account, which will generate a new keypair, encrypt the private key, save the encrypted private key to a file (name=public address?) 
```
gossamer account --generate --type=sr25519
> type password to encrypt new keystore: ****
```

something like this to import a key (assuming file is encrypted json)
```
gossamer account --import key.json
```

**Comment by dutterbutter** [comment]
I don't think we want to write this to the DB at all, we want to encrypt this file put it in the local Keystore and have it protected with your inputted passphrase similarly the way geth does it.

**Comment by noot** [comment]
@dutterbutter ok but where is the local keystore saved when we shut down the node? geth keeps track of your accounts between restarts

**Comment by dutterbutter** [comment]
@noot I think `~/.ethereum/keystore` so for us `~/.gossamer/keystore`

**Comment by noot** [comment]
true, okay that also works
