### ISSUE TITLE
make parachain subsystems concurrent

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#4080]
## Issue summary
We have written subsystem in an easier and simpler way initially. We have avoided writing concurrent code or anything that had complexity that could trouble us in testing it properly.

Eventually we have to add all these complexities back and make the code more concurrent and thus efficient and  fast.

Let's use this issue to track that work 

## Other information and links

-

**Comment by kishansagathiya** [comment]
Estimating this to 8, since this is would require enough work!

**Comment by P1sar** [comment]
duplicate
