### ISSUE TITLE
feat(parachains/candidate-validation): make sure ValidateBlock is implemented as expected

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#4083]
## Issue summary

Originated from this comment (https://github.com/ChainSafe/gossamer/pull/4036#issuecomment-2217725327)

So, eventhough we have Reason for Invalidity (https://github.com/ChainSafe/gossamer/blob/2afed8b30a09fe2d44af649f25f059413d77ef84/dot/parachain/candidate-validation/messages.go#L56) we never use it.
I would think that ValidateBlock (https://github.com/ChainSafe/gossamer/blob/2afed8b30a09fe2d44af649f25f059413d77ef84/dot/parachain/runtime/instance.go#L69) should return a reason for invalidity in validation result. Right now it doesn't since ValidationResult struct (https://github.com/ChainSafe/gossamer/blob/2afed8b30a09fe2d44af649f25f059413d77ef84/dot/parachain/runtime/instance.go#L25) does not have any field in it for reason for invality or any sort of error. 

- [x]  Let's make sure that ValidateBlock is implemented as expected. 
- [x] Let's have a decent number of tests for it. 
- [x] And differentiate between ReasonForInvalidity and errors occurred in executing ValidateBlock or any other internal error.

## Other information and links

-

**Comment by edwardmack** [comment]
Closing this issue because the work defined here was completed in PR #4036.
