### ISSUE TITLE
Start Polkadot FullSync Node

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/gossamer#4153]
### Description

Starting syncing Gossamer with Polkadot network in order to collect new issues and monitor how Gossamer operates in a production network

**Comment by EclesioMeloJunior** [comment]
Polkadot fullsync node started and is syncing from genesis, @P1sar can we close this issue?

![image](https://github.com/user-attachments/assets/804d5444-3a0a-4dc3-8326-ae2648220043)

**Comment by P1sar** [comment]
sure
