### ISSUE TITLE
Update database closed message

### ISSUE THREAD

**Issue by ryanchristo** [ChainSafe/gossamer#418]
## Expected Behavior

When running `gossamer init` and when gossamer has finished initializing, the "Database closed" message should specify which database.

## Current Behavior

When running `gossamer init` and when gossamer has finished initializing, the "Database closed" message appears twice and it does not specify which database has been closed.

## Steps to Reproduce

```
gossamer init
```

**Comment by ansermino** [comment]
These can probably also be `Debug` instead of `Info`
