### ISSUE TITLE
Migrate Badger v2

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#419]
We should switch `github.com/dgraph-io/badger` to `github.com/dgraph-io/badger/v2`.

There are minor breaking API changes, but I don't believe any apply to this project.

**Comment by thomasmodeneis** [comment]
I can work on this one if no one else is going to pick up.

**Comment by thomasmodeneis** [comment]
The upgrade have a collateral effect, the old database should be removed or migrated:

```
➜  gossamer git:(development-origin) ✗ /opt/gocode/bin/gossamer 
EROR[11-26|13:26:25] error starting gossamer                  err="cannot start db service: manifest has unsupported version: 4 (we support 7).\nPlease see https://github.com/dgraph-io/badger/blob/master/README.md#i-see-manifest-has-unsupported-version-x-we-support-y-error on how to fix this."
```

I just removed the `~/.gossamer` and it it seems to do the trick.

However, tests (go test github.com/ChainSafe/gossamer/cmd/gossamer) are failing with:
```
    genesis_test.go:99: could not find exported function BabeApi_configuration
```

and also this other error:
```
configcmd_test.go:426: Cannot acquire directory lock on "/home/user/.gossamer/state".  Another process is using this Badger database.: resource temporarily unavailable
```

But it seems like development branch is also with same error, so I suppose that its all good here.
