### ISSUE TITLE
Get the value of major syncing from sync package for network bridge

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#4207]
## Issue summary

majorSyncing means you are 5 blocks behind the tip of the chain and thus more aggressively download blocks etc to reach the tip of the chain faster.

the bool value of whether we are in `majorSyncing` is need in `ProcessActiveLeavesUpdateSignal` method of network bridge receiver side.  A link to the code here https://github.com/ChainSafe/gossamer/blob/a41ec3f09bb9d845e5f69b20eb66840da420a3e0/dot/parachain/network-bridge/receiver.go#L150-L151

- I am going to tag this issues inside the codebase as todo as well
- 
## Other information and links

-

**Comment by EclesioMeloJunior** [comment]
@kishansagathiya  I would like to mention that our sync approach does not have the concept of major sync, but we can simulate this by exposing the sync peer view struct which enables the caller to get the current target (highest announced block), so you can compare with the current best block and check how many blocks the node are behind the target.
