### ISSUE TITLE
Design Prospective Parachains subsystem

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#4241]
### Description

- [ ] Create and estimate the issues for prospective parachains

https://paritytech.github.io/polkadot-sdk/book/node/backing/prospective-parachains.html#prospective-parachains
https://github.com/paritytech/polkadot-sdk/blob/aa68ea58f389c2aa4eefab4bf7bc7b787dd56580/polkadot/node/core/prospective-parachains/

**Comment by P1sar** [comment]
@EclesioMeloJunior please make a doc PR to docs folder of repo + ask for @timwu20 and someone else to accept this work and review issues
