### ISSUE TITLE
Design Updates for Candidate backing subsystem to support Async backing + Elastic Scaling

### ISSUE THREAD

**Issue by axaysagathiya** [ChainSafe/gossamer#4245]
## Issue summary
All the design update issues to update the `Candidate Backing Subsystem` to support Async backing + Elastic scaling are listed in #3820 

## Other information and links

- 

### Acceptance criteria
- [x] changes specification should be written (or written within issues)
- [x] Estimable issues for changes that includes Async backing for Candidate Backing should be created

**Comment by axaysagathiya** [comment]
We need to remove the usage of Prospective parachain mode from the candidate backing subsystem.
As the `perLeaf` field of the `CandidateBacking` struct keeps a record of whether the active leaf has perspective parachain mode enabled or disabled, `perLeaf` will be removed in the future. Once we remove all the usage of this field.

**Comment by P1sar** [comment]
Issues that Axay have created during design
- #4327
- #4296
- #4329 
- #4324
-  #4316

**Comment by axaysagathiya** [comment]
There are minor changes in the logic to process the `validatedCandidateCommand::Second` message. Raised an issue for the same https://github.com/ChainSafe/gossamer/issues/4402

**Comment by axaysagathiya** [comment]
I raised issues for modifying the logic to process the [Second](https://github.com/ChainSafe/gossamer/issues/4403) overseer message and [Statement](https://github.com/ChainSafe/gossamer/issues/4404) overseer message

**Comment by axaysagathiya** [comment]
Need to raise an issue to imlement https://github.com/polkadot-fellows/RFCs/pull/103
