### ISSUE TITLE
Setting the log level for the sync package does not work

### ISSUE THREAD

**Issue by haikoschol** [ChainSafe/gossamer#4251]
## Describe the bug

Setting the log level for the sync package (and possibly others) on the command line (`--log sync=trace`) or in a config file has no effect.

## Expected Behavior

When the log level is set to `trace`, logs with that level are written to stdout.

## Current Behavior

When the log level is set to `trace`, logs with that level are not written to stdout.

## Possible Solution

Pass on the log level to `SyncService` and set it on the logger created in that package.

## To Reproduce

`bin/gossamer --log sync=trace`

## Specification

- go version: `1.23.2`
- gossamer version: `development`

**Comment by mittal-parth** [comment]
@haikoschol can I work on this?

**Comment by haikoschol** [comment]
> [@haikoschol](https://github.com/haikoschol) can I work on this?

Go for it! 🙌

**Comment by mittal-parth** [comment]
Raised #4407 for this @haikoschol 

thanks!

**Comment by axaysagathiya** [comment]
Closed by #4407
