### ISSUE TITLE
Default minimum number of peers is documented to be 5 but is actually 0

### ISSUE THREAD

**Issue by haikoschol** [ChainSafe/gossamer#4252]
## Describe the bug

According to [the CLI documentation](https://github.com/ChainSafe/gossamer/blob/04c7e6e57674a07fa1d4da90db128b57d8733351/docs/docs/usage/command-line.md?plain=1#L35), the default for the `--min-peers` flag is 5. But [in the code](https://github.com/ChainSafe/gossamer/blob/04c7e6e57674a07fa1d4da90db128b57d8733351/config/config.go#L46) it is actually set to 0.

## Expected Behavior

Documentation reflects what the code actually does.

## Current Behavior

The user is bamboozled.

## Possible Solution

I don't think 0 is a useful default and therefore suggest setting `DefaultMinPeers` to 5.

**Comment by haikoschol** [comment]
fixed by #4257

**Comment by jimjbrettj** [comment]
Reopening since this commit was reverted on dev, so it is still an active issue

**Comment by haikoschol** [comment]
Reclosing, since it was fixed again in #4291. :)
