### ISSUE TITLE
feat(statement-distribution) Implement `ReputationAggregator`

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#4345]
### Description

Reputation Aggregator is a struct that collects reputation changes and sends them in on batch to relieve network channels, needed  for `Statement Distribution`subsystem

This struct should be placed at `parachains/utils` folder since it should be available for more than one subsystem.

The struct:

```go

type ReputationAggregator struct {
   // a function that helps the aggregator to understand if such reputation should be dispatched to network subsystems at arrival or can stay longer in the batch
   sendImmediatelyIf func(rep UnifiedReputationChange) bool 
   byPeer map[peer.ID]int32
}

// effectivelly sends the collected reputations to the network subsystem
type (r *ReputationAggregator) Send(overseerCh) {
    overseerCh <- NetworkBridgeTxMessage {
       ReportPeerMessageBatch: r.byPeer
    }

    // clear the map after sending
    r.byPeer = map[peer.ID]int32{}
}

type (r *ReputationAggregator) Modify(overseerCh, peerID, rep) {
   if r.sendImmediatellyIf(rep) {
       // send rep w/o adding to the aggregator
   }
 
    // add to the aggregator
}
```

#### Links

- Reputation Aggregator definition: https://github.com/paritytech/polkadot-sdk/blob/8216235b480630c5a69636b172f5146711c88c9a/polkadot/node/subsystem-util/src/reputation.rs#L45
- Unified Reputation definition: https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/node/network/protocol/src/reputation.rs

**Comment by haikoschol** [comment]
It is also used in [bitfield distribution](https://github.com/paritytech/polkadot-sdk/blob/1e3b8e1639c1cf784eabf0a9afcab1f3987e0ca4/polkadot/node/network/bitfield-distribution/src/lib.rs#L44).

**Comment by DanielDDHM** [comment]
Can I tackle this issue?

**Comment by haikoschol** [comment]
> Can I tackle this issue?

Yes! It should be a pretty self contained task. At least that's how we imagined it. :)
