### ISSUE TITLE
Adding tests/coverage step into ci.go 

### ISSUE THREAD

**Issue by thomasmodeneis** [ChainSafe/gossamer#436]
In order to avoid having tests with false positives, I propose we add test step into the ci.go and update travis build.

## Expected Behavior

1. `go run scripts/ci.go test` should fail if any test fail and pass if succeed. 
2. `go run scripts/ci.go coverage` should report cov

## Current Behavior
Bash script is being used: `./scripts/ci.sh`

## Possible Solution

Create two steps for ci.go that allow test and coverage report / upload

**Comment by noot** [comment]
codeclimate will be used for coverage
