### ISSUE TITLE
runtime: when to use malloc, free in wasm calls

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#441]
in the runtime, every time memory is malloc'd, it needs to also be free'd. however, if an ext_ function mallocs some memory, it should not be freed until the entire runtime call is finished (since at that point we know the data is no longer needed), not when the ext_ function is finished. we need to investigate how to do this

**Comment by ansermino** [comment]
Are you sure that ALL allocations should be freed at the end of a call?

**Comment by noot** [comment]
@ansermino not totally sure tbh, I was assuming that runtime calls don't depend on something stored in memory from a previous runtime call, I could be wrong though
