### ISSUE TITLE
Cache Trie Root

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#442]
## Expected Behavior

Trie should cache its root.

## Current Behavior

Zero caching.

## Possible Solution
```go
type Trie struct {
    // ...
    dirty bool
    root common.Hash
}
```
When we update the trie we mark it `dirty`, when we retrieve the root hash we only re-calculate if the trie is marked dirty.

**Comment by noot** [comment]
closed since trie is purely in-memory and doesn't write to DB
