### ISSUE TITLE
Migrate Runtime Calls

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#458]
We need to move the majority of logic from the storage funcs in `runtime/imports.go` into our storage API. The storage API should be called from the imports in place of the existing logic.  

To support this we should instantiate a Trie inside the state service. For the time being lets leave the existing Trie alone.

By the end of this the runtime should depend on the storage API and not the Trie. We may beed the leave the existing Trie in there for now so we don't break tests (TBD).

**Comment by ansermino** [comment]
I believe all of these can be included, one of them is still stubbed but can be included in the API: https://github.com/ChainSafe/gossamer/blob/b47531a951e73920a49d06957516d2e593a594b6/runtime/imports.go#L145-L397
