### ISSUE TITLE
Remove DB Service et al.

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#461]
- [x] remove DB service
- [x] remove usages of Trie, Blocktree, Network Service
- [ ] remove rawDb
- [ ] remove `runtime.StorageRoot()` (replace `core.Service.StorageRoot()` with state service)

**Comment by thomasmodeneis** [comment]
Could you please provide a more detailed description ? I am trying to figure out what need to be changed here. Thanks.
