### ISSUE TITLE
Allow for other usages of Trie

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#513]
## Expected Behavior
Ability to create an instance of the Trie that does not depend on a DB and (maybe) doesn't support children tries. This basic trie is required for `ext_blake2_256_enumerated_trie_root`.

## Current Behavior

Only one type of trie is available (w/ DB and children tries).

## Possible Solution

This requires two things:
1) A basic trie implementation that is purely an in-memory trie 
2) An additional type that adds functionality to the basic trie type

**Comment by noot** [comment]
closing in favour of #667
