### ISSUE TITLE
Move Shared Test Helpers to Package

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#530]
Currently, we duplicate some code between packages. We should refactor this so that all these are within their own package, and imported to the tests that need them.

Some examples:
- Fetching test wasm blobs (eg. `runtime/wasmer_test.go`)
- `Exists(file)`
- `newRuntime()`/`newTestRuntime()`
https://github.com/ChainSafe/gossamer/pull/503#discussion_r368065174

**Comment by thomasmodeneis** [comment]
done
