### ISSUE TITLE
integrate scale custom encoding, clean up custom type encoding methods

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#611]
since SCALE now has EncodeCustom and DecodeCustom functions to check if a type has a custom encoding function, we can clean up instances of types that have types within them that can be custom encoded. 

SCALE may also need to be updated to integrate the Custom functions within EncodeTuple, EncodeArray, etc. same for Decode. additionally all custom functions should have the function sig `func (ms *MyStruct) Decode(r io. Reader) error` 

including but not limited to usages of: p2p message types, babe types, optional types

**Comment by Noc2** [comment]
just fyi: https://github.com/itering/scale.go
