### ISSUE TITLE
Use consistent log format in all packages

### ISSUE THREAD

**Issue by ryanchrypto** [ChainSafe/gossamer#669]
## Current Behavior

We are not using a consistent logging format in all of the packages within this repository.

## Expected Behavior

We use a consistent logging format in all of the packages within this repository.

## Checklist

- [ ] update contributing documentation or create a separate document that defines logging, printing, and error format to be used for all packages within this repository
- [ ] update packages to follow logging, printing, and error formatting (as much as possible)

**Comment by dutterbutter** [comment]
Closing due to staleness.
