### ISSUE TITLE
migrate keyring to keystore

### ISSUE THREAD

**Issue by ryanchristo** [ChainSafe/gossamer#691]
## Current Behavior

The `keyring` package is small and it is only being imported by the `keystore` package and should be included as its own file within the `keystore` package. We should also check the `crypto` package if any of the `keystore` methods should be migrated from either package to the other.

**Comment by noot** [comment]
what is the overlapping functionality?

**Comment by ryanchristo** [comment]
While migrating methods over from the `cmd` package in #680, I noticed the `keystore` package already imports `keyring` values and `crypto` types that might be nice to bundle in `keystore`. In the `cmd` package, `account` command would essentially import `keystore` and extend its functionality.

I did not explore this in depth and opened the issue to make note of something I wanted to explore. Not a high priority issue. Will switch back to low and send it to the icebox. I would like to keep it open though.
