### ISSUE TITLE
update "Integration Tests" document

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#710]
## Possible Solution

The integration tests on this page needs to explained in [this page](https://hackmd.io/-bEre9tGTp-vkVsK7FjDpg)

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by thomasmodeneis** [comment]
https://hackmd.io/3SUDQSbZRJmBcaWGVioTlg?view
