### ISSUE TITLE
Implement system RPC calls & error codes

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#731]
Work on each of these system RPC calls one PR at a time. Check mark completed calls as completed. 

**Reference:** https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md

**Please include integration test with RPC call implementation**

### System RPC Calls
- [x] [`accountNextIndex`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1516-system_accountnextindex)
- [x] [`addReservedPeer`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1512-system_addreservedpeer)
- [x] [`localListenAddresses`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#159-system_locallistenaddresses)
- [x] [`localPeerId`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#158-system_localpeerid)
- [x] [`removeReservedPeer`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1513-system_removereservedpeer)
- [x] [`syncState`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#1515-system_syncstate)

**Comment by edwardmack** [comment]
Questions:
- system_addReserverPeer/ system_removeReservedPeer, are we currently storing this info?  Need understanding where I would add/remove these.
- system_accountNextIndex - nonce for given account, where would I find this?
- chain related data, seems to come from genesis definition, but our current test chain doesn't contain this, so need to research/test how we're going to handle these things (system_chain, system_properties)

**Comment by EclesioMeloJunior** [comment]
Issue #1721 to `dryRun` RPC call created

**Comment by EclesioMeloJunior** [comment]
This issue was closed by PR #1712
