### ISSUE TITLE
lib/database: add a Flush method to the Database interface

### ISSUE THREAD

**Issue by mvdan** [ChainSafe/gossamer#758]
For example, if one wants to fully flush database writes to disk without closing the entire database.

It seems like the interface makes writes not flush by themselves, which I think is the right approach. You don't want every write to flush to disk completely, as that could slow down frequent writes.

/cc @noot @ryanchristo

**Comment by noot** [comment]
let us know if you're planning to work on this, otherwise one of us can pick it up in a bit!

**Comment by mvdan** [comment]
I'm not familiar with the badger Go packages yet, so I'll leave this up for grabs for now :) Otherwise, I might have a look next week.

**Comment by ryanchristo** [comment]
sweet, thanks @mvdan !

**Comment by mvdan** [comment]
I think we should also rename `Batch.Write` to `Batch.Flush`. It makes things more consistent; I initially read `Batch.Write` as to mean "write some bytes to the batch operation". And, after all, this method is very similar to a flush.

**Comment by monkrus** [comment]
Is someone working on this issue right now?

**Comment by noot** [comment]
@monkrus not currently!

**Comment by monkrus** [comment]
I would like to start working on it.

**Comment by noot** [comment]
@monkrus go for it :)

**Comment by noot** [comment]
@monkrus are you working on this? no worries if you aren't, I would like implement it asap since I think it is causing some issues with the node.

**Comment by monkrus** [comment]
@noot  Please implement it, as I am a bit behind.Sorry.
