### ISSUE TITLE
Investigate default node other than gssmr

### ISSUE THREAD

**Issue by ryanchrypto** [ChainSafe/gossamer#776]
##  Expected Behavior

If it is reasonable upon further investigation to have a default node that is separate from the gssmr node (currently being used as the default node), then the default node should be a separate node implementation with its own `node/default` configuration directory and package.

## Current Behavior

We are using the gssmr node as the default node and the foundation for creating new node toml configuration files using the export subcommand.

## Possible Solution

Create a new `node/default` directory with its own configuration files and defaults. Update the var `DefaultCfg` to use the default node rather than the gssmr node.

Maybe update the tests throughout to use the default node as the base but still test the gssmr node alongside the ksmcc node where appropriate.

**Comment by noot** [comment]
closing since this is no longer relevant/needed
