### ISSUE TITLE
Implement RPC call chain_getFinalizedHead

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#779]
## Expected Behavior
RPC call chain_getFinalizedHead should be implemented as described in https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md#chain_getfinalizedhead

## Current Behavior
RPC call for chain_getFinalisedHead has not been implemented.

## Possible Solution
[ ] implement chain_getFinalizedHead

**Comment by amerameen** [comment]
@noot did this
