### ISSUE TITLE
[Research] Crypto

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#8]
Should start to look for crypto libraries we need. Stuff we need so far:
* blake2-256 hash for trie 
* ed25519 curve + asymmetric crypto implementation (see section 7.3.2)

**Comment by dutterbutter** [comment]
A few GO implemented libraries listed [here](https://blake2.net/) at the bottom. We will need a kinda of audit on these packages to ensure they're achieving an accurate result.

There is an ed25519 curve go library but again I can't be certain that its what we exactly need. See [here](https://godoc.org/github.com/dyv/crypto/edwards/ed25519)

**Comment by noot** [comment]
I think this https://godoc.org/golang.org/x/crypto/blake2b should be good for blake2.

And these two for ed25519: 
https://godoc.org/golang.org/x/crypto/ed25519 
https://godoc.org/golang.org/x/crypto/ed25519/internal/edwards25519
