### ISSUE TITLE
use t.Cleanup() in tests

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#800]
in some tests where we use `defer(func ())` or some other cleanup methods, it would be prefered to change these to `t.Cleanup(func ())` so that the method that is deferred can be defined in the same function. 

eg. https://github.com/ChainSafe/gossamer/blob/39c7fab0e2a6af060fd624777cec532218bf7484/dot/network/host_test.go#L29

if we change utils.NewTestDataDir to include `utils.RemoveTestDir(t)` in t.Cleanup(), we can remove the need to have the `defer` in the test.

there are likely many places this cleanup can occur.

**Comment by monkrus** [comment]
Hello Team, Is this still an open issue?

**Comment by noot** [comment]
@monkrus Hey, yes it is!

**Comment by noot** [comment]
@monkrus no, the issue description is still accurate. let us know if you are planning to work on this! there is no one planning to pick this up so feel free to take it

**Comment by monkrus** [comment]
Yes, I am planning to work on it. Is this issue limited to specific files?

**Comment by noot** [comment]
@monkrus I think any usages of `utils.NewTestDataDir` can be cleaned up as per the description. I'll take a quick look and see if any other tests stand out.

**Comment by noot** [comment]
closing since this was done with #1042
