### ISSUE TITLE
testing tear down optimization - cleanup optimization

### ISSUE THREAD

**Issue by thomasmodeneis** [ChainSafe/gossamer#803]
## Expected Behavior

-

## Current Behavior

-

## Possible Solution

-

## Steps to Reproduce

1.
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [ ] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [ ] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by ryanchristo** [comment]
@thomasmodeneis could you help fill this issue out more?

**Comment by ryanchristo** [comment]
is this a duplicate of #800?

**Comment by noot** [comment]
can we close this due to lack of information?

**Comment by ryanchristo** [comment]
duplicate of #800
