### ISSUE TITLE
clean up and consolidate dot and lib utils

### ISSUE THREAD

**Issue by ryanchrypto** [ChainSafe/gossamer#804]
## Expected Behavior

- gossamer specific utils should all be in one location (`lib/utils` should move to `dot/utils` and `dot/utils.go` should be added or `dot/utils.go` should be added to `lib/utils`)

## Current Behavior

- gossamer specific utils are not in one location (split between `dot/utils.go` and `lib/utils`)

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [x] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
closing since the utils in these 2 packages serve different purposes
