### ISSUE TITLE
RPC tests for system_health should start 2 peers and assert correctly

### ISSUE THREAD

**Issue by thomasmodeneis** [ChainSafe/gossamer#807]
## Expected Behavior

-

## Current Behavior

-

## Possible Solution

-

## Steps to Reproduce

1.
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [ ] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [ ] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
closing since this functionality exists in `TestStableNetworkRPC`

**Comment by qdm12** [comment]
Done in 62204027a47ec40b2c9e9ecf6529018a06e244d1
