### ISSUE TITLE
BABE: Secondary Slot Leader

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/gossamer#814]
To deal with empty slots, BABE uses a round-robin fallback to select secondary slot leaders. If nobody claims that they are the primary at the beginning of the slot, then the secondary will author a block. 

_Primary Slot Leaders are granted based on the output of the VRF (if the node's VRF output for that slot number is lower than the threshold, then they are a primary slot leader). However, since the result is probabilistic, sometimes there will be no primary slot leaders, in which case a secondary slot leader should produce a block._ 

Currently, we have only have Primary Slot Leaders.

- see spec G.2.5. BabeApi_configuration 
- babe configuration from runtime should contain SecondarySlot boolean which we use to determine whether to use secondary slot leaders or not

**Comment by FlorianFranzen** [comment]
As SASSAFRAS (the BABE replacement) is just around the corner, we decided to tell all implementers not to implement the secondary slot feature. For the same reason we opted not do describe it in the spec.

**Comment by noot** [comment]
our `BabeConfiguration` already contains the `SecondarySlot` boolean, so nothing needs to be done currently for this issue.
