### ISSUE TITLE
Seal digest message byte array encoding issue

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#841]
## Expected Behavior
Calling chain RCP methods that return header with digest of type Seal should be formatting as detailed in Defniniton 3.7 in Polkadot Host Protocol Specification.

The byte in position 6 of the logs should be the byte expressing the length of the following byte array.

## Current Behavior

The byte 6 value does not match the expected length for the byte array included in Seal type digest message, example from gossamer: `0x0542414245ce62d17be303c07fc2104f7b345ac0273e1d4246fa5a20ca0260095b0605bd3668adbaca9ab8d8493e6f86507d72dc57a5bed89a976b8e0c6f7698588d3b9689`
```
byte 6 - ce - Scale enc length byte array, 16371 bytes!  
```
Calling chain_getBlock from within polkadot-js gives errors such as Struct: failed on 'logs':: Bytes: required length less than remainder, expected at least 331575618, found 112 I believe this error is due to incorrect data in this digest log.

## Possible Solution

- Unknown, but this is probably related to the current runtime.

## Steps to Reproduce

1. RPC call chain_getHeader and examine logs for digest type starting with 0x05
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by dutterbutter** [comment]
@edwardmack please review to see if its still an issue.

**Comment by dutterbutter** [comment]
Seems to have been resolved.
