### ISSUE TITLE
update “Command-Line” document

### ISSUE THREAD

**Issue by ryanchrypto** [ChainSafe/gossamer#868]
## Possible Solution

- update “Command-Line” document to include latest changes
- separate and distinguish `local flags` from `global flags` in command output
- see existing page at https://chainsafe.github.io/gossamer/command-line/

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [x] I am planning to submit a pull request to fix this issue myself

**Comment by RyRy79261** [comment]
@edwardmack I review on this document here with the updates I've made: https://hackmd.io/tBlAYz3dSw2pSlZS_6Lcuw
