### ISSUE TITLE
separate block builder functionality from BABE session

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#882]
## Expected Behavior

- the block building functionality (ie lib/babe/build.go) should be separated into a separate submodule
- this will make testing easier for other packages that need to build blocks, but don't need an entire BABE session

## Current Behavior

- block building requires a BABE session

## Possible Solution

- create a new BlockBuilder type that implements the functions in lib/babe/build.go

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by danigomez** [comment]
Hello everyone! 
I found this project while reading the Polkadot documentation and i found it very interesting!
I'm want to start working on this, but i'm not sure if this is still necessary, reviewing the code i found that the `BuildBlock` method was being used in the test file `dot/core/syncer_test.go`but it seems that it doesn't exists anymore.
Am i missing something?
Thanks!

**Comment by noot** [comment]
@danigomez hi, for this issue you would only need to modify the lib/babe package to create a separate `blockBuilder` type or such that has the functions used for block building (lib/babe/build.go) defined on it. the babe `Service` can then use this `blockBuilder` to build a block. let me know if you need more clarification!

**Comment by danigomez** [comment]
@noot Ok!, i will start working on this then.
