### ISSUE TITLE
Create messages package and migrate messages

### ISSUE THREAD

**Issue by ryanchristo** [ChainSafe/gossamer#885]
## Expected Behavior

- Each message type and its associated logic within `dot/network/messages.go` should be in its own file within a `lib/messages` package.

## Current Behavior

- We are continuing to add message types and their associated logic within one large file within network. We will be adding more message types for GRANDPA in the coming weeks.

## Possible Solution

- Create a `lib/messages` package with all the message types and their associated logic organized into individual go files, ie `lib/messages/block_announce.go`.

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
closing since this isn't relevant anymore, grandpa messages are encoded to `ConsensusMessage`
