### ISSUE TITLE
runtime: implement v0.6.x ext_ functions

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#905]
## Expected Behavior

imports_old.go (previous ext functions)
- [x] `ext_is_validator`
- [x] `ext_local_storage_get`
- [x] `ext_local_storage_compare_and_set`
- [x] `ext_network_state`
- [x] `ext_submit_transaction`
- [x] `ext_local_storage_set`

imports.go (new ext functions that are ready to be implemented)
- [x] `ext_kill_child_storage`
- [ ] `ext_child_storage_root`
- [x] `ext_clear_child_storage`
- [x] `ext_get_allocated_child_storage`
- [ ] `ext_secp256k1_ecdsa_recover_compressed`
- [ ] `ext_log`

New ext functions that are not specced yet (please create a new issue with the following fns in it when the above functions are implemented) 
- [ ] `ext_sandbox_memory_new`
- [ ] `ext_sandbox_memory_teardown`
- [ ] `ext_sandbox_instantiate`
- [ ] `ext_sandbox_invoke`
- [ ] `ext_sandbox_instance_teardown`
- [ ] `ext_sandbox_memory_get`
- [ ] `ext_sandbox_memory_set`

It will also be a good idea to look at the v0.7 ext_ functions (see spec Appendix E) to see what changes we will need to make to upgrade, and make the v0.6 functions easily wrappable for v0.7.

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by edwardmack** [comment]
Items remaining undone on checklist because these have not been spec'd yet.
