### ISSUE TITLE
Determine Config Parameters

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#91]
Need to decide what our present config options/sections are.

Starting Ideas:
- bootstraps nodes
- ports
- DB location

**Comment by ansermino** [comment]
Possible example config based on our current functionality:

```
[node]
DataDir = "~/.data"

[p2p]
BootstrapNodes = ["/ipv4/....", "/ipv4/...."]
NoDiscover = false
Port = 3000

[rpc]
Modules = ["system", "state", "chain"]
Port = 30303

```
@noot @dutterbutter @priom anything I'm missing? Anything we know we will need but don't have implemented yet?

**Comment by dutterbutter** [comment]
- Caching thresholds (later on)

[p2p]
MaxPeers?
