### ISSUE TITLE
update "Official Nodes" document

### ISSUE THREAD

**Issue by ryanchrypto** [ChainSafe/gossamer#916]
## Possible Solution

The contents of [this page ](https://hackmd.io/3rFlCMFoRLeg_CbxA0o7Xw) needs to be updated with the context and instructions required to run an official node for Polkadot, Kusama & Gossamer respectively 

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
closing as the "getting started" doc contains this info
