### ISSUE TITLE
update "Custom Services" document

### ISSUE THREAD

**Issue by ryanchristo** [ChainSafe/gossamer#917]
## Possible Solution

- Review the contents of [this hackMD link](https://hackmd.io/zTqpDYcVSaO8r3EmSfzhbg)
- If contents is missing, please amend with context followed by instruction 

## Checklist

- [x] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by danforbes** [comment]
This doesn't seem like an Issue that is relevant to anyone still on the Gossamer team, so I'm closing it. @noot and/or @timwu20 please feel free to reopen and add clarity if you disagree.
