### ISSUE TITLE
Ping/Send tests failing on CI

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#92]
## Expected Behavior

Tests should pass on CI.

## Current Behavior

Ping and send tests fail unexpectedly when running on Travis.

## Possible Solution

We should explore running in docker locally as this may be causing issues with networking. Furthermore, this may stem from an underlying issue or bug in libp2p or one of the related modules.

## Steps to Reproduce (for bugs)

Fails only on CI:
https://travis-ci.com/ChainSafe/gossamer/builds/107288141

## Context

Tests will be temporarily disabled until the issue can be resolved.

## Your Environment
* Version used:
* Commit hash: d0e551da4d5cb367358c31bdf3014e28a6860fc3
* Go Version: 1.12
* Operating System and version (include distro if Linux): Linux (default travis)
* Link to your project or reproducible gist:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by noot** [comment]
I'm still not seeing any failures locally, wondering if its a firewall issue. https://github.com/ipfs/go-ipfs/issues/5588
