### ISSUE TITLE
SCALE Codec - BigInt encoding produces invalid result 

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [ChainSafe/gossamer#931]
## Expected Behavior

The BigInt SCALE encoder does not produce the right output. Once a given number is encoded with `mode 3`, it cannot be decoded using the `Decoder` to the same (initial) number.
It is expected that once the `Encoder` encodes a given value, the `Decoder` should be able to produce the same initial value from the `bytes` given.

## Steps to Reproduce
I've tested the encoding of the number `1073741824`. These are the results of the encoding depending on the `encoder` that was used:

- `int32`, `uint32`, `int64`,  `uint64` encoders produce `[0, 0, 0, 64]`
- `Big.Int` encoder produces `[3, 64, 0, 0, 0]` (the number 3 comes from the `compact` encoding, thus the actual number is stored at the following bytes `64, 0, 0, 0`). The number `[64, 0, 0, 0]` however is wrong. The correct result should be `[3, 0, 0, 0, 64]`

Once we try to decode the input from above using the different types of decoders we get the following result:
- `int32`, `uint32`, `int64`, `uint64`decode the `[0, 0, 0, 64]` bytes to `1073741824`
- `Big.Int` decodes the `[3, 0, 0, 0, 64]` to `1073741824` (which is correct)
and `Big.Int` decodes the `[3, 64, 0, 0, 0]` bytes (produced by the encoder) to `64` 

This means that the big.int encoder is not encoding the bytes in the correct way (using Little Endian) 

## Specification

- go version: `go1.13.4 darwin/amd64`
- gossamer version: `development`

## Checklist

- [X] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [X] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
Hey, thanks for the issue! I opened a PR to address this: https://github.com/ChainSafe/gossamer/pull/932 

for binary.Write should have been writing it in little endian while encoding, but for some reason, BigEndian and LittleEndian modes seem to write the same thing here: https://github.com/ChainSafe/gossamer/blob/development/lib/scale/encode.go#L222
