### ISSUE TITLE
update execute_block call for runtime v0.6

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#941]
## Expected Behavior

- execute_block call should work with runtime v0.6
- spec says it takes BlockData (actually Block) and returns bool

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
related to #904

**Comment by amerameen** [comment]
Closing this since we are focusing on supporting v0.8
