### ISSUE TITLE
potentially broken tests in cmd/gossamer account 

### ISSUE THREAD

**Issue by arberiii** [ChainSafe/gossamer#984]
## Expected Behavior

Test of command gossamer account should confirm that it works properly under different situations(options, flags, etc.)

## Current Behavior

I checked in my device(MacBook Pro) what part of account.go file is covered and saw that some core parts are not covered, for example, there is a test scenario which supposedly tests command gossamer account --generate, however, this is what I get from coverage:
![image](https://user-images.githubusercontent.com/8199285/86799835-aaa58380-c072-11ea-90f0-f8a4343ae443.png)

I think in the tests the cli.Context is not created correctly because after creation the arguments of the context (ctx.Args()) is empty.

## Possible Solution

One quick possible solution is to actually simulate by using the app:
```go
// TestAccountGenerate test "gossamer account --generate"
func TestAccountGenerate(t *testing.T) {
	testDir := utils.NewTestDir(t)
	defer utils.RemoveTestDir(t)

	directory := fmt.Sprintf("--basepath=%s", testDir)

	err := app.Run([]string{"irrelevant", "account", directory, "--generate=true", "--password=false"})
	if err != nil {
		t.Fatal(err)
	}
}
```
This indeed tests the command because that part of code is covered:
![image](https://user-images.githubusercontent.com/8199285/86800545-6d8dc100-c073-11ea-8220-ed94f78257cb.png)

## Steps to Reproduce

If this is not happening only in my device, then you can reproduce it by:
1. Go to the cmd/gossamer directory
2. Run in the terminal > go test -coverprofile=coverage.out
3. Run in the terminal > go tool cover -html=coverage.out
4. When the page is opened in your browser, check the account.go file

## Specification

- go version: go1.14.4 darwin/amd64
- gossamer --version: 0.0.1
- operating system: macOS

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [ ] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
Thanks for pointing this out! I will take a closer look soon.
