### ISSUE TITLE
update blake2_128 and keccak_256 to conform to substrate

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#989]
## Expected Behavior

- see expected result by running integration tests: https://github.com/w3f/polkadot-spec/tree/master/test

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [x] I am planning to submit a pull request to fix this issue myself

**Comment by noot** [comment]
this may be blocked by #903

**Comment by noot** [comment]
see https://github.com/w3f/polkadot-spec/pull/264

**Comment by FlorianFranzen** [comment]
> see [w3f/polkadot-spec#264](https://github.com/w3f/polkadot-spec/pull/264)

To move forward on other Host API tests I separated the two broken test into w3f/polkadot-spec#295.
